### ISSUE TITLE
Feature Request: Run or debug current Ruby file

### ISSUE THREAD

**Issue by mydoghasworms** [rubyide/vscode-ruby#101]
Please provide a feature whereby one can execute or debug the current file being edited.

Otherwise you always need a `main.rb` file to run in the VSCode debugger or change the debugging profile, and this is tedious to maintain.

### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version:  2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]
- VS Code version: 1.7.2
- Operating System: Windows 10

**Comment by mydoghasworms** [comment]
Never mind, I just found out I can substitute ${file} for "program" in launch.json.

**Comment by EricDuminil** [comment]
Why isn't `${file}` the default in launch.json? I think I've never seen any `main.rb` file in my Ruby life.
