### ISSUE TITLE
Typing the shortcut to format the code in .rb files doesn't work

### ISSUE THREAD

**Issue by ecoderek** [rubyide/vscode-ruby#102]
### Your environment

- `vscode-ruby` version: 0.10.3
- Ruby version: 2.2.3
- VS Code version: 1.7
- Operating System: Mac OS El Capitan
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
⇧⌥F should format the code in .rb files. 

### Actual behavior
It prints out this character: Ï

### Steps to reproduce the problem
http://stackoverflow.com/questions/41051423/how-do-i-auto-format-ruby-or-erb-files-in-vs-code/41069963?noredirect=1#comment69350750_41069963

**Comment by ifreecarve** [comment]
I am also having this problem, although no characters are inserted into the buffer when I type the shortcut.  

* `vscode-ruby` version: 0.10.4
* Ruby version: 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
* VS Code version: 1.10.2 (1.10.2)
* OSX 10.11.6
* `debase-0.2.1`
* `ruby-debug-ide-0.6.0`

Steps to reproduce: neither `alt-shift-F` nor `cmd-shift-P` (and choosing `format document` cause the document to be formatted.  Selecting text does not affect things one way or the other.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
