### ISSUE TITLE
Wiggly heredoc support

### ISSUE THREAD

**Issue by adaedra** [rubyide/vscode-ruby#110]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: 2.3.0 (Although VS Code use by default system 2.0.0)
- VS Code version: 1.8.1
- Operating System: macOS Sierra
- Hardware (optional): 

Wiggly heredocs are not working with the extension's syntax coloring.

### Expected behavior

Wiggly heredocs are colored correctly, like in VS Code default Ruby syntax (Ruby extension disabled):

![capture d ecran 2017-01-06 a 10 08 36](https://cloud.githubusercontent.com/assets/823894/21713029/1b4e6860-d3f8-11e6-83d2-bcfc107e8b89.png)

### Actual behavior

Wiggly heredocs are not recognized. Futhermore, having unbalanced quotes in the heredoc breaks completely the syntax coloring for the rest of the file.

![capture d ecran 2017-01-06 a 10 10 14](https://cloud.githubusercontent.com/assets/823894/21713063/53cbaaae-d3f8-11e6-922e-7abfddf3cfeb.png)

### Steps to reproduce the problem

Open a ruby file containing a wiggly heredoc, e.g.:

```ruby
<<~EOF
I'm heredoc!
EOF
```

(Ironically, GitHub suffers from the same bug, so the snippet is incorrectly colored)

**Comment by jtgrenz** [comment]
This seems to still be broken, or maybe it broke again?

**Your environment**
vscode-ruby version: 0.17.0 (March 4 2018)
Ruby version: 2.4.3 
VS Code version: 1.21.1 
Operating System: macOS High Sierra

[![alt](https://screenshot.click/15-03-18-17-38-nyr6m-17r3b.jpg)](https://screenshot.click/15-03-18-17-38-nyr6m-17r3b.jpg)
