### ISSUE TITLE
Support goto definition for bundled gems ?

### ISSUE THREAD

**Issue by adamluzsi** [rubyide/vscode-ruby#111]
### Your environment

- `vscode-ruby` version: 
- Ruby version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
- bundler version: 1.12.5
- VS Code version: 1.8.1
- Operating System: macOS Sierra

### Expected behavior
it would be nice to have some way to make the goto definition work with bundled gems
such as using the `bundle list --paths` paths to scan references in gems or anything like that.

**Comment by pnagaraja1** [comment]
Is there a way to navigate to the external gem libraries outside workspace for methods and classes. i.e the gem libraries which are inside ruby installed folders.

**Comment by adamluzsi** [comment]
# I usually have 3 way for this

## with Bundler
```sh
$ bundle show "GEM_NAME_HERE" 
#=> returns path to the used requested gem + click on it in the vscode terminal
```
## with ruby built in Object#method 
```ruby
p object_that_method_intrests_me.method(:method_name_here).source_location
```
## Ruby Ripper
This is a little more complex, it's a [core package](http://ruby-doc.org/stdlib-2.0.0/libdoc/ripper/rdoc/Ripper.html) that allows you to parse ruby sources, and with that you can search between the tokens that includes the definition representation too.

**Comment by zouchao** [comment]
I have the same problem

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by rajagopalsubhash** [comment]
I think its a really important feature. Is there any plan to open it?

**Comment by stefansedich** [comment]
@rajagopalsubhash I had a PR merged a while ago now that should have fixed the issue of stepping into gems installed outside the workspace root: https://github.com/rubyide/vscode-ruby/pull/350

**Comment by Nowaker** [comment]
@wingrunr21 Please reopen, this is a valid feature request.

**Comment by batamire** [comment]
please reopen issue/feature request...

**Comment by ndan** [comment]
Install [solargraph](https://marketplace.visualstudio.com/items?itemName=castwide.solargraph), follow the instruction [here](https://github.com/castwide/solargraph/issues/87#issuecomment-505366440)

**Comment by loohawe** [comment]
please reopen issue/feature request...
