### ISSUE TITLE
No debugging with multiple ruby installs

### ISSUE THREAD

**Issue by ThomasSzabo** [rubyide/vscode-ruby#112]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: 1.9.3p551
- VS Code version: 1.8.1
- Operating System: OS X 10.12.2
- Hardware (optional): 

### Expected behavior
Debugger attaches to running rails server.

### Actual behavior
Debugger does not attach to running process.  The blue bar at the bottom of VS Code turns orange and immediately jumps back to blue. No debugging session is running and no output is sent to the Debug Console.

### Steps to reproduce the problem
I have two ruby versions installed. ruby 1.9.3p551 and ruby 2.2.1p85. Default ruby is the latter (2.2.1). I used to switch the current shell to use version 1.9.3 before I launch our Ruby on Rails server like this:
```bash
$ rvm use 1.9.3
$ bundle install
$ rails s -p 5679
```

The server works and is running on 0.0.0.0:5679, localhost:5679 and 127.0.0.1:5679. 
`gem list` is showing that `ruby-debug-base19x (0.11.31)` and `ruby-debug-ide (0.6.0)` are installed on the ruby 1.9.3. directory but not in ruby 2.2.1 directory.
I have a standard launch.json configuration:

![screen shot 2017-01-18 at 10 13 06](https://cloud.githubusercontent.com/assets/11858527/22057850/d034ed7c-dd66-11e6-9543-7f6f73f1d19e.jpg)

Am I missing something? Do I need to tell the debugger to `rvm use 1.9.3`? If so, how can I do this?

**Comment by rebornix** [comment]
It seems Code is loading env correctly. Can you try to launch Code from command line, which you run `rvm use 1.9.3`? 

Another way to tell our extension explicitly that which `rdebug-ide` you want to use by setting https://github.com/rubyide/vscode-ruby/wiki/2.-Launching-from-VS-Code#pathtordebugide. Moreover you may want to set up env directly in https://github.com/rubyide/vscode-ruby/wiki/2.-Launching-from-VS-Code#env

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
