### ISSUE TITLE
Debugger terminal error: Process failed: spawn rdebug-ide.bat ENOENT

### ISSUE THREAD

**Issue by Any8ne** [rubyide/vscode-ruby#113]
- `vscode-ruby` version: last
- Operating System: Windows 10
- Hardware (optional): 

When i debug a simple code exit these output
Someone can help me?

**Comment by sschuberth** [comment]
Looks like you need to manually run `gem install ruby-debug-ide` on Windows. Note that `ruby-debug-ide` is a native gem that requires installed [build tools](http://rubyinstaller.org/add-ons/devkit/).

**Comment by rebornix** [comment]
Please follow https://github.com/rubyide/vscode-ruby#install-ruby-dependencies and make sure you can run `ruby-debug-ide` directly on your machine

**Comment by the-nose-knows** [comment]
I've got the same problem, @rebornix. I followed the latest instructions. Please tell me which information needs to be collected for assessment, and where that information is typically located, directory-wise.

x64 Win 10 Pro box
Visual Studio Code `1.11.2`
vs-code Ruby `0.12.0`

**Comment by rebornix** [comment]
@the-nose-knows can you run `rdebug-ide xx.rb` directly in cmd? If you can do that, it might mean Code doesn't take your env, so you can try to launch VS Code from command line and debug again.

**Comment by the-nose-knows** [comment]
@rebornix 
`C:\WINDOWS\system32>rdebug-ide xx.rb`
> `=> Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.2.beta10, file filtering is supported) listens on 127.0.0.1:1234`

Is there an easier way to launch VS Code to take env without using command-line? I've got my taskbar pretty solid, and try to use command-line only when I actually need something that is command-line.

**Comment by rebornix** [comment]
@the-nose-knows can you add `showDebuggerOutput ` to your `launch.json` entry and tell me what's in the output channel?

The second issue you have is the port conflict, that's because you are trying to run `rdebug-ide` twice and both of the processes want to take port 1234

**Comment by the-nose-knows** [comment]
You'll have to tell me what precisely to set, and where, as it's not mentioned at these resources:
https://code.visualstudio.com/docs/extensionAPI/api-debugging
https://code.visualstudio.com/docs/extensions/debugging-extensions

Additionally Googling `+showDebuggerOutput +vscode` doesn't show anything meaningful near the top; neither did `+"showDebuggerOutput"`

**Comment by rebornix** [comment]
Sorry for that, our launch.json intellisense doesn't have a good discoverbility.

![screen shot 2017-04-26 at 4 45 06 pm](https://cloud.githubusercontent.com/assets/876920/25461778/cdc878fc-2a9f-11e7-8e99-4c512947de9b.png)

Add `"showDebuggerOutput": true` as above and take a look at the DEBUG CONSOLE (sorry for misleading you to output channel). A successful debugging session should generate what you can see above, so I'm willing to know what's the output on your machine.

**Comment by the-nose-knows** [comment]
Fixed!!! 

My new `launch.json`:

```
{
	"version": "0.2.0",
	"debugServer":4711,
	"configurations": [
		{
			"name": "Debug Local File",
			"type": "Ruby",
			"request": "launch",
			"cwd": "${workspaceRoot}",
			"program": "{workspaceRoot}/first.rb",
			"showDebuggerOutput": true
		}/*,
		{
			"name": "Debug Local",
			"type": "Ruby",
			"request": "launch",
			"program": "/c/Users/this_user/Desktop/ruby_ruby_stuff/first.rb",
			"showDebuggerOutput": true
		}*/
	]
}
```

What was I missing that was so important? The `"debugServer"`, the `"cwd"`; something else?

**Comment by rebornix** [comment]
I'm afraid Code doesn't pass a good `program` value https://code.visualstudio.com/docs/editor/debugging#_variable-substitution to us so that's why we can't debug anything

**Comment by the-nose-knows** [comment]
Cool, @rebornix -- I'll drop the minimal JSON here for future reference: 

```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Debug Local File",
			"type": "Ruby",
			"request": "launch",
			"cwd": "${workspaceRoot}",
			"program": "{workspaceRoot}/../my_script.rb",
			"showDebuggerOutput": true
		}
	]
}
```

**Comment by jannik-mohemian** [comment]
This might help someone: https://stackoverflow.com/questions/51722136/how-do-you-run-and-debug-ruby-on-rails-from-visual-studio-code/54477794#54477794 This worked for me

**Comment by quetzalcoatl** [comment]
For all people hitting this error on Windows, despite adding PATH to ENV in launch.json, mind this: https://stackoverflow.com/a/54993121/717732 - check the spelling of PATH on your OS!
