### ISSUE TITLE
VSCode Ruby Debugger w/ Spring - not hitting breakpoints

### ISSUE THREAD

**Issue by sb8244** [rubyide/vscode-ruby#114]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
- VS Code version: 1.8.1
- Operating System: OSX 10.11.6
- Hardware (optional): MacBook Pro

### Expected behavior

Running spring'd rspec through the debugger causes breakpoints to hit.

### Actual behavior

The rspec tests run, but no breakpoints are hit.

### Steps to reproduce the problem

Use a `bin/rspec` of 

```
#!/usr/bin/env ruby
begin
  load File.expand_path("../spring", __FILE__)
rescue LoadError => e
  raise unless e.message.include?("spring")
end
#
# This file was generated by Bundler.
#
# The application 'rspec' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require "pathname"
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../../Gemfile",
  Pathname.new(__FILE__).realpath)

require "rubygems"
require "bundler/setup"

load Gem.bin_path("rspec-core", "rspec")
```

Then use launch config:

```
    {
      "name": "RSpec - active spec file only",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rspec",
      "args": [
        "-I",
        "${workspaceRoot}",
        "${file}"
      ]
    },
```

### How can we know it's Spring?

Commenting out the spring `begin/end` and launching will hit breakpoints.

**Comment by fenixping** [comment]
+1

**Comment by brandoncc** [comment]
+1

**Comment by tvhung83** [comment]
+1, not hit any breakpoint at all, not even with a simple rb script, made me wonder what did i do wrong.

**Comment by suan** [comment]
@rebornix If you could point me out roughly where in the code to start and the rough approach to fix this, I might try my hand at it :)

**Comment by suan** [comment]
FYI, we believe this is dependent on work such that @HookyQR proposed here: https://github.com/rubyide/vscode-ruby/issues/18#issuecomment-204646057

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
