### ISSUE TITLE
Code doesn't honor rbenv config in .bashrc

### ISSUE THREAD

**Issue by alexminichino** [rubyide/vscode-ruby#115]
- `vscode-ruby` version: 0.6.0
- Ruby version: 2.3.3
- VS Code version: 1.8.1
- Operating System: Manjaro linux

I installed ruby with rbenv, but when running in debug mode from VSCode it says: 

> /usr/bin/env "ruby": no such file or directory

I've set enviroment variable $PATH in .bashrc:

> PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
> export PATH="$HOME/.rbenv/bin:$PATH"

and my launch.json is:
```
....
 {
            "name": "Rails server",
            "type": "Ruby",
            "request": "launch",
            "useBundler": true,
            "showDebuggerOutput": true,
            "cwd": "${workspaceRoot}",
            "pathToBundler":"${workspaceRoot}/bin/bundle",
            "program": "${workspaceRoot}/bin/rails",
            "args": [
                "server"
            ]
 },
...
```
Ty so much.

**Comment by rebornix** [comment]
@alexminichino can you try to add this config to your launch file https://github.com/rubyide/vscode-ruby/blob/master/package.json#L103 and see if it works?

**Comment by alexminichino** [comment]
@rebornix  thank you, i tried your solution but not woking.
Anyway i found the solution: when open VScode not load environments variables saved in .bashrc file, then if launch VScode from terminal it's work in debug mode.

**Comment by rebornix** [comment]
@alexminichino thanks for your investigation even though this Thank You is a little bit late :)
