### ISSUE TITLE
Working with Dockerized Development Environment

### ISSUE THREAD

**Issue by vkmagalhaes** [rubyide/vscode-ruby#116]
### Your environment

- `vscode-ruby` version: 
- Ruby version: 2.1.2
- VS Code version: 1.8.1
- Operating System: macOS Sierra (10.12.2)
- Hardware (optional): MacBook Pro (Retina, 15-inch, Mid 2015), i7, 16Gb

My app is a very complex rails monolith with lots of dependencies. I have the app folder in my host, but it only rans inside the docker container that we have built.

### Expected behavior

Run Linters inside docker containers 

### Actual behavior

Linters are broken because all my gems are only installed inside my app container

### Steps to reproduce the problem

Create a new rails app without ran `bundle install` and then keep an docker container with this app open with all dependencies installed.

**Comment by johnunclesam** [comment]
Any news on this?

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
