### ISSUE TITLE
connecting to debugger fails ECONNREFUSED

### ISSUE THREAD

**Issue by hunaid-hassan-confiz** [rubyide/vscode-ruby#121]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: 2.1.2
- VS Code version: 1.9.1
- Operating System: macOS Sierra
- Hardware (optional): 

### Expected behavior
It should connect to running instance of rdebug-ide

### Actual behavior
Cannot connect to running instance of rdebug-ide
Debug console outs
`Debugger error: Client: Error: connect ECONNREFUSED 127.0.0.1:1234`

### Steps to reproduce the problem

1. run rdebug-ide from terminal with rails app
2. attempt to start debugger using "Listen for rdebug-ide"

**Comment by jcrben** [comment]
Could you reproduce with a very simple rails app? Ideally you could provide a demonstration repo.

**Comment by shectermen** [comment]
same

**Comment by diazgilberto** [comment]
Same here.

**Comment by iamsuleyman** [comment]
have same problem

**Comment by iamsuleyman** [comment]
try to run `rdebug-ide --port 1234  --host 0.0.0.0 -- bin/rails s -b 0.0.0.0` and then attach to debugger

**Comment by DucNguyenVan** [comment]
have same problem

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
