### ISSUE TITLE
Reek: directory directives in config are ignored

### ISSUE THREAD

**Issue by guzart** [rubyide/vscode-ruby#124]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: 2.2.1
- VS Code version: 1.10.1
- Operating System: macOS 10.11.2

### Expected behavior

Ruby reek linter uses the directory directive configurations.

### Actual behavior

Ruby reek linter is ignore directive directory configurations.

### Steps to reproduce the problem

1. Initialize a new rails application
2. Add a `.reek` configuration file in the project root folder with the following content:  
```
"app/controllers":
  IrresponsibleModule:
    enabled: false
```
3. The IrresponsibleModule rule is highlighted in the controller

### Theory

I think the cause is that each file is being linted individually without reek knowing the context of its root directory? I don't know how to debug the extension so I can't dig any further.

The following command works as expected:
`/my_project_root $ reek app/controllers`

The following command doesn't pickup the directory directives:
`/my_project_root/app $ reek controllers`

PS: Thank for building this extension, it's great!!!

**Comment by tyler-king** [comment]
Just ran into this as well. Seems `config.reek` is not picked up.

**Comment by rebornix** [comment]
@tyler-king @guzart thanks for your feedback, I'll take a look.

**Comment by johnunclesam** [comment]
Any news on this? It's still there...

**Comment by loudandwicked** [comment]
+1 :)

**Comment by pelted** [comment]
Some additional info:

The .reek config is being used, but specifically the directory configurations are not working.

This works
```yaml
IrresponsibleModule:
  enabled: false
```

These examples do not
```yaml
exclude_paths:
  - core/db/migrate

"app/controllers":
  IrresponsibleModule:
    enabled: false
```

Running `reek` from the VSCode terminal in the workspace root does what it is supposed to and all the examples above in the `.reek` file work as expected.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by johanbaaij** [comment]
> The following command works as expected:
> `/my_project_root $ reek app/controllers`
> 
> The following command doesn't pickup the directory directives:
> `/my_project_root/app $ reek controllers`

Can confirm. I guess the trick would be to run reek from root with the relative file path as argument. Should this issue be reopened?

**Comment by guzart** [comment]
Hey @johanbaaij, here’s the PR related to this issue https://github.com/rubyide/vscode-ruby/pull/575
