### ISSUE TITLE
Feature request: Attaching debugger to existing process

### ISSUE THREAD

**Issue by pelletencate** [rubyide/vscode-ruby#125]
The latest (beta) versions of `ruby-debug-ide` have support for attaching a Ruby debugger to existing processes. A nice implementation is done in Rubymine, where you can get a list of currently running ruby processes and select one to attach a debugger to. It works flawless on OS X, whether I attach to a rails server, Sidekiq, even a Zeus slave, and the nice thing is, killing the debugger detaches it again, making the original process go as fast as it went before the debugger was attached.
 
It would be super awesome to be able to do the same in VSCode, and I think – since the code is already there in the ruby-debug-ide gem – it should be manageable to do. Also, this will solve any problem people have with the debugger not finding the right environment (e.g. with rvm in a custom gemset).

**Comment by rebornix** [comment]
VS Code has the process picker UI so the only missing part is this extension :) Nice suggestion.

**Comment by bjeanes** [comment]
Perhaps this might fix #163?

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by firelizzard18** [comment]
@wingrunr21 This is still an issue. Please fix it. It's a really simple change:

```diff
diff --git a/packages/vscode-ruby-debugger/src/main.ts b/packages/vscode-ruby-debugger/src/main.ts
index bd3ec94..e859e13 100644
--- a/packages/vscode-ruby-debugger/src/main.ts
+++ b/packages/vscode-ruby-debugger/src/main.ts
@@ -508,7 +508,11 @@ class RubyDebugSession extends DebugSession {
 
     protected disconnectRequest(response: DebugProtocol.DisconnectResponse, args: DebugProtocol.DisconnectArguments) {
         if (this.rubyProcess.state !== SocketClientState.closed) {
-            this.rubyProcess.Run('quit');
+            if (this.debugMode === Mode.launch) {
+                this.rubyProcess.Run('quit');
+            } else {
+                this.rubyProcess.Run('detach');
+            }
         }
         this.sendResponse(response);
     }
```

**Comment by pelletencate** [comment]
@firelizzard18 This wasn't a bug, this was a feature request. You've commented in the wrong issue.

@wingrunr21 Can we reopen this one please? I really think this is something that's going to be useful for virtually everyone who uses Ruby with resident processes (incl. all Rails devs)
