### ISSUE TITLE
Please add support for rubocop config file setting in settings

### ISSUE THREAD

**Issue by adamluzsi** [rubyide/vscode-ruby#133]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
- VS Code version: 1.10.2
- Operating System: Mac OS
- Hardware (optional): MacBook Pro (Retina, 13-inch, Early 2015)

### Expected behavior

It would be great to have option for rubocop config yml setting configuration option for rubocop linter

```json
{
    "ruby.lint": {

        "rubocop": {
            "configFilePath": "~/.rubocop.yml"
        },
    },
}
```

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
