### ISSUE TITLE
Rubocop not running on rails project

### ISSUE THREAD

**Issue by achernyak** [rubyide/vscode-ruby#134]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: 2.4.0p0
- VS Code version: 1.10.2
- Operating System: Mac

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
I expect `rubocop` to be run and detect errors inside my rails project. I have nothing in my `workspace` config and the following in my `user` config:

```
 "ruby.lint": {
        "rubocop": {
            "lint": true,
            "rails": true
        }
    }
```

### Actual behavior
There are no errors detected on a file that gets errors if I run the command line `rubocop`. There are also no errors in the `debug console` or `output`.

### Steps to reproduce the problem
Open a ruby file with errors.

**Comment by ypresto** [comment]
Is it occurs always or sometimes?
It might be fixed in below PR if latter:
https://github.com/rubyide/vscode-ruby/pull/106#discussion_r94130663

**Comment by achernyak** [comment]
Unfortunately it is happening all the time... I am not sure if there is just an additional setting missing or if it's the package issue.

I also just updated to the newest version of vscode and I'm still experiencing the same issue.

**Comment by achernyak** [comment]
Just an update it seems that even the base `ruby` linter isn't running. However other language linters are working.

**Comment by achernyak** [comment]
I was able to figure out the issue. Turns out I needed to run vscode from the cli.

**Comment by rebornix** [comment]
@achernyak it looks like Desktop application is not picking up your env in cmd, am I right?

**Comment by achernyak** [comment]
@rebornix you are absolutely right.

**Comment by diegoy** [comment]
Hey I have the same problem, is there a way to fix it without have to run `vscode` from the cli every time?
