### ISSUE TITLE
'%' does not jump between 'start' and 'end'

### ISSUE THREAD

**Issue by ytti** [rubyide/vscode-ruby#135]
```
def foo
  bar
end
```

When pressing ```%``` on ```def```or ```end``` cursor does not jump between them, is this expected?

**Comment by karuna** [comment]
I don't think jump to beginning / end of a block is recognized by vscode. 
https://code.visualstudio.com/docs/editor/editingevolved

**Comment by suan** [comment]
To add more context, @ytti I believe u're referring to the `%` key when using the vim extension correct?

If so, yeah, `%` when using the vim extension correctly moves you to the matching `(`/`)` or `{`/`}` etc in those cases, but doesn't work for `def`/`end`. I believe what's missing in the VSCode world is something like [matchit](http://www.vim.org/scripts/script.php?script_id=39) which is what makes such functionality work on actual Vim

**Comment by ytti** [comment]
Exactly. Other than I've not needed 'matchit' in vim for ages, dunno why. My Vim bundles:
```
[ytti@eng0.dllstx09.us.to.gin.ntt.net ~]% grep '^Bundle' .vimrc
Bundle 'gmarik/vundle'
Bundle 'kchmck/vim-coffee-script'
Bundle 'slim-template/vim-slim'
Bundle 'altercation/vim-colors-solarized'
Bundle 'nanotech/jellybeans.vim'
Bundle 'bling/vim-airline'
Bundle 'scrooloose/syntastic'
Bundle 'kien/ctrlp.vim'
Bundle 'ClockworkNet/vim-junos-syntax'
Bundle 'sunaku/vim-ruby-minitest'
Bundle 'jnwhiteh/vim-golang'
Bundle 'wting/rust.vim'
Bundle 'cespare/vim-toml'
Bundle 'rhysd/vim-crystal'
Bundle 'plasticboy/vim-markdown'
[ytti@eng0.dllstx09.us.to.gin.ntt.net ~]%
```

And '%' jumps between module/class/def/begin/.... and end

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by ytti** [comment]
I just tried on 1.21.1 with ruby 0.17.0 and issue does exit.

I can jump between () {} but not begin/end, class/end and such.

**Comment by wingrunr21** [comment]
Yep, I'm hoping a new approach to detected balanced pairs will solve this problem

**Comment by ytti** [comment]
Can you share more details, thanks!

**Comment by wingrunr21** [comment]
Not at this time as I have not looked at this issue specifically.

The highlighting and code folding features are pretty brittle in this extension due to how the balanced pairs are detected (see [here](https://github.com/rubyide/vscode-ruby/blob/master/src/providers/highlight.ts)). I'm hoping improvements to that code will also work here. That's as far as I've gotten though.

**Comment by ytti** [comment]
alright, thanks!

**Comment by Ibragim97** [comment]
Was this problem solved?
This would be very useful for navigating in a big code.
