### ISSUE TITLE
Keyboard shortcut to switch between a code file and its spec file

### ISSUE THREAD

**Issue by suan** [rubyide/vscode-ruby#137]
Would be great if there was a keyboard shortcut to switch between a code file to its spec, and vice-versa, just like https://github.com/tpope/vim-rails `:A` does - would this be something you'd be interested in building or accepting?

**Comment by rebornix** [comment]
@suan it sounds great! PRs-welcome!

**Comment by papa-whisky** [comment]
@suan You can do this in rails projects with the [Rails Go to Spec](https://marketplace.visualstudio.com/items?itemName=sporto.rails-go-to-spec) extension.

[Rails Run Specs](https://marketplace.visualstudio.com/items?itemName=noku.rails-run-spec-vscode) is also handy, to quickly run a whole spec file or just one line in the integrated terminal.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
