### ISSUE TITLE
Notify users if they try to set conditional breakpoint on old versions of debase or others

### ISSUE THREAD

**Issue by rebornix** [rubyide/vscode-ruby#138]
We are going to ship a new release which supports conditional breakpoints but since it requires a manual upgrade of `debase` to a beta version, we should warn users if they try to set conditional breakpoint when their `debase` doesn't support. Otherwise we'll receive a bunch of issues saying conditional breakpoints don't work :(

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
