### ISSUE TITLE
Inspect output in the console does not render multi lines

### ISSUE THREAD

**Issue by ginty** [rubyide/vscode-ruby#14]
### Your environment
- `vscode-ruby` version: 0.3.1
- Ruby version: 2.2.4p230
- VS Code version: 0.10.11
- Operating System: Windows
- Hardware (optional): 
### Expected behavior

I have some objects setup with a custom implementation of inspect. When I refer to these objects in the VSCode console during a debug session, I expect to see something like this:

``` text
-------------------
| Custom | Output |
-------------------
```
### Actual behavior

The line breaks are not evaluated and instead I get this:

``` text
-------------------\n| Custom | Output |\n-------------------
```

I can get it to print properly in the console by typing "puts obj.inspect", but it should really display the right thing if I just type "obj", just like it would in an IRB session for example.

From [this issue](https://github.com/Microsoft/vscode/issues/255) it sounds like VSCode internally has an API to produce multi-line output, and there doesn't seem to be anyway for me to influence this by changing the formatting of my inspect string.

So I was wondering if vscode-ruby could/should be splitting inspect output by newlines and presenting these to the console API as multiple lines?

Thanks again for vscode-ruby btw, its really great and has come on a lot in such a short time!

**Comment by HookyQR** [comment]
@ginty seems like this is a VS Code issue. I've provided further info on the issue you linked.

**Comment by rebornix** [comment]
@ginty thanks for reporting this issue. We are getting simple strings from ruby-debug and I thought there might be some potential printing problem but I didn't take it seriously. I'll see whether we can handle it by current VS Code functionality or we need to open issues to upstream.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
