### ISSUE TITLE
Block highlighting flip-flapping

### ISSUE THREAD

**Issue by vsrnth** [rubyide/vscode-ruby#140]
### Your environment

- `vscode-ruby` version: 0.10.4
- Ruby version: ruby 2.3.3p222 
- VS Code version: 1.11.2
- Operating System: macOS Sierra
- Hardware (optional): 

`ruby`, `ruby-debug-ide` and `ruby-debug-basex19` are installed.

### Expected behavior
Block starting should get highlighted, when the cursor is at the ending of the block.

### Actual behavior
Highlighting tends to work in the beginning, but stops working after sometime.

### Steps to reproduce the problem
A simple rails app with some code, should do the job.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
