### ISSUE TITLE
Linters stop functioning sometimes.

### ISSUE THREAD

**Issue by raldred** [rubyide/vscode-ruby#141]
### Your environment

Strange issue with linters, sorry if this is vague but I don't know how to debug what's going on.
Feels like a process either a linter or autocomplete is breaking something, maybe rubocop?

**Note: a restart of vscode fixes this for a while**

- `vscode-ruby` version: 0.10.4
- Ruby version: 2.4.0
- VS Code version: 1.11.2
- Operating System: OSX 10.12.4
- Hardware (optional): MBP

### Expected behavior
As changes to document are made, i'd expect linters to run and clean up any issues are now resolved or adjust the position of squiggles as lines move around.

### Actual behavior
Something happens, there's an error in the vscode developer tools console
shell.ts:475 An unknown error occurred. Please consult the log for more details.
No more details than that.

I do have some errors from rubocop
```
[Syntax]
unexpected token tLSHFT
(Using Ruby 2.1 parser; configure using `TargetRubyVersion` parameter, under `AllCops`)

//Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 Unexpected end of JSON input: 
SyntaxError: Unexpected end of JSON input
    at RuboCop.processResult (/Users/robaldred/.vscode/extensions/rebornix.Ruby-0.10.4/lint/lib/linters/RuboCop.js:19:22)
    at ChildProcess.spawned.on (/Users/robaldred/.vscode/extensions/rebornix.Ruby-0.10.4/lint/lib/linter.js:74:19)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Steps to reproduce the problem
I don't know how to reproduce I have a suspicion it's something to do with the rct complete crashes or breaking somewhere which then breaks everything else.

You can see in this screenshot that I've added a method (green addition in the gutter)
but the squiggles on line 237 and 243 are actually issues on 246 and 252

    [Style/NegatedIf] Favor `unless` over `if` for negative conditions

and

    [Style/TrailingWhitespace] Trailing whitespace detected

![screenshot 2017-04-20 18 05 22](https://cloud.githubusercontent.com/assets/37096/25243142/ef77da20-25f3-11e7-9ead-99bdad2cb43d.png)

**Comment by revett** [comment]
+1 

Seeing this every 10-20 minutes during development. Cold restart is required.

**Comment by rebornix** [comment]
This happens when rubocop cmd line doesn't return json as expected. Since a cold restart helps, I'll add some rerun the command but still emit the error message.
