### ISSUE TITLE
Problem setting up VSCode for Rails with Bundler

### ISSUE THREAD

**Issue by kalehv** [rubyide/vscode-ruby#142]
### Your environment

- `vscode-ruby` version: `0.10.4`
- Ruby version: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]` via RVM
- VS Code version: `1.11.2`
- Operating System: `macOS Sierra 10.12.4`
- Hardware (optional): `Macbook Pro 15" Mid-2012`

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Debugger starts Rails app

### Actual behavior
Error - 
```
/.rvm/gems/ruby-2.3.1/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find i18n-0.7.0 in any of the sources (Bundler::GemNotFound)
```

### Steps to reproduce the problem
Use the config I mentioned above and have following in the `launch.json`
```json
{
      "name": "Rails server",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rails",
      "useBundler": true,
      "showDebuggerOutput": true,
      "args": [
        "server",
        "-b",
        "0.0.0.0"
      ]
}
```

**Comment by rebornix** [comment]
As you are using bundler, you can follow https://github.com/rubyide/vscode-ruby/issues/16#issuecomment-211598794 to set up `bunder` in your launch config.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
