### ISSUE TITLE
No backtrace or exceptions being logged to the console

### ISSUE THREAD

**Issue by MichaelStankiewicz** [rubyide/vscode-ruby#149]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
- VS Code version: 1.12.1
- Operating System: OSX 10.11.6
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Exception should be displayed in the output of the debugger.

### Actual behavior
No exception logic is being displayed in any debugger windows.

### Steps to reproduce the problem
For example, when invoking a method on a class that does not support it, I would expect a 'NoMethodError' exception, but I don't see anything.

Example (the following should throw an exception):
def test( sentence )
    sentence.include? '('
    ...
end
test( 1 )

**Comment by rebornix** [comment]
This is what I get while debugging your code snippet in Ruby 2.2

![image](https://user-images.githubusercontent.com/876920/29245254-406e1a40-7f89-11e7-89d0-f3c0e9004f81.png)

Are you saying you didn't get anything in the debug console? Can you successfully set breakpoints?

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
