### ISSUE TITLE
Unable to start debugger with "/bin/bash --login

### ISSUE THREAD

**Issue by kattak2k** [rubyide/vscode-ruby#151]
Dear All,

Ruby version : 2.3.3
VSCode Version: 1.12.1
OS Version: Ubuntu 17.04
Language : Ruby on Rails

Please refer link -->https://github.com/Microsoft/vscode/issues/26334

# Steps to Reproduce:

### Background: 
I have installed "ruby on rails" using RVM, after that, I could only use the integrated terminal after running the command **"/bin/bash --login"** i.e. to run in a login shell. and I am also able to config the same in **settings.json** by modifying _"terminal.integrated.shellArgs.linux": ["--login"]_
### Issue: 
now when start the debug with **Rails server** option. I am getting error **Debugger terminal error: Process failed: spawn rdebug-ide ENOENT**. unable to understand what this is and how to fix. Please help... I guess this is also down to **shell login**

Best Regards!!
Ravi

**Comment by simonomis** [comment]
Sounds like your RVM config might be in .bash_profile so it's not setting up PATH to contain rdebug-ide unless you're in a login shell.

You could try moving the RVM initialisation into .bashrc, or setting this option: https://github.com/rubyide/vscode-ruby/wiki/2.-Launching-from-VS-Code#pathtordebugide

**Comment by kattak2k** [comment]
Thank you, when I tried to reload the rvm
 with command : **rvm get stable --auto-dotfiles**
  looks like it has again added to .bash_profile. and even if I had .bashrc my issue was not fixed.

results:
Upgrading the RVM installation in /home/maurya/.rvm/
    Removing rvm PATH line from /home/maurya/.mkshrc /home/maurya/.profile /home/maurya/.bashrc /home/maurya/.zshrc.
    Adding rvm PATH line to /home/maurya/.profile /home/maurya/.mkshrc /home/maurya/.bashrc /home/maurya/.zshrc.
    Removing rvm loading line from /home/maurya/.profile /home/maurya/.bashrc /home/maurya/.bash_profile /home/maurya/.zlogin.
    **Adding rvm loading line to /home/maurya/.profile /home/maurya/.bash_profile /home/maurya/.zlogin.
Upgrade of RVM in /home/maurya/.rvm/ is complete.**

**Comment by PedroVinicius** [comment]
Same problem here :disappointed:

**Comment by rebornix** [comment]
When we launch the debugger process, we didn't run the shell with login, it's a bummer I understand. Need to look into how to archive this properly on *inx.

**Comment by rebornix** [comment]
@kattak2k @PedroVinicius can you try latest version 0.14 and see if you can still see this problem? The latest version will try to load env with login shell at the very beginning.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
