### ISSUE TITLE
Simplest config for a basic Rails 5.1 project?

### ISSUE THREAD

**Issue by MrSkinny** [rubyide/vscode-ruby#153]
Version: 0.12.1
VSC: 1.12.1
Rails: 5.1
Ruby: 2.4.0

Followed the instructions in Readme, using all the defaults. Linting works, but in a standard Rails project, it doesn't recognize any Rails class methods. 

From what I can tell, the RubyLint docs say that Rails is meant to be included automatically:
https://github.com/YorickPeterse/ruby-lint/blob/master/doc/configuration.md#requires

Any tips?

My workspace `settings.json`:
```json
{
    "ruby.lint": {
        "ruby-lint": true,
        "ruby": true,
    	"rubocop": {
            "only": ["SpaceInsideBlockBraces", "LeadingCommentSpace"],
            "lint": true,
            "rails": true
    	},
        "debride": {
            "rails": true
        }
    },
    "ruby.locate": {
        "include": "**/*.rb",
    	"exclude": "{**/@(test|spec|tmp|.*),**/@(test|spec|tmp|.*)/**,**/*_spec.rb}"
    }
}
```

**Comment by idflyfish** [comment]
I have the same problem. I expect that I should get code completion/intellisense for anything in my project.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
