### ISSUE TITLE
[question] Separate scope for self keyword.

### ISSUE THREAD

**Issue by AndyBay** [rubyide/vscode-ruby#155]
Right now the keyword `self` does not have a separate scope (see below), instead it uses either `entity.name.function.ruby` or `variable.other.object.ruby` (dependent on the given context).
![class_self_ruby](https://cloud.githubusercontent.com/assets/1170184/26117463/f3ea13e8-3a66-11e7-95fa-0c6446692c22.png)

My question is if `self` has just not been given a scope, or if it is not meant to have one. Don't know if its ability to have one is dependent on an update from VS Code or not. As seen above the variable `name` inside `initialize` has the scope `support.function.core.ruby` which it shouldn't have, and while trying to read/ understand the `.tmLanguage` file it seems that `initialize` is supposed to have its own scope as well?

It is not an easy task to understand the tmLanguage style/ logic so I'm not sure how it is meant to be/ work.

**Comment by AndyBay** [comment]
#159

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
