### ISSUE TITLE
Wrong interpreter used for "ruby -wc"

### ISSUE THREAD

**Issue by atombender** [rubyide/vscode-ruby#156]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.3.3
- VS Code version: 1.12.2
- Operating System: macOS

### Expected behavior

That the extension always uses the right Ruby version I specify with `ruby.interpreter.commandPath`. This is my config:

```
	"ruby.interpreter.commandPath": "/Users/alex/.rbenv/versions/2.3.3/bin/ruby",
	"ruby.lint": {
		"rubocop": false,
		"ruby": true,
		"fasterer": false,
		"debride": false,
		"ruby-lint": false
	},

```
### Actual behavior

Seems to use some other version; I get syntax errors on syntax such as this:

```
def foo(a:)
end
```

This syntax is new in 2.2, I think. So it's evidently running an earlier version of Ruby.

If I close the window and reopen it, it correctly lints using 2.3.

### Steps to reproduce the problem

Happens every time I start VSCode. Stops happening if I close the window and reopen it.

**Comment by atombender** [comment]
@HookyQR @rebornix Any ideas? It's very annoying. It also affects other things the system-installed Ruby (2.0.0p648) doesn't like, such as character encodings.

I can't believe that I'm the only one that has this issue. I'm using Ruby via rbenv, and so the Ruby settings are part of my path; my `$PATH` has `$HOME/.rbenv/shims` before `/usr/bin`, but it looks like this is not the case when a window is initially opened in VSCode.

**Comment by rebornix** [comment]
`ruby.interpreter.commandPath` was introduced when we added the rctComplete support and this config is not applied to all features. I can see that it's annoying when we have multiple Ruby versions.
