### ISSUE TITLE
Error by using rvm 

### ISSUE THREAD

**Issue by fifiteen82726** [rubyide/vscode-ruby#157]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.3.3
- VS Code version:  1.12.2 (1.12.2)
- Operating System: OSX 10.12

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Run `rubocop` linter

### Actual behavior

<img width="941" alt="screen shot 2017-05-18 at 6 01 37 pm" src="https://cloud.githubusercontent.com/assets/6240395/26197233/12dfc980-3bf4-11e7-98ec-0a93c4eef8be.png">

Error 
```rb
/Users/Coda/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:2159:in `method_missing': undefined method `this' for #<Gem::Specification:0x3fe79c8ac0f0 powerpack-0.1.1> (NoMethodError) from /Users/Coda/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
```

### Steps to reproduce the problem

I put this into `.vscode/setting.json`

```json
{
    "ruby.lint": {
	"reek": false,
	"rubocop": true,
	"ruby": false,
	"fasterer": false,
	"debride": false,
	"ruby-lint": false
    }
}
```
Then go to a ruby file.

**Comment by Arakaki** [comment]
I suppose you should update your rvm version.
https://github.com/rubygems/rubygems/issues/1420

**Comment by rebornix** [comment]
@fifiteen82726 does @Arakaki 's answer help you out?

**Comment by fifiteen82726** [comment]
Thanks @Arakaki
