### ISSUE TITLE
Support formatting of a selection of a document

### ISSUE THREAD

**Issue by chrisnicola** [rubyide/vscode-ruby#158]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.3.1
- VS Code version: 1.12.2
- Operating System: OSX

This is a feature request to support formatting a selection of the document instead of all of it.

### Expected behavior

When working with VSCodeVim selection a part of the document (or resting on a line) and pressing `=` should format that selection (or line).

### Actual behavior

Nothing happens. The only way to format is to format the entire document using the Format Document command. The `=` formatting does work with Javascript and JSON (assuming Prettify JSON is installed).

### Discussion

VSCode provide a specific editor action for this `editor.action.formatSelection` which VSCodeVim is expecting to hook into to be able to format the document. 

https://github.com/Microsoft/vscode/blob/a26e004467f8bf6335f7c3babb7e6e6dfdf0aa72/src/vs/workbench/parts/welcome/walkThrough/electron-browser/editor/vs_code_editor_walkthrough.md#formatting

**Comment by hackhowtofaq** [comment]
Any news?

It is the only reason I'm still on Atom...

Ty

**Comment by chrisnicola** [comment]
I gave this some thought. One the challenges is formatting with context. If you select a particular line for example you need to consider the context of that line. The following *could* work but has some further challenges.

1. Use rubocop to "autocorrect" the entire document using formatting rules only
2. Only apply the changes that affect the selected lines.

The real problem is after the formatting 1 line could become multiple lines so tracking and applying that change correctly certainly poses a challenge.

**Comment by hackhowtofaq** [comment]
Why not format the selection according to the line just above the selection?

In my mind, a typical use is 
* copy paste + edit some code 
* format only the new code

in an already formatted document.

I think this is how Atom is formatting ruby code.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by hackhowtofaq** [comment]
No it is not fixed! I am waiting for this commit https://github.com/Microsoft/vscode/pull/35594

**Comment by wingrunr21** [comment]
I didn't say it was? The issue was closed because

1. I am doing cleanup of outstanding issues
2. The issue appears to be covered by #56 
3. We can't currently support this due to the vscode support not being there
