### ISSUE TITLE
Here-documents are not recognized as strings by the syntax highlighter

### ISSUE THREAD

**Issue by Doodpants** [rubyide/vscode-ruby#160]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.2.5p319
- VS Code version: 1.12.2
- Operating System: Windows 7 SP 1

### Expected behavior
Without the Ruby extension installed, here-documents are properly colored as strings, like so:

![good_colors](https://cloud.githubusercontent.com/assets/10993602/26361383/d8962040-3fa8-11e7-902e-0815a33944fe.png)

### Actual behavior
Here-documents are not recognized as strings, so in this example, the entire span of text between the apostrophe in "Here's" and the apostrophe in "name's" is colored as a string:

![bad_colors](https://cloud.githubusercontent.com/assets/10993602/26361413/e8813436-3fa8-11e7-82fa-2ad46dc5a859.png)

### Steps to reproduce the problem
Use a here-document in a ruby program, such as in the sample code below. (A here-document starts with "<<" followed by an identifier, and is terminated by the same identifier at the start of a line.)

```ruby
#!/usr/bin/env ruby

USAGE = <<END_USAGE
greetings.rb is a program that says hello to a specified person. Here's how to
use it:

  greetings.rb <name>

It will output a greeting message that is personalized using the name that was
passed in.
END_USAGE

if ARGV.size != 1
    puts USAGE
    exit
end

# The name's the first argument
name = ARGV[0]

puts "Hello, #{name}!"
```

**Comment by samhutchins** [comment]
Is this on the roadmap to be fixed? Other variants of HERE docs work fine:
```
<<-HERE
    This works fine
HERE

<<~HERE
    This also works fine
HERE
```

```
<<HERE
    But this doesn't work
HERE
```

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
