### ISSUE TITLE
Option to not include ":" (colon) in autocompletion and when selecting words

### ISSUE THREAD

**Issue by sullerandras** [rubyide/vscode-ruby#161]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.3.3
- VS Code version: 1.12.2
- Operating System: Mac OS X 10.11.6
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

Autocompletion includes list of words, not including the colon (`:` character) before the words.
Command+D selects only the word, but not the colon before it.

### Actual behavior

Autocompletion includes the colon before the word, even when the word in part of the module or class name or when the word is in a string.
Command+D also selects the colon before the word.

### Steps to reproduce the problem

Create a new ruby file, `hello_spec.rb` and add the content:
```ruby
describe Hello do
  let(:some_player) { create :player }
  it 'is valid' do
    some
  end
end
```

I want to type `some_player.should be_valid` in the `it` block, but no completions are offered automatically after typing `some`. I expect to see `some_player` in the autocompletion list. Pressing ctrl+space says "No suggestions".
If i start typing `:some` in the `it` block, the autocompletion suggests `:some_player`, but that's not what i want in this case.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
