### ISSUE TITLE
Use debugger with zeus

### ISSUE THREAD

**Issue by RomainEndelin** [rubyide/vscode-ruby#163]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.3.4
- VS Code version: 1.12.2
- Operating System: MacOS X Sierra
- Hardware (optional): MacBook Pro

- [x] Make sure you have `ruby`, `ruby-debug-ide` ~and `ruby-debug-basex19`~ installed before submitting your issue -- thank you !

### Expected behavior

I use the debugger on my tests with `Rspec`, and it works fine. But it won't work when I run my tests through `Zeus`.

### Actual behavior

I run the debugger, and it stops itself after 1-2sec. The tests haven't been run, and the debugger didn't catch any breakpoint.

### Steps to reproduce the problem

I tried with the following `launch` task:

```
        {
            "name": "Zeus",
            "type": "Ruby",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}/bin/zeus",
            "showDebuggerOutput": true,
            "args": [
              "test",
              "spec"
            ]
    }
```
Output:
```
Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.1, file filtering is supported) listens on 127.0.0.1:1234
```

Meanwhile I have a `zeus start` running in background, and I get this error when the debugger is ran:
```
clienthandler.go:108: write unix /Users/rendelin/dev/explore/rails4/.zeus.sock->: write: broken pipe
```

---

I also tried to run `zeus` with ` rdebug-ide --host 127.0.0.1 --port 1234 bin/zeus start` and attach the debugger with:
```
        {
          "name": "Zeus",
          "type": "Ruby",
          "request": "attach",
          "cwd": "${workspaceRoot}",
          "showDebuggerOutput": true,
          "remoteHost": "127.0.0.1",
          "remotePort": "1234",
          "remoteWorkspaceRoot": "${workspaceRoot}"
        }
```
Then, the `Zeus` process keeps pending until I run the debugger. When I run the debugger, `zeus` gets started, but the debugger stops immediately with no output.

Similarly, I tried running a normal `bin/zeus start` in background, running my tests through `rdebug-ide --host 127.0.0.1 --port 1234 bin/zeus test spec`, and then start the debugger in `attach` mode. But again, starting the debugger just unlock `rdebug-ide` and stops.

Thanks

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by truongsinh** [comment]
any update?
