### ISSUE TITLE
Meaning of red arrow?

### ISSUE THREAD

**Issue by BilalReffas** [rubyide/vscode-ruby#165]
What is the meaning of the red arrow?
<img width="356" alt="bildschirmfoto 2017-06-10 um 23 49 00" src="https://user-images.githubusercontent.com/8920003/27006563-7357c0ce-4e37-11e7-8328-ec00896fb57d.png">

**Comment by timriley** [comment]
That's an icon for .rb files provided by Code's icon theme.

Perhaps you're seeing this now because in the most recent Release, Code updated to use the "vs-seti" icon theme: https://code.visualstudio.com/updates/v1_13#_changed-setting-defaults

**Comment by BilalReffas** [comment]
Ouh 🙄 great to know thank you ! 😅
