### ISSUE TITLE
Curly braces auto-indent does not work as expected

### ISSUE THREAD

**Issue by pedrorolo** [rubyide/vscode-ruby#166]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.3.0
- VS Code version: 1.13.0
- Operating System: MacOSX
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

The following code to be indented as:

```
  #...
  def get_order_extras_from_params
    params[:extras].select{|e|
      #...
    }.map{|e|
      #...
    }
   end
```

### Actual behavior

The code gets indented as:
  
```
  #...
  def get_order_extras_from_params
    params[:extras].select{|e|
    #...
  }.map{|e|
  #...
}
end
```

This happens with all the curly braces, both for hashes and blocks.

### Steps to reproduce the problem

* copy paste the mentioned code into a module.
* Cmd-Shift-P reindent lines

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
