### ISSUE TITLE
Regex Syntax Highlighting

### ISSUE THREAD

**Issue by pavelbraginskiy** [rubyide/vscode-ruby#167]
Long, complicated regexes are a pain to dig through. It would be great if we could have syntax highlighting to make it easier. I know at least Jetbrains IntelliJ and ReSharper have this feature, and I've found it useful in the past. 

Not the most urgent feature-request, just something that would be nice to have.

Here's an example from IntelliJ:

![Example](https://www.jetbrains.com/idea/whatsnew/img/2017.1/idea_2017_1_regexp_1.png)

**Comment by rebornix** [comment]
@pavelbraginskiy in latest VSCode Stable and Insider, you can set 

```
    "editor.tokenColorCustomizations": {
        "textMateRules": [
          {
            "name": "string.exp",
            "scope": "string.regexp",
            "settings": {
              "foreground": "#FFFFFF",
              "background": xxx
            }
          }
        ]
    }
```

to customize the color of a scope.

**Comment by pavelbraginskiy** [comment]
@rebornix If I'm understanding it properly, that configuration sets the entire regular expression literal to a single color, which isn't the point of this issue. The point is to syntax highlight individual elements of the regex, like in the example image.
