### ISSUE TITLE
=begin/=end get indented wrong.

### ISSUE THREAD

**Issue by jots** [rubyide/vscode-ruby#174]
### Your environment

- `vscode-ruby` version: 0.12.1

### Expected behavior
=begin and =end get indented to beginning of line

### Actual behavior
if using =begin/=end inside of a method or class, it gets indented when calling
editor.action.reindentlines
this breaks the code.

Not certain if this is because of vscode-ruby.

**Comment by rebornix** [comment]
@jots it's majorly due to VSCode's indentation logic but since I'm the owner as well so we can track it here.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
