### ISSUE TITLE
Cannot read property 'offenses' of undefined rubocop

### ISSUE THREAD

**Issue by mmahalwy** [rubyide/vscode-ruby#175]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version:  2.1.8
- VS Code version: 1.13,1
- Operating System: MacOS

### Expected behavior
Rubocop to show errors

### Actual behavior
![image](https://user-images.githubusercontent.com/3749095/27975171-fc836c0c-6315-11e7-81d0-5cd9a4af83a9.png)

### Steps to reproduce the problem
Creating an offense for rubocop

**Comment by mmahalwy** [comment]
Okay! The problem is rooted from here: https://github.com/rubyide/vscode-ruby/blob/master/lint/lib/linters/RuboCop.js#L9

The `--force-exclusion` is what is causing the problem in that particular project and thus the result has `files: []`.

**Comment by gerrywastaken** [comment]
I couldn't actually replicate your issue. Your "steps to reproduce" might not be complete.

**Comment by mmahalwy** [comment]
@gerrywastaken could be rubocop version?
