### ISSUE TITLE
end followed by method call not matched correctly

### ISSUE THREAD

**Issue by jstastny** [rubyide/vscode-ruby#177]
### Your environment

- `vscode-ruby` version: 0.12.1

### Expected behavior

Given the following example:
```ruby
[1,2].map do |n|
    [n, 'hello']
end.to_h
```
the highlighter should match the `end`.

### Actual behavior
The `end` in the example above is not matched. This is because it is followed by `.to_h`. I believe this was introduced in https://github.com/rubyide/vscode-ruby/commit/def1c9cd599702d2b9d73b922198682067e368de#diff-bf827c0b089d3f27ec77695584cb76c0L68 as the string `end.to_h` is matched by the old RegEx: `^(\s*)(end|(end\..*))\s*$`, but not with the new one: `(\s*)end\b[\.\s#]?\s*$`.

The easiest way to resolve this is to revert the change of the line. Should I proceed with that and prepare PR for this?

**Comment by greggilbert** [comment]
Just to add onto this, the same thing happens for defs with anything after `end`. For example:

```
def foo
    p 'okay'
end # comment
```

It doesn't know how to match the end there. Maybe it should strip off all text after `end`?

**Comment by rebornix** [comment]
@greggilbert good catch :) we should ignore comments after `end` at least.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
