### ISSUE TITLE
Feature Request: add TDC(test driven complete) support

### ISSUE THREAD

**Issue by doun** [rubyide/vscode-ruby#179]
user workflow:
  - focus on test file
  - switch to implement file
  - TDC completes with test file executed.

Things to do:
  - using TDC args rct-complete --filename='' --test="{file}@{line}", if we have last_test_file
  - add an event listener to workspace, save last_test_file
  - optional: add command for ruby-toggle-file

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
