### ISSUE TITLE
No support for debugging spawned processes

### ISSUE THREAD

**Issue by rebornix** [rubyide/vscode-ruby#18]
Issue reported by @ronen-burin

OS: Mac

Reproduce steps:
1. Run `rdebug-ide --host 127.0.0.1 --port 1234 ~/.rvm/gems/ruby-2.2.3/gems/thin-1.5.0/lib/thin start`
2. Choose `Listen to rdebug-ide` configuration as below

```
{
            "name": "Listen for rdebug-ide",
            "type": "Ruby",
            "request": "attach",
            "cwd": "${workspaceRoot}",
            "remoteHost": "127.0.0.1",
            "remotePort": "1234",
            "remoteWorkspaceRoot": "${workspaceRoot}"
        }
```

But VS Code doesn't connect to rdebug-ide.

**Comment by rebornix** [comment]
@HookyQR I fail to repro this issue but it constantly fails on @ronen-burin's machine. Can you help have a try on your Mac to see whether it's a valid issue? Thanks!

**Comment by ronen-burin** [comment]
Some more info: 
ruby version: 2.2.3p173
VSCode version:  0.10.11 (0.10.11)
VSCode-Ruby version: 0.3.1

Note that I'm running 2 thin instances:
thin start -p 3000 -s 2

**Comment by HookyQR** [comment]
@ronen-burin. Taking a look now.

**Comment by ronen-burin** [comment]
Thanks :-)

Ronen.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
