### ISSUE TITLE
Clicking on a line in the Debug Console doesn't switch focus to the file in question

### ISSUE THREAD

**Issue by perlun** [rubyide/vscode-ruby#180]
First, let me say a huge thanks for a **great** extension! I've been using it for a while for just editing Ruby projects, but hadn't tried the debug experience with it. It's the best I've ever seen with Ruby, great work from you all!!!

----

### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version: 2.4.1
- VS Code version: 1.14.0
- Operating System: macOS
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

Clicking on a link from e.g. `rspec` output should switch keyboard focus to the file in question.

### Actual behavior

Focus is moved to the editing field in the Debug Console, where you can enter Ruby code.

### Steps to reproduce the problem

1. Run the `rspec - active file spec only` task.
2. Click on a link to a line number in a file.
3. Focus is on the &gt; line below
4. If i Cmd-click on a line, a new tab opens in vscode with the correct behavior, but if I just click without cmd it does not. Is the bug in vscode-ruby or in vscode?
5. Also, *if the file is not already open*, it also works correctly! So only if the file was already active and visible the bug occurs, it seems.

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/630613/28202641-f5aff986-687e-11e7-90b2-d9c38f5d07b8.png">

**Comment by rebornix** [comment]
Moving the result to integrated terminal might solve this problem

**Comment by rebornix** [comment]
Re https://github.com/Microsoft/vscode/issues/27713

**Comment by perlun** [comment]
> Moving the result to integrated terminal might solve this problem

How do you do that? I tried setting the `console` setting which didn't work for me. See https://github.com/Microsoft/vscode/issues/32696

**Comment by perlun** [comment]
Ping @rebornix - it would be great to be able to move the result to integrated terminal. Would you have time to look into it? (or: would you accept a PR that fixes it?)

**Comment by perlun** [comment]
@rebornix and @wingrunr21 With 0.17.0, these references are no longer underlined, and you cannot click them. This is sad, it's a nice feature that used to work in some earlier version. (0.14? 0.15?)

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
