### ISSUE TITLE
use both vscode-ruby and vscodevim is lag

### ISSUE THREAD

**Issue by bestv2** [rubyide/vscode-ruby#181]
### Your environment

- `vscode-ruby` version: 0.12.1
- Ruby version:  2.4.1
- VS Code version:  1.14.1
- Operating System:  Mac OS 10.12.5 
- Hardware (optional):  MacBook Pro (Retina, 15-inch, Mid 2015)

when I use both vscode-ruby and vscodevim, the editor become very slow with more than 30 second to respond my input.

**Comment by rebornix** [comment]
@bestv2 they are executed in the same process so maybe something is blocking the main loop of nodejs. Good catch though!

**Comment by bestv2** [comment]
@rebornix thanks for your reply. I've built vscomde-ruby myself and install through vsix,  very strange

**Comment by rhys-vdw** [comment]
Ah, I didn't realize this was caused by the two packages in unison. This one is really bad. Affects a few devs at our work.

**Comment by shelly-w** [comment]
Yes, this also happened on me. Typing latency disappeared when I disabled vscode-ruby.

My environment:
* Operating System: Mac OS 10.13.1
* VS Code version: 1.21.1
* vscode-ruby version: 0.17.0
* Ruby version: 2.5.0

**Comment by sherrywong1220** [comment]
Yes, this also happened on me. Typing latency disappeared when I disabled `vscode-ruby`.

**Comment by pdf** [comment]
I've had to disable `vscode-ruby` too, worth noting that I have no similar issues with any other language plugins, and I use a few.

**Comment by gurgeous** [comment]
Could be related to the lack of debounce in the linting code, which I think was added recently but not yet released.

**Comment by rhys-vdw** [comment]
Looks like this issue was duplicated in #252 and potentially solved by #264

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
