### ISSUE TITLE
Feature Request: Add ruby-test functionality similar to Sublime Text

### ISSUE THREAD

**Issue by coderberry** [rubyide/vscode-ruby#184]
*We discussed this on Ruby Rogues*

I would love to see a feature where we can run tests by placing the cursor on the test itself then running the test using a shortcut command (CMD-Shift+T).

This plugin exists in Sublime Text (https://github.com/maltize/sublime-text-2-ruby-tests)

Thanks for your hard work!

**Comment by rebornix** [comment]
@cavneb thanks for sharing your ups and downs with this extension. I'll make a roadmap for version 1.0 and make its features comparable to others (like Go, PHP) !

**Comment by petekinnecom** [comment]
In the meantime, this setup might work for you: https://github.com/petekinnecom/test_launcher/blob/master/README.md#visual-studio-code-support

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
