### ISSUE TITLE
Version 1.0 Plan

### ISSUE THREAD

**Issue by rebornix** [rubyide/vscode-ruby#185]
Just had a fun talk with Ruby Rogues and Eric Berry about this extension on Ruby Rogues show. It's good to know that users really love this extension but it's not comparable to other language extensions. We already around 30 contributors and hundreds of issues opened, which means the community is pretty active. So I think it's the right time that we push this extension to 1.0 and provide a good starting experience for both junior and senior Rubist.

* [ ] VSCode Engine/TypeScript/Test
* [ ] Move the whole project to TS 
* [ ] Issues query for 1.0 https://github.com/rubyide/vscode-ruby/milestone/2

**Comment by Youngv** [comment]
When will the 1.0 version be release?

**Comment by rebornix** [comment]
@Youngv it kind of depends on how many weekends I have and how naughty my baby is.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
