### ISSUE TITLE
Bundler is not taken into account for linters

### ISSUE THREAD

**Issue by lloeki** [rubyide/vscode-ruby#188]
### Your environment

- `vscode-ruby` version: 0.13.0
- Ruby version: 2.3
- VS Code version: 1.14.2
- Operating System: macOS 10.13
- Hardware (optional): rMBP

### Expected behavior

Existing `Gemfile`s should be taken into account when running linters (and maybe something else?).

### Actual behavior

Existing `Gemfile`s are ignored when running linters. This does not just makes for distracting warnings when a project lags behind the latest bundler installed but altogether disables them since some newer versions can outright bail out when they don't know anymore about some deprecated config file structure. Being able to handle multiple Gemfile (possibly in nested directories) is important for monorepos and vendoring.

### Steps to reproduce the problem

```bash
mkdir -p repro/{foo,bar}
cd repro
cat > foo/foo.rb <<'EOF'
if 42 == answer
  # there should not be a linter warning above
  # but a Style/YodaCondition is raised
end
EOF
cat > bar/bar.rb <<'EOF'
if 42 == answer
  # there should be a Style/YodaCondition linter warning above
end
EOF
cat > foo/Gemfile <<'EOF'
source 'https://rubygems.org'

gem 'rubocop', '~> 0.46.0'
EOF
cat > bar/Gemfile <<'EOF'
source 'https://rubygems.org'

gem 'rubocop', '~> 0.49.0'
EOF
(cd foo; bundle install)
(cd bar; bundle install)
code .
# now look at foo.rb and bar.rb
# nested variants include foo being inside bar as well as bar being inside foo
```

**Comment by rocifier** [comment]
+1 this is driving me nuts
