### ISSUE TITLE
Changelog entry and Git tag missing vor v0.13.0

### ISSUE THREAD

**Issue by kaiwood** [rubyide/vscode-ruby#189]
Just wanted to quickly report that v0.13.0 shows up in the marketplace, but there is no Changelog entry or a tagged release in the this Github repo. Not a big deal, but it makes it harder to see what changed for people that check everything before they update.

**Comment by rebornix** [comment]
@kaiwood noticed that after the release ;( Now working on refactoring the code to TypeScript, once that's done, I'll have a new release with all of them.
