### ISSUE TITLE
Debug local file offline

### ISSUE THREAD

**Issue by WLLR9505** [rubyide/vscode-ruby#194]
I can't debug a local file offline, why?

**Comment by rebornix** [comment]
@WLLR9505 did you follow our wiki of setting necessary gems and launch.json?

**Comment by WLLR9505** [comment]
Yes, debugger WORKS well, but only with a internet connection, gems and launch.json are OK

I need download something else?

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
