### ISSUE TITLE
Fetching ruby documentation!

### ISSUE THREAD

**Issue by diazgilberto** [rubyide/vscode-ruby#196]
### Your environment

- `vscode-ruby` version: 0.14.0
- Ruby version: 2.4.1
- VS Code version: 1.15.0
- Operating System: OS X
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Probably this is more than a feature request. Does the extension pull ruby documentation?

### Actual behavior
N/A

### Steps to reproduce the problem
N/A

**Comment by rebornix** [comment]
@diazgilberto we don't have that right now :)

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
