### ISSUE TITLE
Emmet isn't recognised in erb

### ISSUE THREAD

**Issue by resting** [rubyide/vscode-ruby#197]
### Your environment

- `vscode-ruby` version: 0.14.0
- Ruby version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16
- VS Code version: 1.15.0
- Operating System: MacOS

### Expected behavior
1. Create a new file
2. Set language mode to `erb`
3. Type `.myclass` or any HTML like `div`, `p` etc
4. Hit `ctrl + space` to list suggestions (if you don't have autosugesstion turned on)
5. Expect to see emmet expanded abbreviations

### Actual behavior
`No suggestions` returned

### Steps to reproduce the problem
see `Expected behavior`

---
IIRC `emmet` used to work seamlessly with `erb`.
Perhaps its due to the change to `emmet` in vscode.
Workaround: set language mode to `HTML`.

**Comment by coisnepe** [comment]
Add this to your settings:

`"emmet.includeLanguages": {"erb": "html"}`

**Comment by resting** [comment]
Works like magic

**Comment by tenzin2017** [comment]
You just need 2 steps to make it work: ( for VS code)
1. "emmet.includeLanguages": {"erb": "html"} as mentioned by @coisnepe 
2.  Install "erb
Craig Maslowsk " extensions..... it helps erb syntax highlighting

**Comment by pvsukale** [comment]
@coisnepe  Thanks!

**Comment by Neo42** [comment]
You guys rocks!

**Comment by Zhao-Andy** [comment]
For anyone looking to add it for `html.erb` files, add this:
```
    "emmet.includeLanguages": {
      "html.erb": "html",
    },
```

**Comment by tenzin2017** [comment]
@Zhao-Andy I tried 
    "emmet.includeLanguages": {
      "html.erb": "html",
    },

but this one doesn't work.
 So I tried 
    "emmet.includeLanguages": {
      "erb": "html",
    },
this works perfectly...... Thanks

**Comment by wingrunr21** [comment]
Would anyone mind writing up either a README entry for this stuff for something for the wiki?

**Comment by prasanthnv** [comment]
"emmet.includeLanguages": {
"erb": "html",
}

**Comment by ariefrizkyr** [comment]
I found that on my mac `.html.erb` are detected as `.html.erb` format instead of `erb`. You can find the format detection by opening your `.html.erb` file and see the bottom right section. Therefore @coisnepe solution doesn't work and @Zhao-Andy works and vice versa.

If you find your format detection as `.html.erb` and you wish to use @coisnepe solution, you may need to add these lines:

```
"files.associations": {
     "*.erb": "erb"
 }
```

Hope this helps.

**Comment by wingrunr21** [comment]
Do you have additional extensions installed that would register an html.erb as a syntax? This extension does’t register that syntax name.

**Comment by aristotelesbr2014** [comment]
This is work for me!
`"emmet.includeLanguages": {"erb": "html"}`
tks! @coisnepe

**Comment by wehdi** [comment]
In addition to "emmet.includeLanguages": {"erb": "html"} you need to install this extension : 
https://marketplace.visualstudio.com/items?itemName=CraigMaslowski.erb

**Comment by flaviofl** [comment]
Not sure why, but for me only worked this way
"emmet.includeLanguages": {"ruby": "html"}

**Comment by frogandcode** [comment]
> I found that on my Mac `.html.erb` are detected as `.html.erb` format instead of erb.

> Not sure why, but for me only worked this way “emmet.includeLanguages”: {“ruby”: “html”}

In case it helps future generations, the solution will depend on what language/format your ERB files are being recognized as using. This comment (above) from @ariefrizkyr is helpful in this regard:

> You can find the format detection by opening your `.html.erb` file and see the bottom right section.

For me (on a Mac), the default was `Ruby`  but changed to `erb` after installing the [Simple Ruby ERB](https://marketplace.visualstudio.com/items?itemName=vortizhe.simple-ruby-erb) extension. So keep any eye on what type of file VS Code thinks you have and configure accordingly.

**Comment by LoretoGH** [comment]
Many thanks, @frogandcode. You just addressed the exact problem I was having. I had edited de config file and added "emmet.includeLanguages": {"erb":"html"}, but it wasn't working. Then I looked at the right lower corner of the editor and I saw that the language association for html.erb was "Plain text", and erb wasn't among the options to choose from. I installed Simple Ruby ERB and changed the language association to erb and now Emmet Abbreviation works perfectly in my html.erb files :)

**Comment by thecodepixi** [comment]
> Not sure why, but for me only worked this way
> "emmet.includeLanguages": {"ruby": "html"}

I tried all of the options presented elsewhere in this thread, and this was what worked for me on Mac, running VS Code v 1.41.0 on a Mac running OS Catalina v 10.15.1

**Comment by edemagbenyo** [comment]
> Add this to your settings:
> 
> `"emmet.includeLanguages": {"erb": "html"}`

Works like a charm

**Comment by sher-s7** [comment]
> Then I looked at the right lower corner of the editor and I saw that the language association for html.erb was "Plain text"

@LoretoGH Thanks for that info, you're a lifesaver

**Comment by Hassanelashram** [comment]
> Works like magic

I don't understand, where exactly do you write "emmet.includeLanguages": ... ?

**Comment by raulrpearson** [comment]
> I don't understand, where exactly do you write "emmet.includeLanguages": ... ?

@Hassanelashram, that goes into [VS Code settings file](https://code.visualstudio.com/docs/getstarted/settings).

**Comment by Hassanelashram** [comment]
@raulrpearson thank you very much for taking the time to answer me, you were right, however i had a headache becasue i was trying it with "emmet.includeLanguages": {"erb": "html"}
but in reality i had to add: "emmet.includeLanguages": {"ruby": "html"}

**Comment by abhicoder0105** [comment]
thank you

**Comment by bazfer** [comment]
So -- adding a file association { "*html.erb": "html" } enables snippets but disables erb highlighting and viceversa. A true Catch-22. Sucks.

**Comment by berxtjkl** [comment]
> For anyone looking to add it for `html.erb` files, add this:
> 
> ```
>     "emmet.includeLanguages": {
>       "html.erb": "html",
>     },
> ```

Thank you so much brother, your answer really helped, :) 
High five.

**Comment by Korak-997** [comment]
@coisnepe 
Thanks a lot your solution works fine. 
Except there is a one little thing you should take care of : 
It is **Trigger Expansion on Tab** 
it need to be checked otherwise when you hit the tab the Emmet will not work fine.
To do that:
 * should go in **Settings** in **Vscode**
* Then write **Emmet** in the search bar
* By coming down a bit you will find this 
  ![Screenshot from 2020-07-29 12-37-46](https://user- 
 images.githubusercontent.com/59537065/88790677-ce9f4500-d198-11ea-88a5- 
  c6325840eacd.png)
* If its checked you are fine if not you need to check it.

**Comment by irmaR** [comment]
> @coisnepe
> Thanks a lot your solution works fine.
> Except there is a one little thing you should take care of :
> It is **Trigger Expansion on Tab**
> it need to be checked otherwise when you hit the tab the Emmet will not work fine.
> To do that:
> 
> * should go in **Settings** in **Vscode**
> * Then write **Emmet** in the search bar
> * By coming down a bit you will find this
>   ![Screenshot from 2020-07-29 12-37-46](https://user-images.githubusercontent.com/59537065/88791024-5a18d600-d199-11ea-9cd0-355c396400e9.png)
> * If its checked you are fine if not you need to check it.

Thanks. Exactly what I was looking for!

**Comment by Mtillmann** [comment]
> Not sure why, but for me only worked this way
> "emmet.includeLanguages": {"ruby": "html"}

that's the one that did it for me, thanks a lot!

**Comment by RafaelBarbosa09** [comment]
it worked for me:

  "emmet.includeLanguages": {
    "erb": "html",
    "ruby": "html"
  }

**Comment by sandyleo26** [comment]
I'm using the same setting but autocompletion wouldn't work in the `erb` file until I click a normal `html` file and then select the `erb` file. Not sure if it's lazy loading issue or something else but it's a bit annoying that I need to do this dance every time I open a new project.

**Comment by guar47** [comment]
For me, the only way to make it works was:
Add an association between `.erb` files and `erb.html`:
```
```

**Comment by o-t-w** [comment]
None of these worked for me

**Comment by ben-brunner** [comment]
> 

Tried everything, including thorough uninstall of VS Code, that's actually the only thing that worked in order to get Emmett to work in erb files...

**Comment by ben-brunner** [comment]
> I'm using the same setting but autocompletion wouldn't work in the `erb` file until I click a normal `html` file and then select the `erb` file. Not sure if it's lazy loading issue or something else but it's a bit annoying that I need to do this dance every time I open a new project.


Tried everything, including thorough uninstall of VS Code, that's actually the only thing that worked in order to get Emmett to work in erb files...

**Comment by guanting112** [comment]
![test](https://imgur.com/KU0n4JU.gif)

**Comment by pablojp** [comment]
> For me, the only way to make it works was: Add an association between `.erb` files and `erb.html`:
> 
> ```
>   "files.associations": {
>     "*.erb": "html.erb"
>   }
> ```
> 
> And then add emmet setting:
> 
> ```
>   "emmet.includeLanguages": {
>     "html.erb": "html",
>   },
> ```

this work for me.. Thanks!!!
