### ISSUE TITLE
go to definition not working after upgrading to 0.14.0

### ISSUE THREAD

**Issue by rachsmithcodes** [rubyide/vscode-ruby#198]
### Your environment

- `vscode-ruby` version: 0.14.0
- Ruby version: 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
- VS Code version: 1.15.0
- Operating System: macOS Sierra 10.12.6
- Hardware (optional): macbook pro

### Problem
Go to definition/peek definition stopped being an option in .rb files. Right-clicking, using command palette doesn't have go to definition when vars are selected and when I command-click methods/vars that it should work on nothing happens.  (in v0.14.0)

### Steps to reproduce the problem
All I changed in my setup is upgrading to 0.14.0. I deleted and installed 0.13.0 again from a .vsix file and go to definition was working again. 

Thankyou!!

**Comment by perlun** [comment]
I am seeing similar issues here, with 1.15.x.

**Comment by borenho** [comment]
I also got this issue. Fixed it by installing the `rails` extension on vscode. This might help if you use Rails too.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by bragamat** [comment]
> I also got this issue. Fixed it by installing the `rails` extension on vscode. This might help if you use Rails too.

Thank you very much! That worked for me
