### ISSUE TITLE
Autocompletion from rcodetools doesn't work

### ISSUE THREAD

**Issue by lumean** [rubyide/vscode-ruby#201]
### Your environment

- `vscode-ruby` version:  0.14
- Ruby version:  2.3.3p222
- VS Code version:  1.15.1
- Operating System: Win10 Home

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Autocompletion works and I get the suggestions for an array:
```
#each
#each_index
#empty?
#eql?
```

### Actual behavior
Autocompletion doesn't work
![image](https://user-images.githubusercontent.com/9656676/29525930-7f46ac66-8694-11e7-8285-99bdc9d978ec.png)

I can see some permission errors in the developer tools
[vscode.txt](https://github.com/rubyide/vscode-ruby/files/1239226/vscode.txt)

### Steps to reproduce the problem
press Ctrl.space

**Comment by castwide** [comment]
The rcodetools gem hasn't been updated in over 8 years. I doubt it's maintained or supported anymore.

I published a separate VS Code extension that might suit your needs: [Ruby Solargraph](https://marketplace.visualstudio.com/items?itemName=castwide.solargraph)

It works well as an addition to the Ruby extension with no overlapping functionality outside of replacing the rcodetools version of code completion.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
