### ISSUE TITLE
Go to definition not working in 0.15.0 for VS Code - Insiders

### ISSUE THREAD

**Issue by sergeant-q** [rubyide/vscode-ruby#209]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin16]
- VS Code version: 1.17.0-insider (1.17.0-insider)
- Operating System: 10.12.6 (macOS Sierra)
- Hardware (optional): MBP

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Right-clicking or a class or method and selecting go to definition should direct me to the file where the definition exists. 

CMD+ selecting a class, module or method should highlight and take you to the definition. 

### Actual behavior
After right-clicking and selecting go to definition, the definition is never found. You get a response saying "no definition found for... "

Hovering over a class, module or method and pressing down on CMD does not highlight the string and you are unable to select it trigger the go to definition. 

### Steps to reproduce the problem
Open any ruby file (*.rb) and find a method, module or class that you know is defined in another file and attempt to either right-click or CMD+click it and observe the **actual behavior mentioned above**

**Comment by rs-longsheng** [comment]
Any feedback on this issue?

**Comment by vcardillo** [comment]
I think you mistyped:

```
$ gem install ruby-debug-basex19
ERROR:  Could not find a valid gem 'ruby-debug-basex19' (>= 0) in any repository
ERROR:  Possible alternatives: ruby-debug-base19, ruby-debug-base19x, ruby-debug-base193, ruby-debug-base, ruby-debug-ide19
```

**Comment by vcardillo** [comment]
This is broken for me as well.

**Comment by vcardillo** [comment]
This has broken for me as well.

**Comment by sergeant-q** [comment]
Any updates on this? I am on VS code version **1.19.3** and on `vscode-ruby` version **0.16.0** and go to definition still does not work!

**Comment by castwide** [comment]
https://github.com/rubyide/vscode-ruby/pull/248 is a step toward resolving this issue. The next version of the Solargraph extension will include support for going to a definition in any file in the workspace.

**Comment by jxdx** [comment]
Doesn't work in 1.21.1 for me
Or the latest insiders build

**Comment by iamsuleyman** [comment]
It doesn't work for me too!

**Comment by castwide** [comment]
Check which option you're using for `ruby.intellisense`. If it's `solargraph`, make sure you have the solargraph gem installed. More information here: https://github.com/castwide/vscode-solargraph

If you use `rubyLocate`, you might need to configure the include and exclude settings. See this extension's README for configuration.

A related solargraph bug due to character encoding issues is being tracked at https://github.com/castwide/vscode-solargraph/issues/32.

**Comment by iamsuleyman** [comment]
@castwide I use solargraph, I'll wait fixing of related bug that you provided. Thank you

**Comment by borenho** [comment]
I fixed this by installing the `rails` vscode extension, which has support for `Go to definition`

**Comment by castwide** [comment]
Gem version 0.17.4 is published. It resolves the character encoding bug that caused "go to definition" to stop working in some workspaces.

**Comment by vcardillo** [comment]
It still shows `0.17.0` in the Extensions Marketplace.

**Comment by iamsuleyman** [comment]
I updated to latest ``solargraph`` versions but "go to definition" doesn't work
