### ISSUE TITLE
[Feature Request] `def ... end` highlighting

### ISSUE THREAD

**Issue by ciaoben** [rubyide/vscode-ruby#21]
It would be great to have brackets ( and `def .. end`) highlighting.

**Comment by lextm** [comment]
Can you check if #23 meets your need?

**Comment by rebornix** [comment]
@ciaoben 0.4.0 is out with syntax highlighting support :smile:

**Comment by HookyQR** [comment]
@ciaoben version 0.5.0 released with block start/end highlighting. It ignores one liners, so `def nothing; end` won't highlight anything. Something like this:
```ruby
def bad_format; puts "nasty"
end
```
will mess it up as well, but if you're doing that then there's not much that can help you 😉 !

A block opener is considered any line starting with:
`begin|class|def|for|if|module|unless|until|case|while` and doesn't have a `{` or `;` on the line, or it has `do` on the line with no `;` after it.

Also, this extension now includes linting support. Have a look at the readme for how to enable it (or them - there are several options)
