### ISSUE TITLE
String Interpolation Should Automatically Add Closing Bracket

### ISSUE THREAD

**Issue by ecbrodie** [rubyide/vscode-ruby#210]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.4.1
- VS Code version: 1.16.1
- Operating System: MacOS 10.12.6

### Expected behavior

When typing a Ruby string with String interpolation, for example a `puts` statement, the closing bracket of the string interpolation should automatically appear. For example, when I type this:

```ruby
puts "test_str = #{
```

Then the closing bracket should immediately be filled in:

```ruby
puts "test_str = #{}
```

### Actual behavior

The closing bracket does not get filled in automatically, which is very annoying.

### Steps to reproduce the problem

Nothing else to really mention regarding steps to reproduce. I am personally curious if this is a bug in the VSCode IDE itself or specific to this extension.

**Comment by jeffpereira** [comment]
I in fact think that the feature should go one step further and think that anytime you type in and hashtag inside of double quotes that are not escaped the editor should add both curly braces.

**Comment by goronfreeman** [comment]
I opened this same issue in #200. Want to close this one, so we don't have duplicates?

**Comment by ecbrodie** [comment]
I don't mind closing to remove duplicates, but I want to see if @jeffpereira 's concern will still be address.

**Comment by goronfreeman** [comment]
His expected behavior is what I have in the "Expected behavior" section of my open issue.

**Comment by aliariff** [comment]
Hi, I created a solution specifically for this issue. Feel free to try it out.

https://marketplace.visualstudio.com/items?itemName=aliariff.auto-add-brackets
