### ISSUE TITLE
Intellisense cross files

### ISSUE THREAD

**Issue by diazgilberto** [rubyide/vscode-ruby#212]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.4.2
- VS Code version: 1.17.0 (1.17.0)
- Operating System: El Capitan
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
- Intellisense for the class methods cross files

### Actual behavior
- Intellisense is not working for methods cross files

### Steps to reproduce the problem
- Create a file with a class and methods
- Create a second file and require_relative the first file
- Try to create an instance of the class and use methods of the class.
```
instance = Class.new
instance.__ # here should prompt me with the methods of the class
```

**Comment by damienlethiec** [comment]
Same for me (as well as GoToDefinition cross file)

**Comment by castwide** [comment]
https://github.com/rubyide/vscode-ruby/pull/248 should resolve this issue.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
