### ISSUE TITLE
Use solargraph for code autocomplete

### ISSUE THREAD

**Issue by numbcoder** [rubyide/vscode-ruby#218]
The rcodetools’ development is not active, solargraph looks better
 
https://github.com/castwide/solargraph

**Comment by doudou** [comment]
Given that solargraph focusses on code completion, and develops its own VSCode extension, I would suggest to remove completion support completely from vscode-ruby, and simply depend on the solargraph extension. Even better, approach the solargraph developer(s) to get all the gems and extensions under the same org (rubyide would sound like a good choice).

**Comment by castwide** [comment]
Adding a dependency is definitely the easiest way to integrate Solargraph. I created a [fork](https://github.com/castwide/vscode-ruby) and a [pull request](https://github.com/rubyide/vscode-ruby/pull/248) for it.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
