### ISSUE TITLE
Enhancement Request (not a bug issue) : Match this feature set please

### ISSUE THREAD

**Issue by mistergibson** [rubyide/vscode-ruby#221]
Your auto-indent is nice, but I'm currently using NetBeans with this Ruby support plug-in:

Found Here: http://plugins.netbeans.org/plugin/38549

If you really want to provide a compelling reason to leave NetBeans and switch to Visual Studio Code, you're going to have to match the feature set of that plug-in. It is phenominal:

- auto-indent to the *proper* tab mark on a single tab stroke.
- auto-closures for if/else/end, do/end, class/end, module/end, {}, etc.
- auto-highlights closure pairs for easy matching (saved my ass numerous times).
- underlines variables not used.

... and much more.

So, I invite you to match this plug-in feature for feature. If VSC had this ability to help me with my coding I'd switch in a heart-beat. As things stand, I just don't think its ready yet - still too young. Go ahead and install NetBeans 8.2 and that plug-in and try it out - you'll see why I want the features ported to VSC.

Thank you,

G. Gibson

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
