### ISSUE TITLE
`ruby-lint` is a mess with Rails. It still in use by the community?

### ISSUE THREAD

**Issue by johnunclesam** [rubyide/vscode-ruby#225]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
- VS Code version: 1.18.1 and 1.19.0-insider 
- Operating System: Windows 10 latest

### Expected behavior

`ruby-lint` OK with Rails.

### Actual behavior

`ruby-lint` is a mess with Rails.

![image](https://user-images.githubusercontent.com/21275217/33344261-ab769110-d488-11e7-89c2-69de824bc0a5.png)

I see `ruby-lint` is old and unmanteined. Is it still in use by the community? We really need it?

**Comment by goronfreeman** [comment]
I've never heard of anyone using `ruby-lint`. The de facto Ruby linter is [rubocop](https://github.com/bbatsov/rubocop).

**Comment by johnunclesam** [comment]
In this package Readme:

![image](https://user-images.githubusercontent.com/21275217/33896990-929de6de-df64-11e7-8139-a2dd0e40729e.png)

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by richjdsmith** [comment]
Any chance we could open this and use this thread as a discussion about dropping ruby-lint from the recommended available Linter Hooks?

**Comment by wingrunr21** [comment]
Nope because I'm already planning on dropping support: https://github.com/rubyide/vscode-ruby/issues/317#issue-311300214
