### ISSUE TITLE
Support for Rails colorization?

### ISSUE THREAD

**Issue by oyeanuj** [rubyide/vscode-ruby#228]
### Your environment

- `vscode-ruby` version: 0.15.0 
- Ruby version:  2.4.0.
- VS Code version: 1.18.1
- Operating System: MacOS
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

Rails code would be syntax highlighted correctly.

### Actual behavior

Rails methods and code are not highlighted.

### Proposal

@rebornix Thank you for creating this! I was wondering if there was plan to syntax highlight/colorize Rails specific code as well? That's one big thing missing in VSCode and I wasn't sure if this was extension-land request or in the main vscode repo, but thought I'd start here.

Thoughts?

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by oyeanuj** [comment]
@wingrunr21 This is still an issue, is this something on the radar specifically?
