### ISSUE TITLE
[Proposal] implement a TaskProvider for running tests

### ISSUE THREAD

**Issue by doudou** [rubyide/vscode-ruby#230]
Would there be an interest in implementing a taskprovider that would allow starting individual tests (files and/or single tests) directly from the "run test task" menu ? I would be doing the work.

I would initially implement for minitest (since it's what I'm using), but keeping in mind the possibility to add more.

**Comment by goronfreeman** [comment]
[Here's](https://github.com/noku/rails-run-spec-vscode) a nice test runner extension I use for RSpec. Might help with developing this.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by connorshea** [comment]
I created a Ruby Test Explorer that seems relevant to this issue: https://marketplace.visualstudio.com/items?itemName=connorshea.vscode-ruby-test-adapter

**Comment by minkir014** [comment]
Or you may create that task yourself. It's not hard.
