### ISSUE TITLE
[Debugging] Attach to subprocesses automatically

### ISSUE THREAD

**Issue by jwhitcraft** [rubyide/vscode-ruby#235]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.3.x
- VS Code version: 1.19.0
- Operating System: macOS High Serria
- Hardware (optional): MacBook Pro Mid 215

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
When I launch a debugging instance, the debugger should auto attached to any child processes that are spawned.

### Actual behavior
You have attach to the first one, and then wait for the second one to start up, and then attach to it, and then if there is any more you have to repeat each step.

### Steps to reproduce the problem
Create a Sinatra based app that uses rack to run, and try and debug it. 

### Additional Notes
Rubymine does this already when you have `Attach to subprocesses automatically when debugging` enabled.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
