### ISSUE TITLE
Gem包里的方法无法go to definition

### ISSUE THREAD

**Issue by zouchao** [rubyide/vscode-ruby#236]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version:  ruby 2.3.1p112
- VS Code version: 1.19.1, 0759f77bb8d86658bc935a10a64f6182c5a1eeba, x64
- Operating System: macOS 10.13.2 (17C88)
- Rbenv version: 1.0.0-21-g9fdce5d
- Bundler version: 1.16.0
- Gem version: 2.7.4
- Hardware (optional): 

```
debase (0.2.2.beta14, 0.2.1)
debase-ruby_core_source (0.10.0)
ruby-debug-ide (0.6.0)
```

### Expected behavior
预期引入的gem包的方法也可以跳到定义的位置，方便阅读源码

### Actual behavior
无法跳转

### Steps to reproduce the problem
本地装了rbenv，gem是用bundler管理，路径大致如下：
```
/Users/xxxxx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rails-4.2.5
```

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
