### ISSUE TITLE
Wrong indentation for case...when

### ISSUE THREAD

**Issue by lucasqueiroz** [rubyide/vscode-ruby#237]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.3.3
- VS Code version: 1.19.1
- Operating System: Ubuntu 17.10
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
`when` should be indented at the same level as `case`

### Actual behavior
`when` is indented one level before `case`

### Screenshots

![rb-vscode](https://user-images.githubusercontent.com/29466590/34470555-1d74c622-ef1b-11e7-86ab-efa1d789132c.png)

**Comment by wingrunr21** [comment]
This is fixed by #231

**Comment by rebornix** [comment]
Already fixed in 0.16.0.
