### ISSUE TITLE
rubocop issues don't disappear after fixing

### ISSUE THREAD

**Issue by PascalTurbo** [rubyide/vscode-ruby#238]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin17]
- VS Code version: 1.19.1
- Operating System: macOS High Sierra 10.13.2
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

After fixing a rubocop issue the issue shouldn't appear in vscode

### Actual behavior

After fixing a rubocop issue the issue will appear unless restarting vscode

### Steps to reproduce the problem

Create a ruby file and produce an rubocop issue. Save the file, exit vscode, start vscode again, fix the issue. Now the issue should disappear.

I've been watching this problem for month on different devices with different macOS Versions. Even on a brand new device installed from scratch.

**Comment by gurgeous** [comment]
I wonder if we are supposed to manually remove diagnostics when files are closed. I think eslint is doing something similar here - https://github.com/Microsoft/vscode-eslint/blob/master/server/src/eslintServer.ts#L617

**Comment by greveritt** [comment]
It sounds like I'm having the same problem.

My environment
--------------

-  vscode-ruby version: 0.18.0
-  Ruby version (installed with rbenv): ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
-  VS Code version: 1.25.1
-  Operating System: macOS High Sierra 10.13.6
-  Hardware (optional): MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by andrewmcodes** [comment]
Is this still happening on 0.20.0 for you? I just removed some rubocop errors and the issues disappeared.

**Comment by wingrunr21** [comment]
This should be working correctly on `v0.22.2` and up with language server based linting
