### ISSUE TITLE
Format Document working, editor.formatOnSave=true broken

### ISSUE THREAD

**Issue by gurgeous** [rubyide/vscode-ruby#240]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.5.0
- VS Code version: 1.19.1
- OS Version: Mac OS 10.12.6

### Description

I am having some trouble with `editor.formatOnSave=true` when using the Ruby extension. It isn't formatting on save. This is strange, because a manual `Format Document` works fine. How is that possible?

I modified the extension locally and added some debug output to this file:

https://github.com/rubyide/vscode-ruby/blob/master/src/format/rubyFormat.ts

I verified that the correct edits were being returned from `provideDocumentFormattingEdits`. This makes sense since a manual `Format Document` works fine. What am I missing? Could this be a vscode bug? Not sure how to debug further.

**Comment by cplotter** [comment]
Running into the same issue.

**Comment by t4deu** [comment]
So do I!

**Comment by gurgeous** [comment]
Another alternative for formatting is rufo, which is quite snappy:

https://github.com/ruby-formatter/rufo
https://marketplace.visualstudio.com/items?itemName=siliconsenthil.rufo-vscode

**Comment by gurgeous** [comment]
The vscode issue has some more information:

https://github.com/Microsoft/vscode/issues/41194

**Comment by gurgeous** [comment]
Let's close this since the vscode fix should be right around the corner.
