### ISSUE TITLE
vscode-ruby does not auto-detect Ruby syntax from shebang

### ISSUE THREAD

**Issue by mdub** [rubyide/vscode-ruby#245]
### Your environment

- `vscode-ruby` version: 0.15.0
- Ruby version: 2.4.2
- VS Code version: 1.19.2
- Operating System: OS X

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

When opening a file with first line `#! /usr/bin/env ruby`, VS Code should automatically select "ruby" syntax (even if the file does not have an `.rb` extension).

### Actual behavior

VS Code assumes the file is "Plain Text".

### Steps to reproduce the problem

Create a file called "blah" with contents:

```ruby
#! /usr/bin/env ruby
puts "Hello"
```

and open this in VS Code.

**Comment by wingrunr21** [comment]
This is resolved by #246

**Comment by rebornix** [comment]
Already fixed in 0.16.0.
