### ISSUE TITLE
.arb file extension support

### ISSUE THREAD

**Issue by dkniffin** [rubyide/vscode-ruby#256]
[Arbre](https://github.com/activeadmin/arbre) is a ruby gem that allows you to build view components using plain ruby (instead of embedded ruby, as in erb). In Arbre, you can build partials and views just like with ERB, but the file extension is different (`.arb` instead of `.erb`).

I think supporting this file extension should be fairly straightforward. The code inside the file is just ruby (no fancy syntax), so it should be as easy as recognizing the file extension, and using the right language for it.

In the meantime, an easy workaround for anyone interested is to add this to your settings config:

```js
  "files.associations": {
    "*.arb": "ruby"
  }
```

**Comment by wingrunr21** [comment]
This change should be just adding it to the [`extensions` array](https://github.com/rubyide/vscode-ruby/blob/master/package.json#L268) in `package.json`. Feel free to open a PR!.

**Comment by dkniffin** [comment]
Will do! Thanks for pointing me to where the change was. I'm not too familiar with how vscode extensions work yet.
