### ISSUE TITLE
Word match includes ":"

### ISSUE THREAD

**Issue by atombender** [rubyide/vscode-ruby#257]
### Your environment

- `vscode-ruby` version: 0.16.0
- Ruby version: 2.3.3p222
- VS Code version: 1.19.3
- Operating System: macOS 10.13.2
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

`:` should never be part of word matching rules.

### Actual behavior

`:` is included when matching words (e.g. cmd-D). This [used to be an issue in VSCode itself](https://github.com/Microsoft/vscode/issues/18241), but was fixed.

### Steps to reproduce the problem

Given the following snippet:

```ruby
Foo::Bar.baz(:fnord)
```

Position caret on `Bar` and hit cmd-D. This will highlight `:Bar` instead of just `Bar`:

<img width="322" alt="screen shot 2018-01-30 at 14 26 58" src="https://user-images.githubusercontent.com/50314/35586733-b6ef2846-05c9-11e8-8931-7b2b7bc98e0c.png">

Postion caret on `fnord` and hit Cmd-D. This will hightlight `:fnord` instead of `fnord`.

<img width="322" alt="screen shot 2018-01-30 at 14 27 12" src="https://user-images.githubusercontent.com/50314/35586732-b6e13b32-05c9-11e8-8b4f-ab25e737b7a5.png">

Both are surprising and wrong. A symbol is _not_ a word. The `:` is not part of it, in the same way that quotes are not part of `"a string"` or a minus character is not part of `-3`. For example, this hits the `cmd-D` behaviour where you might have:

```ruby
def delete(object)
  put_in_trash if object.kind == :foo || mode == 'foo'
end
```

Place the caret on `foo` and hit cmd-D a few times, and it will of course only match the symbol. Similarly, if you used cmd-D with the intention to copy the name, you'd get the colon included. Neither is useful.

Some might argue that the colon is part of the term, but this just isn't useful. Of course, the other use case which hits qualified identifiers (`Foo::Bar`) is indefensible.

**Comment by davev** [comment]
+1 in ERB and HAML files, the word separator works correctly, but in Ruby files, the preceding colon is included in word selection.

**Comment by wingrunr21** [comment]
Closing in favor of #282
