### ISSUE TITLE
Incorrect boolean flag to turn on rubocop

### ISSUE THREAD

**Issue by thawatchai** [rubyide/vscode-ruby#261]
### Your environment

- `vscode-ruby` version: 0.16.0
- Ruby version: 2.5.0
- VS Code version: 1.20.0
- Operating System: macOS 10.13.3
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
This should turn on the linter and rails support.
```
    "ruby.lint": {
        "rubocop": {
            "lint": true,
            "rails": true
        }
    }
```

### Actual behavior
This turns on the linter and rails support.
```
    "ruby.lint": {
        "rubocop": {
            "lint": false,
            "rails": false
        }
    }
```

### Steps to reproduce the problem
Put the config in my user settings and change from `true` to `false`.

**Comment by thawatchai** [comment]
This is probably related to #229.

**Comment by rpellerin** [comment]
Any updates on this?

**Comment by andrewmcodes** [comment]
Is this still an issue with 0.20.0?

**Comment by happysean-lavabit-com** [comment]
@andrewmcodes yes this is still an issue

- vscode-ruby 0.21.0
-ruby version: 2.5.3p105
-vs code version 1.30.0
-operating system: windows 10 enterprise 1709 build 16299.846

**Comment by wingrunr21** [comment]
This should be working correctly on `v0.22.2` and up with language server based linting
