### ISSUE TITLE
Block dectection faulty on single-line conditionals

### ISSUE THREAD

**Issue by neovatar** [rubyide/vscode-ruby#265]
### Your environment

- `vscode-ruby` version: 0.16.0
- Ruby version: 2.4.1p111
- VS Code version: 1.20.0
- Operating System: Linux

### Expected behavior
Block marking on last `end` matches single-line `if` instead of top level `def` (working until v0.15.0):

![image](https://user-images.githubusercontent.com/550533/36090444-acc558ba-0fe0-11e8-9902-696bcb4cde70.png)

### Actual behavior

Block marking on last `end` matches single-line `if` instead of top level `def`:

![image](https://user-images.githubusercontent.com/550533/36090008-e012eff4-0fde-11e8-8fa4-5b410eb84f49.png)

### Steps to reproduce the problem
- install vscode-ruby v0.16.0
- Use the following code

```
def foo(a)
  raise 'Error' if a.nil?
  puts "#{a} is foo"
end
```

- Go to last line and observe block marking for `end` statement

**Comment by wingrunr21** [comment]
Closing in favor of #282
