### ISSUE TITLE
Ruby 99% ++ CPU Usage on Mac

### ISSUE THREAD

**Issue by konzaho** [rubyide/vscode-ruby#267]
### Your environment

- `vscode-ruby` version: 0.6.0
- Ruby version: ruby 2.5.0p0
- VS Code version: 1.20.0
- Operating System: MacOs 10.13.3
- Hardware (optional): MacBook Pro 2016 15" TouchBar

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

I run some simple ruby code using Visual Studio Code and i see something odd. The ruby process is taking 99%++ CPU usage.

### Expected behavior
I think it doesn't need that much of power to run a code i provide.

### Actual behavior
[https://imgur.com/a/SD4Ma](https://imgur.com/a/SD4Ma)

As you can see, it taking 99% CPU usage just for a single simple code. It will still running until i force quit the service and sometimes there is not just one process. I run the code within the VS Code terminal, but it seems i don't have this problem when running the code in regular terminal.

### Steps to reproduce the problem
I create a simple short code in VS Code and run it within the VS Code terminal.
this is the code:
`something = 3`
`something.to_s` 
`print something`

this is the log of the ruby process in Activity Monitor:
`cwd`
`/`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/bin/ruby`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/libruby.2.5.0.dylib`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/enc/encdb.bundle`
`txt`
`/usr/local/Cellar/gmp/6.1.2_1/lib/libgmp.10.dylib`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/enc/trans/transdb.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/stringio.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/etc.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/pathname.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/openssl.bundle`
`txt`
`/usr/local/Cellar/openssl@1.1/1.1.0g_1/lib/libssl.1.1.dylib`
`txt`
`/usr/local/Cellar/openssl@1.1/1.1.0g_1/lib/libcrypto.1.1.dylib`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/digest.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/io/nonblock.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/zlib.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/digest/sha1.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/socket.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/io/wait.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/enc/windows_31j.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/json/ext/parser.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/json/ext/generator.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/readline.bundle`
`txt`
`/usr/local/Cellar/readline/7.0.3_1/lib/libreadline.7.0.dylib`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/strscan.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/date_core.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/cgi/escape.bundle`
`txt`
`/Users/konzaho/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/x86_64-darwin17/digest/md5.bundle`
`txt`
`/usr/lib/dyld`
`txt`
`/private/var/db/dyld/dyld_shared_cache_x86_64h`
`0`
`->0x369452a54d0e4c31`
`1`
`->0x369452a54d0e4911`
`2`
`->0x369452a54d0e38a9`
`3`
`->0x369452a54b81a3e9`
`4`
`->0x369452a54b81b769`
`5`
`->0x369452a54b81a569`
`6`
`->0x369452a54d0e38a9`
`7`
`->0x369452a54b81bb29`
`8`
`[ctl com.apple.netsrc id 9 unit 27]`
`9`
`->0x369452a54d0e5271`
`10`
`localhost:59277`
`11`
`localhost:59277`
`12`
`->0x369452a54b81a0e9`
`13`
`->0x369452a54b81a4a9`
`14`
`localhost:59277->localhost:59285`
`15`
`localhost:59277->localhost:59286`
`16`
`localhost:59277->localhost:59287`
`24`
`->0x369452a5536d6789`
`25`
`/Applications/Visual Studio Code.app/Contents/Resources/electron.asar`
`27`
`/Users/konzaho/Devs/ruby/bookTwo.rb`

The log provided is log when i run the code above. Is it normal for Ruby to taking this much of CPU power just to run a simple code? Yes, of course i can just instantly force quit the process, but it kind of annoying to do it every time you close the editor and it heated up my machine too.

**Comment by bert-mccutchen** [comment]
**I found the issue, it's Solargraph.**

You can fix it by adding `"ruby.codeCompletion": "none"` to your VS Code user settings and then running `gem uninstall solargraph`. You may need to shut down VS Code and/or restart your computer to stop any running ruby processes. This will turn off code completion, so I hope you don't use it.

**Comment by suan** [comment]
The Ruby extension is causing so much lag when typing that it's unusable for me unfortunately :-/  I've tried removing the solargraph gem and setting codeCompletion to "none" and unfortunately it's still slow - the only thing that seems to do the trick for me is to disable the Ruby extension altogether

**Comment by wingrunr21** [comment]
We'd need to configs from people in order to figure out what may be going on. How you run ruby, how your linters are installed, etc can all affect speed.

Are you all running the latest version with the linting debounced?

**Comment by mariohd** [comment]
this problem was happening to me also, solved uninstalling the latest version of solargraph (0.17.4). Now i'm using solargraph (0.17.3) and it's working fine. Although VS Code still warns me to update the gem, i just ignore and everything is fine.

**Comment by wingrunr21** [comment]
Closing as this appears to have been a solargraph issue
