### ISSUE TITLE
Sorry, but there is no formatter for 'ruby'-files installed.

### ISSUE THREAD

**Issue by doudou** [rubyide/vscode-ruby#269]
### Your environment

- `vscode-ruby` version: master
- Ruby version: 2.3.0
- VS Code version: 1.20.1
- Operating System: Ubuntu 16.04

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

I can use rubocop to do formatting

### Actual behavior

I get the `sorry, but there is no formatter for 'ruby'-files installed.

### Steps to reproduce the problem

On my machine, it is systematic. I've run under a debugger, and the line with `registerDocumentFormattingEditProvider` is executed.

**Comment by universam1** [comment]
same here

**Comment by bhoeting** [comment]
This is also happening to me.

**Comment by estevaoam** [comment]
Same here. :/

**Comment by wingrunr21** [comment]
This will be addressed via #317. Please use that to track progress against it.

**Comment by dsomel21** [comment]
Did y'all figure this out?

**Comment by jcarlos** [comment]
Same happening here with me, however when I go to View > Command Palette and choose format it formats just fine. 

Seems to be related just with my vim shortcut ```=G``` to format the whole file or if I select just a few lines and try to format it.

Using ALT+SHIFT+F for now to format the whole document works ok

**Comment by andrewheekin** [comment]
seeing the same issue, even with format from view > command palette @jcarlos

**Comment by wingrunr21** [comment]
This will be addressed via #317. Until then, if someone else debugs and submits a PR for a fix I'll be happy to take a look/merge.

**Comment by jacquescrocker** [comment]
Anyone have a workaround that they use? 

This is sort of a key feature on an ide and this pops up on the google search result when looking for it. 

Maybe someone has something working that we can use?

**Comment by vaidhyanathan93** [comment]
Same thing to here . If anyone fixes the issues/Found how to rectify this please update

**Comment by zackchandler** [comment]
Same here!

**Comment by marinhero** [comment]
Thanks for the insight @kaiwood. I ended up remapping `==` to `Reindent lines` and that's more than enough for me right now. Hope you get the ERB plugin out soon!

**Comment by bjeanes** [comment]
Remapping == doesn't seem to be working. Can somebody paste their remapping configuration to make sure I have it right?

``` json
    "vim.normalModeKeyBindingsNonRecursive": [{
            "before": ["j"],
            "after": ["g", "j"]
        },
        {
            "before": ["k"],
            "after": ["g", "k"]
        },
        {
            "before": ["=", "="],
            "commands": ["editor.action.reindentselectedlines"]
        }
    ],
```

I've tried recursive and non-recursive (though it shouldn't make a difference for `"commands"` maps) as well as `reindentlines` and `reindentselectedlines`. My other mappings work so I know that remappings generally are taking effect, however I still get the selection formatter error when hitting `==`.

**Comment by locofocos** [comment]
Note to random Googlers (correct me if I'm wrong): you can follow this to get ruby formatting working: https://github.com/rubyide/vscode-ruby#formatting

If I understand correctly, #317 is targeted towards making some improvements to how it's implemented.

**Comment by wingrunr21** [comment]
#405 is the implementation for most of that ticket

**Comment by ignaciosiri** [comment]
Adding this setting in `settings.js` fixes that!

    "files.associations": {
            "*.erb": "erb"
        }

**Comment by rehanmunir** [comment]
rvm use (version)@global     
gem install htmlbeautifier
