### ISSUE TITLE
Indentation

### ISSUE THREAD

**Issue by remcohh** [rubyide/vscode-ruby#27]
Would it be possible to add indentation support?
That would be really great!

**Comment by HookyQR** [comment]
Formatting (including auto indent/de-indent) is my next target after replacing the debugger.

**Comment by HookyQR** [comment]
@remcohh 
I'm on a flow, so I'll have a bash at this tonight.

Specifically I'll be indenting (and potentially auto 'end' inserting) for `def ...`, `while`, `begin` etc.

Anything else you're particularly keen on?

**Comment by remcohh** [comment]
@HookyQR for starters the indenting stuff would be great, it would make vscode so much more usefull for ruby developers!

**Comment by HookyQR** [comment]
PR for indentation is done, un-indenting needs to be done manually because the API only un-tabs the _next_ line which would leave the `end` keyword hanging.

**Comment by remcohh** [comment]
@HookyQR Looking forward to test it, about the un-indenting:
Is it nescessary to do that?
The way it works in rubymine: 
I type "def foo" <enter>
after that it inserts two new lines at onces: the first one empty and indented, the second one contains "end" and is not indented. This would be ideal i think

**Comment by HookyQR** [comment]
There are two ways to provide this, the first is with snippets, the second is with on-type-formatting. Snippet provision is on by default, and on-type-formatting is off by default. 

I'll put snippets in today, and maybe have a look at on-type-formatting. I'm not sure how the two will interact if they're both on.

Will keep you informed. Personally, I think on-type-formatting is a better solution, but time will tell.

**Comment by HookyQR** [comment]
@remcohh check out the latest version (0.5.*) and let me know what you think. It uses the snippets as well as auto indentation if you don't use the snippets.

**Comment by remcohh** [comment]
I didn;t succeed building it from github repo, I guess i need to use gulp?
Could you give me some pointers?


Op vr 20 mei 2016 om 23:52 schreef HookyQR <notifications@github.com>:

**Comment by HookyQR** [comment]
@remcohh: You should install it from within VS Code. Hit **F1** and type `ext install ruby`.

**Comment by remcohh** [comment]
@HookyQR I didn't expect you to push it allready to the extensions repo that fast :)
I checked it and it works as expected! One small detail: you mentioned that snippets is on by default but for me that wasn't the case so I had to enable it. Thanks a lot and good luck with the upcoming features!
