### ISSUE TITLE
command 'extension.formatRuby' not found

### ISSUE THREAD

**Issue by escobera** [rubyide/vscode-ruby#271]
### Your environment

- `vscode-ruby` version: 0.16.0
- Ruby version: 2.1.5
- VS Code version: 1.20.1
- Operating System: Linux Mint 18.3

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
When I press ctrl + shit + i on a ruby file it formats it (based on rubocop)

### Actual behavior
I get a message
WARN command 'extension.formatRuby' not found

### Steps to reproduce the problem
gem install rubocop
code .
install the extension
click reload reload
open *.rb file
ctrl+shif+i

**Comment by escobera** [comment]
Is there any way I can debug this behavior? 

cc @rebornix

**Comment by rebornix** [comment]
@escobera did you bind ctrl+shift+i to `extension.formatRuby ` yourself?, we don't have this command at this moment.

**Comment by escobera** [comment]
That is the default "Format Document" keybinding.

![selection_012](https://user-images.githubusercontent.com/9344/36950856-0ac2b3fe-1fdb-11e8-80be-94f7479d45ac.png)

Any more info you need I'm happy to provide.

I'm using RVM on Linux Mint 18.3.

**Comment by escobera** [comment]
Something might have messed up my vscode installation. Removed everything and started from scratch, now this plugin is working =)

Thank you for your time.
