### ISSUE TITLE
(feature request) Heredoc Slim support (or a way to add custom heredoc syntaxes)

### ISSUE THREAD

**Issue by rafasoares** [rubyide/vscode-ruby#274]
### Environment 

- `vscode-ruby` version: 0.16.0
- Ruby version: 2.5.0
- VS Code version: 1.20.1
- Operating System: macOS High Sierra 10.13.3

### Expected behavior

Color Slim heredocs syntax the same way it works with HTML

### Actual behavior

Slim heredocs are colored as strings

### Steps to reproduce the problem

![screen shot 2018-02-22 at 9 51 52 am](https://user-images.githubusercontent.com/893971/36555201-236a3062-17b6-11e8-95b6-90f14aef1447.png)

### Additional Notes

Perhaps the best approach would be to allow a setting for custom heredoc matching. Something like:

```json
"ruby.heredoc.customSyntaxes": {
  "SLIM": "slim",
  "MATCHER": "vscode-syntax-key"
}
```

**Comment by wingrunr21** [comment]
Hmm, I will look into this.

This also raises a larger question as to whether we should be directly supporting HAML or Slim or leaving that to other extensions.

**Comment by rafasoares** [comment]
That's why I suggested the customization options. Simply set a matcher and the syntax key. The highlighting itself would be handled by VS Code or the appropriate extension.

I'm pretty sure this is how it works already (looking at https://github.com/rubyide/vscode-ruby/blob/72ae6af787b8d7f993975eab772f075f24c24f66/syntaxes/ruby.cson.json#L1558), but with a fixed list of syntaxes, thus adding another one for Slim would be a lot easier. Unless I missed something and you include syntax rules for things like SQL, GraphQL, CSS and XML in the vscode-ruby extension, of course.

**Comment by wingrunr21** [comment]
Except the syntax is loaded at extension load time and I've not yet found a way to modify the syntax via runtime configuration options

**Comment by wingrunr21** [comment]
Reloading the extension wouldn't do anything. VSCode loads the grammar based on the stuff in `package.json` and uses that for syntax highlighting.

I also don't want to be doing one-off edits to the grammar just to support specific uses cases. For instance, there's nothing that requires you to use `<<-SLIM` as the heredoc delimiter. How would we support slim detection via `<<-TEMPLATE`? Allowing VSCode to properly detect embedded languages and apply the appropriate syntax is a better option here (similar to what we do with ERB [here](https://github.com/rubyide/vscode-ruby/blob/master/package.json#L387). The problem with this approach is that it's basically going to require an entry for every language you can embed in a Heredoc.
