### ISSUE TITLE
Formatting not respecting .rubocop.yml

### ISSUE THREAD

**Issue by tdegrunt** [rubyide/vscode-ruby#275]
### Your environment

- `vscode-ruby` version: 0.16.0
- Ruby version: 2.4.2
- VS Code version: 1.20.1
- Operating System: macOS
- Hardware (optional):

I'm using bundler and rbenv.

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Calling "Format Document" should do exactly the same as calling `rubocop -c .rubocop.yml-afs <file>` from the command line. 

### Actual behavior
Even though -c .rubocop.yml is added in the arguments it doesn't do the same thing as the command line.

https://github.com/rubyide/vscode-ruby/blob/2e2ef99920b12437a511586d8f36a4e2f300f428/src/format/RuboCop.ts#L50

### Steps to reproduce the problem

.rubocop.yml:
```yaml
Lint/EndAlignment:
  AutoCorrect: true
```

test.rb
```ruby
test = false
foo = if test
'bar'
else
'qux'
end
```

After formatting from inside vscode test.rb looks like:
```ruby
test = false
foo = if test
        'bar'
      else
        'qux'
end
```

From the command line it looks like:
rubocop -c .rubocop.yml -afs test.rb
== test.rb ==
W:  4:  1: Lint/UselessAssignment: Useless assignment to variable - foo.
W:  8:  1: [Corrected] Lint/EndAlignment: end at 8, 0 is not aligned with if at 4, 6.

```ruby
test = false
foo = if test
        'bar'
      else
        'qux'
      end
```

**Comment by tdegrunt** [comment]
Just found out this will be fixed with the code in current repo (by manually installing it), closing.

**Comment by CharlieIGG** [comment]
Hey @tdegrunt I'm still facing what I think is the same issue you described here, but I cannot see any references as to when/if/how this got fixed. Can you point me in the right direction?
