### ISSUE TITLE
Reindex current open file not working

### ISSUE THREAD

**Issue by RMacfarlane** [rubyide/vscode-ruby#276]
_From @spsisys on February 23, 2018 17:23_

### Issue Type
Bug

### Description

Open .rb file (Ruby extension enabled), copy & paste new content: Shift-Cmd-P not find the new def method, F12 "symbol not found". I suppose reindex file content is not working properly. The problem's gone when quit & reopen Code.

### VS Code Info

VS Code version: Code 1.20.1 (f88bbf9137d24d36d968ea6b2911786bfe103002, 2018-02-13T15:23:28.607Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (1.66GB free)|
|Process Argv|/private/var/folders/xw/6gk49zsd2vs2_mk9k8wgs65w0000gn/T/AppTranslocation/BAC8840C-2E00-4DDA-A087-66644F97BCD6/d/Visual Studio Code.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.3.0
material-icon-theme|PKi|3.2.3
vscode-dash|dee|1.8.0
ruby-linter|hoo|1.0.0
rails-snippets|Hri|1.0.6
rails-fast-nav|jem|1.1.10
vscode-duplicate|mrm|1.2.0
mssql|ms-|1.3.0
vscode-open-iterm2|mus|0.0.4
advanced-new-file|pat|1.1.0
Ruby|reb|0.16.0
rails-latest-migration|tmi|0.0.1
highlight-matching-tag|vin|0.4.4
simple-ruby-erb|vor|0.2.1

</details>
Reproduces without extensions

_Copied from original issue: Microsoft/vscode#44288_

**Comment by andrewmcodes** [comment]
Is this still an issue with 0.20.0?
