### ISSUE TITLE
Matching do/end blocks

### ISSUE THREAD

**Issue by illegalnumbers** [rubyide/vscode-ruby#277]
### Your environment

- `vscode-ruby` version: 0.16.0
- Ruby version: 2.4
- VS Code version: 1.20.1 
- Operating System: macosx
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

Does this extension properly highlight do/end blocks? I have been unable to see highlighting to see where my blocks begin. 

### Expected behavior

Highlighting on do when clicked the cursor at an end keyword. Highlighting on an end when cursor is highlighted at the do beginning keyword.

### Actual behavior
Nothing highlights.

**Comment by illegalnumbers** [comment]
Also it seems like sometimes when it does highlight that it gets confused or mixed up by keywords being in other strings. For example if I have a string like 'The class was at 9 am' and a block around it it will match the class word in the string to the block which is incorrect. So I guess highlighting _sometimes_ works.

**Comment by wingrunr21** [comment]
Closing in favor of #282
