### ISSUE TITLE
comment character in string breaks indent on next line

### ISSUE THREAD

**Issue by eedwards-sk** [rubyide/vscode-ruby#280]
### My environment

- `vscode-ruby` version: 0.16.0
- Ruby version: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
- VS Code version: 1.20.1
- Operating System: OS X High Sierra 10.13.3 (17D102)
- Hardware (optional): 

### Expected behavior

next line indented correctly
```
line "#withCommentCharStartingString" do
    text_after_indent
end
```

### Actual behavior

next line indented incorrectly
```
line "#withCommentCharStartingString" do
text_after_indent
end
```

### Steps to reproduce the problem

- Open a new blank file
- Set language to 'ruby'
- Enter the following text:
```
line "#withCommentCharStartingString" do
end
```
- Place cursor at the end of the first line (after `do`)
- Press Enter

### Comparison

Remove the `#` character from the string, and note the behavior.

e.g.

```
line "withoutCommentCharStartingString" do
end
```

results in expected indentation of

```
line "withoutCommentCharStartingString" do
    text_after_indent
end
```

**Comment by wingrunr21** [comment]
Closing in favor of #282
