### ISSUE TITLE
Option to disable solargraph integration

### ISSUE THREAD

**Issue by dmke** [rubyide/vscode-ruby#281]
### Your environment

- `vscode-ruby` version: 0.17.0
- Ruby version: multiple via rbenv, no system-wide ruby
- VS Code version: 1.20.1
- Operating System: Debian Stretch (9.3)
- Hardware (optional): 

### Expected behavior

When opening the directory of a Rails app, I just want to code :-)

### Actual behavior

Since a recent version of this extension, I get a "Solargraph gem not found" message:

![image](https://user-images.githubusercontent.com/327411/36988189-8cc8fff2-209e-11e8-8ff2-a9aa5c6ebd55.png)

Installing the solargraph gem won't help, since (a) I don't have a global Ruby installation, and (b) the VSCode process does not evaluate per-directory `.ruby-version` files, i.e. loading the correct Ruby shims.

Updating the Gemfile is not possible, because I am not the only person managing the repository (but the only one using VSCode).

I don't want/need code completion (this has never really worked meta-programming-heavy languages like Ruby, so I'm used to not having it), so would like to see an option to disable it. I can also live with a "Don't show again" on the error message.

### Steps to reproduce the problem

- manage your Rubies with rbenv
- don't have a system wide Ruby installed
- open a Ruby file

**Comment by wingrunr21** [comment]
I'm going to close this as it is a dup of #263

**Comment by dmke** [comment]
Sorry for the duplicate, [is:issue solargraph](https://github.com/rubyide/vscode-ruby/issues?utf8=%E2%9C%93&q=is%3Aissue+solargaph) didn't yield any results...

![image](https://user-images.githubusercontent.com/327411/36991940-9b5b2d6e-20a9-11e8-8048-1188935a80b9.png)
