### ISSUE TITLE
Highlighting/Indention doesn't always work as intended

### ISSUE THREAD

**Issue by wingrunr21** [rubyide/vscode-ruby#282]
This is a tracking issue to collect issues related to the highlighting functionality and/or the indention not always working as intended.

The highlight provider is currently attempting to use regular expressions to figure out balanced pairs (see [here](https://github.com/rubyide/vscode-ruby/blob/master/src/ruby.ts#L58). This approach has proven to be quite brittle (as #253, #250, #231, #223 can attest).

Given how dynamic Ruby is, we may want to consider going with an AST implementation to correctly identify language constructs. This would have the added benefit of correctly identifying custom DSLs.

Tracked issues:
#257 (possibly caused by [`wordPattern`](https://github.com/rubyide/vscode-ruby/blob/master/src/ruby.ts#L22)
#265 
#277 
#280 
#322

**Comment by Dkapps** [comment]
Hello,
Not sure if my example is part of this issue but I have witnessed a strange behavior with the do/end highlight matching. The matching will often be confused with keywords in comments eg:
![2018-12-19_14-29-28](https://user-images.githubusercontent.com/9819361/50223887-adf7f200-039c-11e9-8d42-7144bbf81fec.png)

In the attached screenshot, the last **end** should match with a **do** keyword higher in the file but matches with the word **for** placed in the comments. It makes it quite confusing when I'm hunting a missing keyword in a file.

**Comment by wingrunr21** [comment]
Are you using the language server?

**Comment by Dkapps** [comment]
> 
> 
> Are you using the language server?
I couldn't make it work, it times out on startup and the I lose all highlighting. Maybe because I'm behind a corp proxy ? Should probably search for/file an issue on that then...

**Comment by wingrunr21** [comment]
It could be your proxy. It has to download precompiled binaries to work. The logs should provide more info.

Highlighting is improved in the language server. I won’t be putting additional effort into the old solution and will eventually deprecate it.

**Comment by wingrunr21** [comment]
Closing as this issue is out of date
