### ISSUE TITLE
Please remove hard dependency on 'Ruby Solargraph'

### ISSUE THREAD

**Issue by bmhatfield** [rubyide/vscode-ruby#284]
In the documentation, this is listed as an optional mode, but the vscode extension was installed automatically and I cannot uninstall it. I prefer to keep my extensions list lean and not add unnecessary dependencies.

<img width="1202" alt="screen shot 2018-03-06 at 9 13 46 am" src="https://user-images.githubusercontent.com/1119967/37036808-b9ae5712-211e-11e8-9f27-05bbb3d09040.png">

**Comment by wingrunr21** [comment]
Dup of #263
