### ISSUE TITLE
solar graph intellisense too slow

### ISSUE THREAD

**Issue by mberrueta** [rubyide/vscode-ruby#286]
### Your environment

- `vscode-ruby` version: 0.17.0
- Ruby version: 2.3.6
- VS Code version: 
- Operating System: MacOS
- Hardware (optional): 

 
 
### Actual behavior
intelligisense `loading` forever in large projects. even if I disable almos everything in the solargraph.yml

can I disable this ? and use the normal one?

**Comment by roflomglol** [comment]
Can't agree more. What happened? It worked fine before. Probably because it wasn't solargraph?

**Comment by castwide** [comment]
The `ruby.codeCompletion` and `ruby.intellisense` settings let you select the providers.

**Comment by roflomglol** [comment]
@castwide did something changed after 0.17.0 update in this regard? I haven't setup anything regarding codeCompletion and intellisense before and it worked fine. I could jump to method definitions pretty easily, but after update I noticed that I got new extension (solargraph), Its mandatory and I got to install gem. And all this works worse than before.

**Comment by castwide** [comment]
Sorry for the trouble. Solargraph will probably be removed as a hard dependency, although we'll continue to work on making it integrate well with vscode-ruby as an optional extension.

To use the original vscode-ruby feature for jumping to definitions, set `ruby.intellisense` to `rubyLocate`.

Also. please feel free to report solargraph-related bugs at https://github.com/castwide/vscode-solargraph.

**Comment by wingrunr21** [comment]
Closing in favor of #263

**Comment by mberrueta** [comment]
setting that, but I would like to disable solargraph
`Cannot disable extension 'Ruby Solargraph'. Extension 'Ruby' depends on this.`
