### ISSUE TITLE
Syntax highlighting issue with safe navigation operator

### ISSUE THREAD

**Issue by ob-stripe** [rubyide/vscode-ruby#288]
### Your environment

- `vscode-ruby` version: 0.17.0
- Ruby version: 2.4.3
- VS Code version: 1.21.0
- Operating System: macOS 10.13.3
- Hardware (optional): MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)

### Expected behavior

When calling a method on a variable using the safe navigation operator (`&.`), the variable should be highlighted.

### Actual behavior

The variable is not highlighted.

### Steps to reproduce the problem

Trivial:
<img width="287" alt="screen shot 2018-03-10 at 10 55 20 pm" src="https://user-images.githubusercontent.com/23086931/37247083-2e1b911a-24b6-11e8-91b7-d877692ee4aa.png">

**Comment by ob-stripe** [comment]
In case this helps:

<img width="524" alt="screen shot 2018-03-10 at 10 58 35 pm" src="https://user-images.githubusercontent.com/23086931/37247117-9ec598c0-24b6-11e8-8228-e4fc7816546c.png">

<img width="274" alt="screen shot 2018-03-10 at 10 58 44 pm" src="https://user-images.githubusercontent.com/23086931/37247118-a1d5f1e0-24b6-11e8-845a-9a1ba7006bc9.png">

This issue might be related to / a dupe of #283.

**Comment by wingrunr21** [comment]
I'm going to guess that it is but until I'm sure I'm going to leave this open.

I haven't gotten a chance to dive into this yet but my guess is the grammar doesn't have explicit support for that syntax given it is relatively new.

**Comment by wingrunr21** [comment]
The indicator is the Atom issue linked above. Until semantic syntax highlighting lands in the language server protocol highlighting is based on coded grammars. As Atom is the upstream grammar for us, they need to fix so I can pull it in.

**Comment by bbugh** [comment]
According to this PR, they have support for the safe navigation operator since 2015: https://github.com/atom/language-ruby/pull/125

Is there an easy way to enable it for this extension?

**Comment by wingrunr21** [comment]
It is already in the grammar

https://github.com/rubyide/vscode-ruby/blob/master/syntaxes/ruby.cson.json#L2111-L2119

**Comment by minkir014** [comment]
@wingrunr21 He added some lines in a coffee script file. Can this be the cause to this issue?

**Comment by bbugh** [comment]
The issue described in the original post is still present, though! My editor matches the screen shots. Variables using `object&.something` are not correctly colored.

**Comment by wingrunr21** [comment]
@minkir014 Potentially. VSCode activates grammars based on the detected language type at the bottom and whether that language declares other languages can be "embedded". If that parent language doesn't declare embedded languages then there's not much that can be done from a highlighting perspective.

@bbugh 
The coloring is based on the matching scopes and whatever your theme has specified for those scopes. The grammar would need to change to the appropriate scope. You commented on the exact upstream issue for this: atom/language-ruby#167. You could open a PR against that repo to fix it and then I could pull it in.
