### ISSUE TITLE
ERB Code Folding for "if" statements, etc

### ISSUE THREAD

**Issue by jarheck** [rubyide/vscode-ruby#304]
### Your environment

- `vscode-ruby` version: 0.17.0
- Ruby version: 2.4
- VS Code version: 1.21
- Operating System: Windows 10
- Hardware (optional): 

It would be really helpful to have proper code folding within the .erb files for "if", "do" and other statements

-  <%- if (condition) -%> 
   <%= code %>
   <%= code %>
   <%= code %>
-  <%- elsif (condition) -%>
   <%= code %>
   <% end %>

**Comment by gurgeous** [comment]
I believe that code folding in vscode is based entirely on indentation - we have no control over folding. Indent your `<%= code %>` lines and you'll get folding! That's probably the recommended style too. Personally I use HAML so take this with a grain of salt...

**Comment by wingrunr21** [comment]
Code folding will be supported in v1. Please use #317 to track progress on this.
