### ISSUE TITLE
Ignore spec and test files

### ISSUE THREAD

**Issue by garyking** [rubyide/vscode-ruby#306]
By default, Rubocop does not apply certain rules to files in the `spec/` and `test/` dirs, such as `Style/Documentation`, and `Style/DocumentationMethod` ([docs](https://rubocop.readthedocs.io/en/latest/cops_style/#styledocumentation)).

However, this extension still shows these warnings when editing these files. 

Why does this extension not use the same `Exclude` defaults that are used for several Rubocop rules?

**Comment by gurgeous** [comment]
I doubt this is happening on purpose. Would you be interested in investigating a bit?

**Comment by wingrunr21** [comment]
This should be behaving correctly in `v0.22.2` and up
