### ISSUE TITLE
Wrong line gets underlined

### ISSUE THREAD

**Issue by garyking** [rubyide/vscode-ruby#307]
I'm using Rubocop, and I've got a line underlined for the rule `Metrics/MethodLength`. I moved a few things around at the top of the file, and now I've got this rule still appearing, but a comment is underlined instead. 

Is there any way to force the linting to run again, so it doesn't highlight the wrong lines?

**Comment by gurgeous** [comment]
I've seen this as well and I don't know the cause. I think that a recent (not yet released) change that debounces/slows the linter might fix it. In the current release the linter runs on every single keystroke, which is super aggressive and error prone.

In the meantime, you may have to restart vscode. Sorry...

**Comment by andrewmcodes** [comment]
Is this still an issue with 0.20.0?

**Comment by wingrunr21** [comment]
This should be working correctly on `v0.22.2` and up with language server based linting
