### ISSUE TITLE
Feature Request: completion and jump to source from runtime process

### ISSUE THREAD

**Issue by amerov** [rubyide/vscode-ruby#310]
Actually, for ruby we need completion based on real runtime.
For example, Emacs has "robe-mode" package that interacts with process wrapped by pry, pry-doc...
It is really works.
It also work with source code than generated from runtime by `define_method`...

[Emacs and robe-mode demo video](https://www.youtube.com/watch?v=l_gkh3CsbTk)
https://github.com/dgutov/robe

**Comment by gurgeous** [comment]
See the excellent https://github.com/castwide/vscode-solargraph extension by castwide.

**Comment by amerov** [comment]
@gurgeous Its completion and source lookup doesn't work for gems.

**Comment by wingrunr21** [comment]
To be clear, I'm not currently planning on focusing on this feature. @gurgeous and @castwide are doing a great job solving this use case. I'm looking to make the core Ruby functionality better before implementing this in this project.
