### ISSUE TITLE
Unkown confirmation setting "ruby.format"

### ISSUE THREAD

**Issue by KevinColemanInc** [rubyide/vscode-ruby#314]
### Your environment

- `vscode-ruby` version: 0.17.0
- Ruby version: 2.5.1
- VS Code version: 1.21.1 79b44aa704ce542d8ca4a3cc44cfca566e7720f1 x64
- Operating System: OS X 10.13.4
- Hardware (optional): MBP

### Expected behavior

No error message when trying to set the ruby format in `settings.json`

### Actual behavior

Problem: "Unknown configuration setting" for "ruby.format"

### Steps to reproduce the problem
Add `"ruby.format": "rubocop"` to the user settings file in VS code.

**Comment by gurgeous** [comment]
The `ruby.format` setting will be in the next version of the extension.

**Comment by ianks** [comment]
awesome @gurgeous when do you think this will be? deciding whether or not to implement a temporary solution
