### ISSUE TITLE
README does not seem up to date

### ISSUE THREAD

**Issue by illegalnumbers** [rubyide/vscode-ruby#315]
Listed in the README on intellisense you say 'Use the ruby.intellisense setting to select a go to/peek definition method. Valid options are rubyLocate, and false.' but the default after install is Solargraph. What are the actual values this can be?

**Comment by wingrunr21** [comment]
The README reflects the unreleased version currently in `master`. Please review the README for the current release tag: https://github.com/rubyide/vscode-ruby/tree/0.17.0#intellisense-go-topeek-definition
