### ISSUE TITLE
Improved Configuration

### ISSUE THREAD

**Issue by wingrunr21** [rubyide/vscode-ruby#318]
Improve the configuration of the extension

- [ ] Allow language server features to be selectable to internal, legacy, or disabled. The disabled state will allow other language server providers to handle this instead. This is based on VSCode's behavior of [taking the first provider with the highest score](https://github.com/Microsoft/vscode/issues/11609).
- [ ] Allow configuration as to how the Ruby environment is loaded. This should support multi-root workspaces, monorepos with multiple `Gemfiles`, and different Ruby version managers

**Comment by gurgeous** [comment]
Should we list/prioritize the set of ruby environments we'd like to support? It's a nasty business, unfortunately, and extremely difficult for users to debug. With Bust-A-Gem all I did was support repos with a Gemfile at the root, and users can manually specify full replacements for stuff I use like `bundle show`. Am I right in thinking that's the most common setup?

Maybe @castwide can chime in. I know the solargraph extension does a nice job of finding and ugprading the gem. Perhaps there's even a library we can reuse somehow.

(great work on this btw)

**Comment by castwide** [comment]
You can check out the [solargraph-utils](https://github.com/castwide/solargraph-utils) package for some of the logic I used to detect ruby environments and make it work cross-platform. I'd be happy to help get those capabilities into vscode-ruby. It might be worthwhile to implement those features in a general-purpose Ruby environment package.

**Comment by wingrunr21** [comment]
This issue is now redundant with the work that went into auto detection of the environment. The language server work is also being done in a backwards compatible way so closing this out.
