### ISSUE TITLE
Poor performance of key input on ruby file

### ISSUE THREAD

**Issue by ypresto** [rubyide/vscode-ruby#320]
### Your environment

- `vscode-ruby` version: 
- Ruby version: 2.3.4
- VS Code version: 1.21.1
- Operating System: macOS Sierra 10.12.6
- Hardware (optional): MacBook Pro (Retina, 15-inch, Mid 2014)

### Expected behavior

Key input is smoothly applied to editor content.

### Actual behavior

It sometimes causes short freeze while key input.

### Steps to reproduce the problem

1. Enable Ruby plugin.
1. Focus to editor of ruby file.
1. Type fast, or keep pressing down `a` key.
1. `aaaaaaaa(freeze....)aaaaaaaa(freeze....)aaaaaaaaaa....`

I'm also using VSCodeVim plugin.
It does not reproduce if Ruby (this) plugin is disabled, even when Solargraph plugin is kept enabled.

**Comment by gurgeous** [comment]
Thanks for reporting. This is most likely due to the lack of debounce in the ruby linter. See #264, fixed in master but not yet released. You can install from master, disable for now, or be patient :)

**Comment by rebornix** [comment]
0.18.0 already has the fix of debouncing. Please reopen if you still have issues with typing.
