### ISSUE TITLE
Solargraph seems to handle go-to-definition/peek-definition too slow

### ISSUE THREAD

**Issue by TheTharin** [rubyide/vscode-ruby#323]
I've found some amount of similar issues here, that go-to-definition/peek-definition takes around 10-20 seconds to perform (instantaneously in Sublime Text 3), and found a solution to change it for rubyLocate. I've tried it, but have waited for almost an hour and a half for VSCode to finish Indexing Ruby source files, and nothing. It keeps indexing forever.
Is there any way to explicitly check if it's even doing anything?
Code indexing in Sublime Text on my code base takes roughly 7-10 minutes. I really like the flow and looks of VS Code, but the lack of go-to-definition function makes it almost unusable.

**Comment by wingrunr21** [comment]
Hi,

I'm going to close this as it is not a `vscode-ruby` issue. You'll probably have more luck filing under the [`vscode-solargraph` repo](https://github.com/castwide/vscode-solargraph).

ping @castwide regarding the issue as well
