### ISSUE TITLE
run tslint and prettier

### ISSUE THREAD

**Issue by gurgeous** [rubyide/vscode-ruby#325]
Now that we have formatting, should we do our cleanup? This would make the codebase easier to approach. Then we can enable formatOnSave too. Should be easy to generate the PR. Perhaps something like:

```
$ tslint --fix src/**/*.ts
$ find src -type f | grep -E "\.(js|ts)$" | xargs prettier --write
```

I don't want to mess up your big PR, @wingrunr21. This can wait until that PR is merged.

**Comment by rebornix** [comment]
@gurgeous I like the idea of having `formatOnSave` turned on in this workspace by default. Is there any particular reason that you want to use prettier instead of leverage TypeScript formatter since we are already writing TypeScript.

**Comment by gurgeous** [comment]
I am relatively new to typescript so I'm not very familiar with the tools. I was not aware that the vscode typescript support had built in formatting. We should use that, clearly. No reason to use prettier.

**Comment by wingrunr21** [comment]
Closing as this is being done on all new TypeScript. Purposefully choosing not to do it on older code.
