### ISSUE TITLE
linting => TypeScript

### ISSUE THREAD

**Issue by gurgeous** [rubyide/vscode-ruby#328]
I've spent some time rewriting the linting code in TypeScript. @wingrunr21, it's pretty early but I'd like to get your approval before I complete my work. I've refactored the existing code into new Typescript classes and I can perform RuboCop linting, though clearly I have a ways to go. I might be able to submit a PR this week if you agree with the general direction here.

There are specific questions for you to consider at the bottom of this comment.

https://github.com/rubyide/vscode-ruby/compare/master...gurgeous:lint2?expand=1&w=1

Here's my checklist:

- [x] basic RuboCop linting framework in TypeScript
- [x] ask @wingrunr21 to review WIP
- [ ] API for linting subset of document?
- [x] finalize tslint.json
- [x] finish rewrite (fasterer/reek, error handling, disposal, config notifications...)
- [ ] review historic linting issues (#238, #262, #307, and #324...)
- [ ] test(s)
- [ ] remove old linting implemention

It would be great if you could provide answers to these questions before I continue:

1. Should I continue? It's quite extensive. Any feedback on the design prior to a PR?
1. What would you like in terms of an API for linting a subset? Perhaps a method that takes a block of data and turns it into an array of diagnostics? It's ok if you don't know the answer yet.
1. I think we should reconsider our `tslint.json` and maybe switch to the default generated by `yo code`. Our current tslint.json is overly pedantic and doesn't let tsc infer types. For example:

```ts
// required by current tslint.json
const s: string = "hello"
// default tslint.json
const s = "hello"
```
It is a huge headache to add full typedefs to all classes, methods, and variables as required by our pedantic tslint settings.

**Comment by patricko** [comment]
This looks very promising! Thanks for the hard work!

**Comment by wingrunr21** [comment]
1. I guess I'm not clear what problems in the current implementation your code is solving? The underlying way everything works appears to be very similar but it is rewritten in a cleaner way. It also somewhat cleans up some of the configuration options. What else is it addressing?

   I also won't be able to use utilize this implementation without modification as the `Linting` object makes assumptions as to the context it is running in.
2. I'm not sure this is going to be required. VSCode doesn't actually do partial changesets (it sents the whole doc over with metadata on the changes).
3. I would consider disabling `interface-name` but definitely not `no-any` and `no-console`. I'm somewhat indifferent on `newline-before-return` but I do think having one reads better.

**Comment by gurgeous** [comment]
Thanks for getting back to me. So, it sounds like I should keep going? :)

1. I aspire to fix all the existing linting bugs, and add new features like format on save. New development should be done with TypeScript, right? The whole thing needs a revisit because the underlying linters were originally implemented as straight functions.

2. What API would you like for the new language server? Let me know and I can implement it.

3. I guess I don't care too much either way about the tslint settings. If our goal is to make our code pass the linting check, it would be nice to start with something less pedantic. Here are the default settings from `yo code` as recommended in the VS Code extension docs (below). I used this for another project and found it pleasant and sufficient.
  
Regarding those specific tslint rules... `no-any` is pretty strict. It makes it difficult to parse JSON, for example. We can disable that one on a case-by-case basis, I suppose. `no-console` seems undesirable. Don't we want to have lots of console logging for debugging? But the really painful one is `typedef`. That prevents TypeScript from inferring many obvious cases. If I could pick one rule to relax, that would be the one. I'm pretty new to TypeScript so I'm happy to let you make the decision here. Just chiming in.

```js
// default from running yo code
{
  "rules": {
    "no-string-throw": true,
    "no-unused-expression": true,
    "no-duplicate-variable": true,
    "curly": true,
    "class-name": true,
    "semicolon": [true, "always", "ignore-bound-class-methods"],
    "triple-equals": true
  },
  "defaultSeverity": "warning"
}
```

**Comment by wingrunr21** [comment]
1. I don't really care how new development is done. Typescript is how a lot of the VSCode APIs are exposed/enforced so I think that makes sense, but functional JS would be totally valid if it makes sense.
2. I'm not the one who dictates the API. The events that are subscribed to are a part of the language server protocol. Right now your "manager" assumes it is running in the context of a direct implementation. I'd prefer to ship the language server alongside the direct implementation while we are testing it. That means it may be a better architecture decision to have the linting "manager" be one object and then have the actual adapter for the runtime environment be another.
3. What situation do you have where you've got JSON responses that are not of a known structure? `no-any` is strict for a reason: we are looking for responses of a given type/structure.

   If the linter rules are too onerous then relaxing the constraints is fine, but I want to make sure we're maintaining the whole point of using Typescript. If the settings are so loose that using types is basically optional, there's not really a point in using Typescript.

**Comment by gurgeous** [comment]
Here's the latest if you want to check progress. A few more comments below.

https://github.com/rubyide/vscode-ruby/compare/master...gurgeous:lint2?expand=1&w=1

2. It would be easy to break Linting into two parts, a vscode adapter and the linting manager. Not a problem.

3. I'll remove `no-any: false` and `newline-before-return: false`. I checked for `any` in my branch. It's only used for JSON and a bit of error handling. I'll add interfaces for those things or just disable the check for those specific lines. In general I'm making heavy use of Typescript linting, don't worry. :) I'll try `typedef: false` and see how that feels, unless you object. I think that'll make it easier for people to contribute.

Would you like me to continue my work and push toward a PR? Pretty much the only thing left at this point is a review of historical github issues and more testing/tests. Plus the Linting breakup described in (2) above, but that can come later.

**Comment by gurgeous** [comment]
Calling @wingrunr21... should I finish this up? Mostly testing at this point but I only want to push ahead if you are interested in the PR. :)

**Comment by wingrunr21** [comment]
I'll take a look tonight
