### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by MarvDann** [rubyide/vscode-ruby#330]
### Your environment

- `vscode-ruby` version: 0.18.0
- Ruby version: 2.2.6p396
- VS Code version: 1.22.2
- Operating System: Windows 10 Pro
- Hardware (optional): LenovoThinkpad Ultrabook i7

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you ! 

ruby-debug-basex19 - doesn't exist. I tried installing ruby-debug-base19x in case it was a typo but that failed to install.

### Expected behavior
Debugger is attached as normal

### Actual behavior
Debugger quits with the message 'Debug adapter process has terminated unexpectedly' This message pops up twice and the debugger doesn't start.

### Steps to reproduce the problem
{
   "version": "0.2.0",
   "configurations": [
      {
         "name": "Debug Server",
         "type": "Ruby",
         "request": "launch",
         "cwd": "${workspaceRoot}",
         "program": "${workspaceRoot}/main.rb",
         "args": ["server"]
      }]
}

**Comment by wingrunr21** [comment]
`ruby-debug-base19x` is for Ruby 1.9. You'll need to install an appropriate backend for `ruby-debug-ide` like `byebug` or `debase`.

**Comment by MarvDann** [comment]
Hi wingrun21. thanks for your reply. I have the latest version of debase installed and the error persists. 
My comment about ruby-debug-basex19 was in response to your minimum requiremens on this post.
Please re-open.
