### ISSUE TITLE
Ability to exclude certain files from go-to-definition

### ISSUE THREAD

**Issue by rattrayalex-stripe** [rubyide/vscode-ruby#348]
We have some "mirrored" class definitions in a special folder and would like to exclude them from "Go To Definition" / "Peek Definition" results. 

Is this possible? Thoughts on adding this ability as a config option?

**Comment by gabe-stripe** [comment]
Would this be relevant for you? 

```
"ruby.locate": {
	"include": "**/*.rb",
	"exclude": "{**/@(test|spec|tmp|.*),**/@(test|spec|tmp|.*)/**,**/*_spec.rb}"
}
```
- https://github.com/rubyide/vscode-ruby#user-content-rubylocate

Note that by default it excludes figuring out symbols for `test` directories too.

**Comment by rattrayalex-stripe** [comment]
Oops, missed that – yes, does the trick! Thanks.
