### ISSUE TITLE
How to configure rubocop-rspec require of rubocop dependency gem

### ISSUE THREAD

**Issue by choosen** [rubyide/vscode-ruby#352]
### Your environment

- `vscode-ruby` version: 0.18.0
- Ruby version: 2.4.2
- VS Code version: Version 1.24.1 (1.24.1)
- Operating System: MacOS High Sierra
- Hardware (optional): Macbook 2k15 Pro

### Expected behavior

checking rspec files properly

### Actual behavior

rubocop is working, but without rspec rules from rubocop-rspec.

My setup in VSC:
```
"ruby.lint":{
  "rubocop": {
     "lint": true,
     "rails": true,
     "require": ["rubocop-rspec"] # this also did not help
  }
}
```

### Steps to reproduce the problem

add 'require: rubocop-rspec' on top `.rubocop` file

**Comment by rubydog** [comment]
I am facing same issue. Any update on it? @choosen Did you figure out how to fix it?

**Comment by wingrunr21** [comment]
Are you all using rubocop via bundler? You could create a binstub that would ensure both dependencies are loaded with the bundler environment comes up.

**Comment by choosen** [comment]
from my config:
```
    "ruby.pathToBundler": "/Users/user/.rbenv/shims/bundle",
    "ruby.useBundler": true,
```
I did not resolved problem yet. 
I use overcommit hooks, but it would be more convenient to see remarks in VSC

**Comment by choosen** [comment]
what about this default setting ? :
```
 // Defines where the Ruby extension will look to find Modules, Classes and methods.
  "ruby.locate": {
    "exclude": "{**/@(test|spec|tmp|.*),**/@(test|spec|tmp|.*)/**,**/*_spec.rb}",
    "include": "**/*.rb"
  },
```

**Comment by wingrunr21** [comment]
Can you try `0.22.0` and run RuboCop via the language server?

**Comment by choosen** [comment]
yeah, now it works like a charm without `"require": ["rubocop-rspec"]` 
👍
