### ISSUE TITLE
Release v0.19.0

### ISSUE THREAD

**Issue by wingrunr21** [rubyide/vscode-ruby#355]
v0.19.0 is tagged. @rebornix can you release it?

**Comment by toddmazierski** [comment]
Hi @wingrunr21,

Sorry to bug, but is there anyone else available to release the new version?

**Comment by wingrunr21** [comment]
I don't know. I don't have the ability to publish the extension.

Ping @rebornix

**Comment by numbcoder** [comment]
Ping @rebornix

**Comment by wingrunr21** [comment]
0.19.0 was published on the 31st. I have been given publish permissions now so I should be able to publish newer versions from now on.

Thanks everyone!
