### ISSUE TITLE
debug sinatra based app

### ISSUE THREAD

**Issue by typekpb** [rubyide/vscode-ruby#36]
### Your environment

- `vscode-ruby` version: 0.5.1
- Ruby version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
- VS Code version: 1.1.1
- Operating System: RHEL 7.2
- Hardware (optional): 

> Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you ! 

Well I don't have ruby-debug-base installed, as it seems to be relevant for 1.9 versions only

### Expected behavior
Possible to debug sinatra based app.

### Actual behavior
Fails while launching the debug with err:

	/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x75be58 debase-0.2.1> (NoMethodError)
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/debase-0.2.1/lib/debase.rb:4:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:8:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:8:in `require_relative'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:8:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/rdebug-ide:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/rdebug-ide:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

### Steps to reproduce the problem
1. cloned project: 

	clone https://github.com/datarator/datarator.git
	cd datarator
	code .

1. opened in vstudio and created launch config with contents:

        {
            "version": "0.2.0",
            "configurations": [
                {
                    "name": "Debug Local File",
                    "type": "Ruby",
                    "request": "launch",
                    "program": "${workspaceRoot}/config.ru"
                }       
            ]
        }

1. Tried to debug, resulting in error above.

**Comment by HookyQR** [comment]
Could you delve into the `/usr/local/rvm/gems/ruby-2.3.0/gems/debase-0.2.1/lib/` directory and check if there is a `debase_internals.so` or `debase_internals.a` file there. It seems like the debase gem didn't build properly.

**Comment by typekpb** [comment]
thanks for feedback, not sure why but it seems to be working for me now. Anyway, I ended up with `launch.json` like this:

    {
        "version": "0.2.0",
        "configurations": [
            {
                "name": "Debug Local File",
                "type": "Ruby",
                "request": "launch",
                "program": "${workspaceRoot}/bin/datarator"
            }       
        ]
    }
