### ISSUE TITLE
Missing decorators on scrollbar for highlighted word

### ISSUE THREAD

**Issue by jaydee864** [rubyide/vscode-ruby#360]
### Your environment

- `vscode-ruby` version: 0.18.0
- Ruby version: ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
- VS Code version: 1.24.1
- Operating System: Windows 10 v. 1803

### Expected behavior

Highlighting a word in Ruby code should add a decorator to the scrollbar indicating other locations in the code where that word can be found, as in the below screenshot, taken with vscode-ruby disabled:
![vscode-ruby-disabled](https://user-images.githubusercontent.com/7988064/41875620-4ffaf186-7880-11e8-9149-db2785154e77.png)

### Actual behavior
Highlighting a word in Ruby code does not add a decorator to the scrollbar, I have to use the Find feature to see the decorators. Compare the below screenshot with the previous one, taken with vscode-ruby enabled:
![vscode-ruby-enabled](https://user-images.githubusercontent.com/7988064/41875681-8efa1b5a-7880-11e8-9029-1d0b15d38400.png)

### Steps to reproduce the problem
1. Install vscode-ruby
2. Open a Ruby file and highlight a word which occurs more than once in the same document

**Comment by andrewmcodes** [comment]
Is this still an issue with vscode-ruby 0.20.0?

**Comment by jaydee864** [comment]
Yes, verified this is still an issue in vscode-ruby 0.20.0.

**Comment by wingrunr21** [comment]
This will be fixed via the symbol highlight support in the language server. There's another tracking issue for that so I will be closing this one.
