### ISSUE TITLE
There is no selection formatter for 'ruby'-files installed.

### ISSUE THREAD

**Issue by ecbrodie** [rubyide/vscode-ruby#361]
### Your environment

- `vscode-ruby` version: 0.18.0
- Ruby version: 2.5.0
- VS Code version: 1.24.1
- Operating System: Mac OS 10.13.5

### And ... the issue

_I'm sorry! I know I'm breaking apart from your Issue template, but this seems more like a Feature Request than a Bug._

I just worked very hard to add Rubocop to a Ruby project so I can finally use vscode-ruby to format my Ruby code in VSCode. So now the file formatting action (OPT-SHIFT-F) will finally work.

However, it looks like selection formatting (CMD-K CMD-F) still doesn't work. When I run that command, I get the following error message:

> There is no selection formatter for 'ruby'-files installed.

My hunch is that support for selection formatting still hasn't been added to vscode-ruby; I could not find any Issues that existed talking about selection formatting. Regardless, I wanted to report this, at it would be very nice if this extension had selection formatting support.

Thank you!

**Comment by Altons** [comment]
@ecbrodie would you mind sharing how-to get rubocop to work at least with `OPT-SHIFT-F`.

thanks

**Comment by ecbrodie** [comment]
@wingrunr21 any way I can raise attention to this Issue? I am still running into trouble getting VSCode-Ruby to execute the selection formatter when I have rubocop formatting enabled on my project, and also most definitely installed for my Ruby version. Document formatting works fine though.

**Comment by wingrunr21** [comment]
`v0.22.0` supports selection formatting

**Comment by ecbrodie** [comment]
@wingrunr21 I don't think this is working in 0.22.x. But, sounds like #434 is a dupe issue reported for this.

**Comment by wingrunr21** [comment]
It is working but for `rubocop` or `standard` you can't have any linter errors (due to the return code). #434 handles that bug.
