### ISSUE TITLE
Debugger stops at breakpoint but doesn't see any variables

### ISSUE THREAD

**Issue by nonsenseless** [rubyide/vscode-ruby#364]
### Your environment

- `vscode-ruby` version: 0.18.0
- Ruby version: 2.5.1 (using rbenv to manage ruby environment)
- VS Code version: 1.24.1
- Operating System: MacOS High Sierra
- Hardware (optional): 2013 Macbook Pro

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !
ruby-debug-ide: 0.6.1
debase 0.2.2

### Expected behavior
When running a program, I should be able to add a breakpoint and the debugger will stop on hitting that breakpoint allowing me to see what variables are currently in scope.

### Actual behavior
The debugger stops at the appropriate moment but the Variables section of the debugger is empty and nothing appears to be in scope in the debugger console. I can press step over and it wiil *very* slowly move to the next step.

### Steps to reproduce the problem

- Install ruby-debug-ide
- Install debase
- Add ruby, solargraph, and rubocop extensions to vscode.
- Add breakpoint controller
- Navigate to page that matches controller action.

### Additional Notes
This is happening on a Rails app and using the default rails server debug config options added to launch.json by vscode/vscode-ruby. I've set this up successfully on two other computers and I can't tell what's different between the installs. I've tried completely uninstalling all VSCode files (at the system level and the local .vscode folder) but the issue seems to persist.

**Comment by fones** [comment]
Same here. 

When I press play on breakpoint nothing happen.

vscode 1.24.1
vscode-ruby: 0.18.0
ruby: 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin17]
os: mac os high sierra 10.13.5
hw: 2017 MacBook Pro

```
Fast Debugger (ruby-debug-ide 0.6.1, debase 0.2.2, file filtering is supported) listens on 127.0.0.1:1234
Connected from 127.0.0.1
25009: Starting control thread
25009: Processing in control: break /Users/fones/Documents/Git/socialproof-omega/app/controllers/landing_controller.rb:4
25009: <breakpointAdded no="1" location="/Users/fones/Documents/Git/socialproof-omega/app/controllers/landing_controller.rb:4"/>
25009: Processing in control: start
25009: Starting: running program script
25009: Processing in control: thread list
25009: <threads>
25009: <thread id="2" status="sleep" pid="25009" />
25009: </threads>
=> Booting Puma
=> Rails 5.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
[25009] Puma starting in cluster mode...
[25009] * Version 3.7.0 (ruby 2.3.1-p112), codename: Snowy Sagebrush
[25009] * Min threads: 1, max threads: 5
[25009] * Environment: development
[25009] * Process workers: 2
[25009] * Preloading application
[25009] * Listening on tcp://0.0.0.0:3000
[25009] Use Ctrl-C to stop
[25009] - Worker 0 (pid: 25021) booted, phase: 0
[25009] - Worker 1 (pid: 25022) booted, phase: 0
Started GET "/" for ::ffff:127.0.0.1 at 2018-07-07 21:53:31 +0200
  ActiveRecord::SchemaMigration Load (0.3ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Started GET "/pl" for ::ffff:127.0.0.1 at 2018-07-07 21:53:31 +0200
  ActiveRecord::SchemaMigration Load (0.4ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by LandingController#index as HTML
  Parameters: {"locale"=>"pl"}
25022: <breakpoint file="/Users/fones/Documents/Git/socialproof-omega/app/controllers/landing_controller.rb" line="4" threadId="5"/>
25022: Stopping Thread #<Thread:0x007f8a311751e8> (25022)
25022: Threads equal: true
25009: Processing in control: thread list
25009: <threads>
25009: <thread id="2" status="sleep" pid="25009" />
25009: </threads>
Started GET "/pl" for ::ffff:127.0.0.1 at 2018-07-07 21:53:38 +0200
Processing by LandingController#index as HTML
  Parameters: {"locale"=>"pl"}
25021: <breakpoint file="/Users/fones/Documents/Git/socialproof-omega/app/controllers/landing_controller.rb" line="4" threadId="5"/>
25021: Stopping Thread #<Thread:0x007f8a31175558> (25021)
25021: Threads equal: true
25009: Processing in control: thread list
25009: <threads>
25009: <thread id="2" status="sleep" pid="25009" />
25009: </threads>
```

Press play on vscode debugger control adds no logs here.

**Comment by fones** [comment]
@nonsenseless have you resolved this issue?

**Comment by nonsenseless** [comment]
Fones: Yes, in my case, it looks like the issue was that I was running
Rails 5.1.1. When I migrated the application to 5.2 the debugger started
working about as expected. Your logs say you're on 5.0 so I'd try migrating
and go from there.

**Comment by DavidGriswoldTeacher** [comment]
This issue is closed, I know, but I am also having this same problem on Rails 5.1.1 . Unfortunately, I am simply working on fixing something in an open-source app and have no ability to migrate to rails 5.2 (an initial attempt failed miserably). 

For me I'm trying to debug into a docker container, which obviously adds another wrinkle, but this bug report very closely matches my own result. It stops at my breakpoint, but I can't actually see anything and the Call stack shows 8 "running" threads and nothing else.
