### ISSUE TITLE
couldn't find rubocop for formatting (ENOENT)

### ISSUE THREAD

**Issue by vedmant** [rubyide/vscode-ruby#370]
### Your environment

- `c` version: 0.18.0
- Ruby version: 2.4.1
- VS Code version: Version 1.25.1 (1.25.1)
- Operating System: MacOS
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
Formatting should work

### Actual behavior
Shows: couldn't find rubocop for formatting (ENOENT) on window reload

### Steps to reproduce the problem
1. Install couldn't find rubocop for formatting (ENOENT)
1. Set "ruby.format": "rubocop"
1. Reload window

rubocop gem is installed with `gem install rubocop` and `which rubocop` shows: `/Users/vedmant/.rvm/gems/ruby-2.5.1/bin/rubocop`

I couldn't find a way to specify path for rubocop

**Comment by levma** [comment]
same here, but with rbenv instead of rvm

**Comment by Te7a-Houdini** [comment]
can you try to add this settings to vscode , as i think this is what's used in the  [source code](https://github.com/rubyide/vscode-ruby/blob/master/src/format/RuboCop.ts#L29)

`"ruby.lint.rubocop" : {
        "exe" : "/Users/vedmant/.rvm/gems/ruby-2.5.1/bin/rubocop"
    }`

**Comment by goodforever** [comment]
same error, and after I set "ruby.lint.rubocop" : { "exe" : "/Users/vedmant/.rvm/gems/ruby-2.5.1/bin/rubocop" }  I got another error:
rubocop failed with code=127

**Comment by donwlewis** [comment]
I to have the same issue, but I think my situation is a bit different.  I am leveraging the ruby version wrapped in ChefDK, and am getting the same error.

**Comment by wingrunr21** [comment]
Automatic environment detection will ship for the language server in 0.22.0. See #405

**Comment by Carrein** [comment]
I am getting a similar error in VC.
`carrein@DESKTOP-MP8IGIO:~$ find . -name "rubocop"
./.rbenv/shims/rubocop
./.rbenv/versions/2.5.1/bin/rubocop
./.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-0.65.0/exe/rubocop
./.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-0.65.0/lib/rubocop`

I tried all the above paths but nothing seems to work both with or without the rubocop extension from the marketplace.

**Comment by wingrunr21** [comment]
Hi @Carrein 

Please file a new issue around this with all the included details (such as your config and relevant output)

**Comment by efagerberg** [comment]
To make use of what @wingrunr21 mentioned, you will need to set `useLanguageServer` in your config to be true. I believe this comes with rubocop linting (or at least the docs suggest as much) so you should be able to disable the linting option in the ruby settings.

**Comment by MarkusAbtion** [comment]
> can you try to add this settings to vscode , as i think this is what's used in the [source code](https://github.com/rubyide/vscode-ruby/blob/master/src/format/RuboCop.ts#L29)
> 
> `"ruby.lint.rubocop" : { "exe" : "/Users/vedmant/.rvm/gems/ruby-2.5.1/bin/rubocop" }`

This worked with the following template:
"<ROOT>/.rvm/gems/ruby-<VERSION>/bin/rubocop"

So for me that was:
"~/.rvm/gems/ruby-2.7.1/bin/rubocop"

**Comment by rgaufman** [comment]
Any solution to this?

**Comment by qurriahSam** [comment]
I had the same error, prettier  is set as my default fomartter I think it conflicts with rubocop.

```
"ruby.format": "rubocop",
  "[ruby]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": null
  },
```

adding this in settings.json solved my issue.
