### ISSUE TITLE
def end method highlighting does not work

### ISSUE THREAD

**Issue by codingdracula** [rubyide/vscode-ruby#372]
### Your environment

- `vscode-ruby` version: 0.19.0
- Ruby version: ruby-2.4.2
- VS Code version: Version 1.25.1 (1.25.1)
- Operating System: iMac (Retina 5K, 27-inch, Late 2014)
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
**def** new
**end**

When I go to a .rb file I expect the words def & end to be highlighted when I place my cursor to the right of def or end.

### Actual behavior
def & end do not highlight. If I write a new method (name does not matter) then def & end will highlight as normal in that file. When I go to a new file, I have to create a method before def and end properly highlight again

### Steps to reproduce the problem
1. open up a ruby file that has some basic methods ex:
_test.rb_
```
def hello
end
```
2. put your cursor to the right of def or end. (notice that it does not highlight)
3. in that same file, write another method (doesn't matter what it is). Notice that now when you place your cursor to the right of def or end highlighting is now working.
_test.rb_
```
def hello
end

def highlighting_working_now
end
```

**Comment by wingrunr21** [comment]
This will be addressed by #366 and the language server work.
