### ISSUE TITLE
Codelens capabilities for language server

### ISSUE THREAD

**Issue by kbrandwijk** [rubyide/vscode-ruby#379]
I'm developing an extension for VS Code that provides CodeLens capabilities to Ruby files. For this, the language server needs to include this capability. Is this somewhere on the roadmap, or would it be possible to contribute this feature on a short term?

**Comment by wingrunr21** [comment]
It is on the roadmap

**Comment by wingrunr21** [comment]
Closing as this is encapsulated by the roadmap in #317
