### ISSUE TITLE
"WARN: Unresolved specs during Gem::Specification.reset"

### ISSUE THREAD

**Issue by garyking** [rubyide/vscode-ruby#381]
### Your environment

- `vscode-ruby` version: 0.20.0
- Ruby version: 2.4.2
- Ruby version manager (if any): rvm 1.29.3
- VS Code version: Version 1.26.0 (1.26.0)
- Operating System: OS X 10.13.5 (17F77)
- Using language server? Yes, SolarGraph

### Expected behavior

The error message shouldn't appear.

### Actual behavior

Whenever I open the `Debug Console`, I get:

```
WARN: Unresolved specs during Gem::Specification.reset:
      rake (>= 0.8.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

How do I stop this from appearing?

**Comment by andrewmcodes** [comment]
Try running `gem cleanup rake` and see if that resolves it. 
[ref](
https://github.com/rubygems/rubygems/issues/1267)

**Comment by wingrunr21** [comment]
This does not appear to be vscode-ruby issue but rather an issue with the Rubygems environment. Please let me know if this isn't the case and I can reopen the issue.
