### ISSUE TITLE
GoTo Definition not working for Ruby

### ISSUE THREAD

**Issue by weinand** [rubyide/vscode-ruby#39]
_From @AlminCode on July 12, 2016 7:57_

- VSCode Version: Code 1.3.0
- OS Version: OS X, El capitan

Steps to Reproduce:

1. Open ruby file in VS code
2. Press F12 on selected method - nothing happens

_Copied from original issue: Microsoft/vscode#9117_

**Comment by HookyQR** [comment]
@AlminCode @weinand: The ruby extension does not yet support symbol marking. Development for this functionality is in progress.

**Comment by AlminCode** [comment]
@HookyQR Oh, didn't know, thanks for the clarification!

**Comment by xmattstrongx** [comment]
:( looks like Im still stuck using intelliJ for Ruby. Cant wait for this feature!

**Comment by rebornix** [comment]
@xmattstrongx intellij has an inhouse AST parser and we don't have a perfect competitive open source library so it takes time to handle it :)

**Comment by anpham-xo** [comment]
Im also expecting this feature. Thanks for handling it. 👍

**Comment by yozlet** [comment]
Might [Ripper](http://ruby-doc.org/stdlib-2.3.1/libdoc/ripper/rdoc/Ripper.html) (the Ruby-parsing library that's now part of Ruby's stdlib) be useful here?

**Comment by rebornix** [comment]
@yozlet thanks for the info, I'll see if I can convert Ripper to language service.

**Comment by HookyQR** [comment]
Update to `v0.6.0`. Solved by #59.

**Comment by hackhowtofaq** [comment]
@yozlet look at https://github.com/castwide/solargraph

@HookyQR  it is not working for Class methods

Ty

**Comment by tansaku** [comment]
I have the plugin installed, but not getting goto definition functionality anywhere - is there something I have to do to active it?

**Comment by kusumajati51** [comment]
i can't found ruby.codeCompletion in my vscode
