### ISSUE TITLE
Support for rvm gemsets etc

### ISSUE THREAD

**Issue by af6140** [rubyide/vscode-ruby#391]
Really like the rubymine capabilities that you can switch rvm gemsets at project level. Wondering whether it is possible to implement this feature, though it may be a big effort and requires vscode level changes.

**Comment by wingrunr21** [comment]
I'm not sure this is something I want to explicitly support. I'm not an RVM user so I'd need someone who is to help verify the implementation. Also, I feel RVM specific features should probably go in their own extension vs being baked into this one.

**Comment by wingrunr21** [comment]
Just for clarity, are you asking for this extension to automatically use gemsets (via the `.ruby-gemset` or `.ruby-version` files or are you asking for UI options to allow you to switch a gemset within the editor?

If it is the former, I'm finishing up changes that should fix automatic environment detection for most of these use cases.

**Comment by af6140** [comment]
@wingrunr21 , dot file processing works.

**Comment by wingrunr21** [comment]
Ok. There should be fixes for environment detection hitting the language server within the next week (hopefully). I'm finishing up a pretty large update.

**Comment by ismardantas** [comment]
Hello, is it already done?

**Comment by wingrunr21** [comment]
#405 has been merged and should pick up the RVM gemset if you have it properly configured via your shell
