### ISSUE TITLE
Require Statements Failing in Debugger

### ISSUE THREAD

**Issue by JCass45** [rubyide/vscode-ruby#392]
### Your environment

- `vscode-ruby` version: 0.20.0
- Ruby version: 2.5.1p57
- Ruby version manager (if any): N/A
- VS Code version: 1.27.2
- Operating System: macOS High Sierra 10.13.6
- Using language server? Yes

### Expected behavior
When starting debugger on a simple script, expect a 'require' statement to import the requested library. e.g.

```
require 'io/console' 

puts IO.console.winsize
```

### Actual behavior
Debugger fails to include the library.
with example from above, debugger throws the following error
```
Uncaught exception: undefined method `winsize' for nil:NilClass
	/Users/jack/Code/Ruby/Learning/debug-test.rb:3:in `<top (required)>'
	/usr/local/bin/rdebug-ide:23:in `load'
	/usr/local/bin/rdebug-ide:23:in `<main>'
```

My `launch.json` configuration:

```
{
      "name": "Debug THIS File",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${file}"
}
```

Output from `gem list | grep ide`: `ruby-debug-ide (0.6.1)`

**Comment by inweblife** [comment]
No work and for me

**Comment by wingrunr21** [comment]
Yes, there are numerous issues with the current debugger implementation. Sorry, it's on the list but that's about all I've got right now.

**Comment by wingrunr21** [comment]
I'm going to merge this with #316
