### ISSUE TITLE
Breaks standard trimFinalNewLines feature of VScode

### ISSUE THREAD

**Issue by auchenberg** [rubyide/vscode-ruby#393]
Reported from marketplace:

"breaks standard trimFinalNewLines feature of VScode"

**Comment by wingrunr21** [comment]
This issue doesn't follow the issue template. Without more information there's not much to go on to debug. Are you currently experiencing this issue?

**Comment by auchenberg** [comment]
Hi, this is Kenneth from the VS Code team. This issue was reported via our marketplace with this amount of detail. I have asked the original reporter to contribute to this issue with more details to make it more actionable.

**Comment by wingrunr21** [comment]
@auchenberg thanks, but there's no detail there (which was in the issue template) that will enable debugging. Without that, I'm closing this issue.
