### ISSUE TITLE
Debugger is not stopping at breakpoints

### ISSUE THREAD

**Issue by arunagirinathan-rajan** [rubyide/vscode-ruby#403]
### Your environment

- `vscode-ruby` version: 0.20.0
- Ruby version: 2.5.1
- Ruby version manager (if any): rvm
- VS Code version: 1.28.2
- Operating System: OS X 10.14
- Using language server?

### Steps to reproduce

I am using custom framework to run spec files(Rspec).

After i marked my breakpoints inside the code, I will start my execution. But the debugger is not stopping at breakpoints. debugger just ignores/skip the breakpoints. Debugger works like runner. directly fly to end.

### Expected behavior

Debugger should stop at the break point and show all necessary debug information like call stack etc

### Actual behavior

Debugger is not stoping and there is no visual representation.

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*

### Additional Information: 

Find my debug configuration which i gave in launch.json.

> {
> "name": "Webframe",
> "type": "Ruby",
> "request": "launch",
> "cwd": "${workspaceRoot}",
> "program": "/Users/arunagirinathanr/.rvm/gems/ruby-2.5.1/bin/webframe",
> "env": {
> "PLAN":"Garden"
> },
> "args": [
> "${file}",
> "spec/abandoned_call_metrics1.rb"
> ]
> }

**Comment by natchiketa** [comment]
Are you using Bootsnap? That fixed it for me.

**Comment by MicMicMon** [comment]
Same here, can't get it to work.
Using `rbenv`, nothing fancy but can't get it to break on breakpoints.

And if I start debugging with a breakpoint active, when it should break on it (request comes in), instead the request just hangs, and vscode shows no context. Never returns, and seems like it's stopped.

Any luck with a fix so far?

**Comment by arunagirinathan-rajan** [comment]
@natchiketa I'm not using rails application. So Bootsnap didn't give hand to me.

**Comment by wingrunr21** [comment]
Dup of #316
