### ISSUE TITLE
Launch not working

### ISSUE THREAD

**Issue by BaldEagleX02** [rubyide/vscode-ruby#406]
### Your environment

- `vscode-ruby` version: 0.20.0
- Ruby version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
- Ruby version manager (if any): NO
- VS Code version: 1.29.1 (1.29.1)
- Operating System: MacOS Mojave 10.14.1
- Using language server? NO

### Expected behavior
Debug Ruby code

### Actual behavior
The debugger does not start after loading for a while

I have installed ruby-debug-ide with `sudo gem install ruby-debug-ide
sudo gem install debase`
Then I have started the debugger with this simple configuration: 
`{
            "name": "Debug Local File",
            "type": "Ruby",
            "request": "launch",
            "program": "${file}"
        },`

It seems to be loading but after 5 seconds it stops without printing any error message.

**Comment by MarioRuiz** [comment]
Same on Ubuntu 18.10

**Comment by BaldEagleX02** [comment]
It is working well now but I do not know why. I have not changed anything in the configuration file...

**Comment by BaldEagleX02** [comment]
@MarioRuiz: When your problem is solved I will close this issue

**Comment by MarioRuiz** [comment]
Go ahead, solved

**Comment by dshefchik** [comment]
@BaldEagleX02 I'm dealing with the exact same problem at the moment. Running any debug command with type = Ruby simply exits with no warning or logs after about 3 seconds. I tried re-installing the extension, removing all other extensions, and clearing my workspace cache. Nothing works.

vscode-ruby version: 0.20.0
Ruby version: ruby 2.5.1p57 (2018-10-18 revision 65156) [x86_64-darwin18]
Ruby version manager (if any): NO
VS Code version: 1.29.1 (1.29.1)
Operating System: MacOS High Sierra
Using language server? NO

**Comment by dshefchik** [comment]
I had already installed debase and ruby-debug-ide. When I list my gems, it's showing:

```
Ignoring debase-0.2.3.beta2 because its extensions are not built. Try: gem pristine debase --version 0.2.3.beta2
Ignoring debase-0.2.2 because its extensions are not built. Try: gem pristine debase --version 0.2.2
Ignoring jaro_winkler-1.5.1 because its extensions are not built. Try: gem pristine jaro_winkler --version 1.5.1
Ignoring ruby-debug-ide-0.7.0.beta6 because its extensions are not built. Try: gem pristine ruby-debug-ide --version 0.7.0.beta6
Ignoring ruby-debug-ide-0.7.0.beta3 because its extensions are not built. Try: gem pristine ruby-debug-ide --version 0.7.0.beta3
```
I'm going to try to run gem pristine as indicated and see what happens

**Comment by dshefchik** [comment]
And it worked ^

**Comment by BaldEagleX02** [comment]
:+1:

**Comment by BaldEagleX02** [comment]
I am closing this issue
