### ISSUE TITLE
cant attach rails server

### ISSUE THREAD

**Issue by williamhatch** [rubyide/vscode-ruby#410]
### Your environment

- `vscode-ruby` version: 0.21.0
- Ruby version: 2.3.5
- Ruby version manager (if any): rbenv
- VS Code version: 1.27.1
- Operating System: mac
- Using language server?
```
config: {
			"name": "Debug Attach",
			"type": "Ruby",
			"request": "attach",
			"cwd": "${workspaceRoot}",
			"remoteWorkspaceRoot": "${workspaceRoot}",
			"remoteHost": "127.0.0.1",
			"remotePort": "3000"
		}
```
### Expected behavior
attach the rails (locally running on port 3000)
cant  attach the process,
then I typed in a teminal:
```
rdebug-ide --host 127.0.0.1 --port 3000  --attach-mode   
```                                                                             
/Users/william/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/ruby-debug-ide-0.6.1/bin/rdebug-ide:175:in `<top (required)>': uninitialized constant Debase::MultiProcess (NameError)
Did you mean?  Process
        from /Users/william/.rbenv/versions/2.3.5/bin/rdebug-ide:22:in `load'
        from /Users/william/.rbenv/versions/2.3.5/bin/rdebug-ide:22:in `<main>'

**Comment by wingrunr21** [comment]
This looks like `debase` is missing. Is it available in the same place you've installed `ruby-debug-ide`?

**Comment by williamhatch** [comment]
@wingrunr21 debase is installed as well.

**Comment by williamhatch** [comment]
@wingrunr21 what is the exact steps can be followed to attach a rails app? thanks ;)

**Comment by wingrunr21** [comment]
I don't know as I don't actively use the debugger. Besides the steps in the README do these work for you? https://github.com/Microsoft/vscode-recipes/tree/master/debugging-Ruby-on-Rails

**Comment by williamhatch** [comment]
@wingrunr21 awesome!! it works according to your documents! thanks.

**Comment by wingrunr21** [comment]
Great. Closing this issue then
