### ISSUE TITLE
Extension breaks javascript syntax highlighting

### ISSUE THREAD

**Issue by adam-h** [rubyide/vscode-ruby#411]
### Your environment

- `vscode-ruby` version: 0.21.0
- Ruby version: 2.5.3p105
- Ruby version manager (if any):
- VS Code version: 1.30.0
- Operating System: Arch linux (4.19.8-arch1-1-ARCH)
- Using language server? Tried with and without

### Expected behavior

Opening a javascript file has syntax highlighting

### Actual behavior

No syntax highlighting for javascript, error in vscode console:

```
  ERR Unexpected end of JSON input: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parseJSONGrammar (/opt/visual-studio-code/resources/app/node_modules.asar/vscode-textmate/release/main.js:1583:17)
    at parseRawGrammar (/opt/visual-studio-code/resources/app/node_modules.asar/vscode-textmate/release/main.js:1574:16)
    at file:///opt/visual-studio-code/resources/app/out/vs/workbench/workbench.main.js:4447:803
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Disabling all extensions and enabling just this ruby extension still causes the issue.

![image](https://user-images.githubusercontent.com/604449/49980630-35a1c300-ff8f-11e8-83b2-12d428e9bed6.png)

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*

**Comment by wingrunr21** [comment]
What architecture are you running? I cannot reproduce this on my mac so I'm wondering if it has to do with you being on Arch

**Comment by meddario** [comment]
Does it still happen with only the ruby extension enabled? On my pc (Ubuntu 18.04, vscode 1.29.x/1.30.x) I don't see any issue with JS files highlighting after installing this extension.

**Comment by wingrunr21** [comment]
Interesting. Wonder if something about KDE is the culprit.

**Comment by wingrunr21** [comment]
Ok let me know what you find out. If I get time I’ll throw Arch in a VM and poke at it.
