### ISSUE TITLE
Debugger did work  but now it couldn't work

### ISSUE THREAD

**Issue by Lucius3451** [rubyide/vscode-ruby#414]
### Your environment

- `vscode-ruby` version:0.21.0
- Ruby version:
ruby 2.5.3p105 (2018-10-18 revision 65156)
- Ruby version manager (if any):
- VS Code version:
1.30.0
- Operating System:
WIN 10   1803(OS内部版本17134.471)
架构: Windows_NT x64 10.0.17134
- Using language server?

### Expected behavior
Press F5 and work correctly
### Actual behavior
Press F5 and return error
##ERROR INFORMATION
Uncaught exception: cannot load such file -- C:/Users/Vucius/Desktop/Rubytest/main.rb
	D:/Ruby25-x64/bin/rdebug-ide:23:in `load'
	D:/Ruby25-x64/bin/rdebug-ide:23:in `<main>'
Debugger error: Client: Error: read ECONNRESET
D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:92:in `debug_load': cannot load such file -- C:/Users/Vucius/Desktop/Rubytest/main.rb (LoadError)
	from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:92:in `debug_program'
	from D:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/ruby-debug-ide-0.6.1/bin/rdebug-ide:182:in `<top (required)>'
	from D:/Ruby25-x64/bin/rdebug-ide:23:in `load'
	from D:/Ruby25-x64/bin/rdebug-ide:23:in `<main>'

###Additional Information:
On my launch.json, I use those basic debug configurations. And I choose "Debug Local File" to debug.
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for rdebug-ide",
            "type": "Ruby",
            "request": "attach",
            "cwd": "${workspaceRoot}",
            "remoteHost": "127.0.0.1",
            "remotePort": "1234",
            "remoteWorkspaceRoot": "${workspaceRoot}"
        },
        {
            "name": "Rails server",
            "type": "Ruby",
            "request": "launch",
            "program": "${workspaceRoot}/bin/rails",
            "args": [
                "server"
            ]
        },
        {
            "name": "RSpec - all",
            "type": "Ruby",
            "request": "launch",
            "program": "${workspaceRoot}/bin/rspec",
            "args": [
                "-I",
                "${workspaceRoot}"
            ]
        },
        {
            "name": "RSpec - active spec file only",
            "type": "Ruby",
            "request": "launch",
            "program": "${workspaceRoot}/bin/rspec",
            "args": [
                "-I",
                "${workspaceRoot}",
                "${file}"
            ]
        },
        {
            "name": "Debug Local File",
            "type": "Ruby",
            "request": "launch",
            "program": "${workspaceRoot}/main.rb"
        },
        {
            "name": "Cucumber",
            "type": "Ruby",
            "request": "launch",
            "program": "${workspaceRoot}/bin/cucumber"
        },
    ]
}
And I think I should give my tasks.json
{
    "version": "2.0.0",
    "tasks": [
		{
			//"label": "Ruby dbg",
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "always"
				//"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*

**Comment by Lucius3451** [comment]
And a extra question:
I couldn't see issues#404(I remember that is about debuger)
it is a pity that I couldn't reference it anymore.
I'm a noob on ruby and vscode, so...how I can get imformation about "debug ruby on vscode"

**Comment by Lucius3451** [comment]
solved

**Comment by vaibhavsingh97** [comment]
@Lucius3451 How you solved the issue? can you please help me out?

**Comment by Lucius3451** [comment]
@vaibhavsingh97  if u mean ` Client: Error: read ECONNRESET`
Reference this: https://github.com/rubyide/vscode-ruby/issues/214
