### ISSUE TITLE
Running debugger should respect ruby virtual envs like rvm

### ISSUE THREAD

**Issue by efagerberg** [rubyide/vscode-ruby#418]
### Your environment

- `vscode-ruby` version: 0.21.0
- Ruby version: 2.2.8p477 (2017-09-14 revision 59906) [x86_64-darwin17]
- Ruby version manager (if any): rvm
- VS Code version: 1.30.1
- Operating System:maxOS High Sierra Version 10.13.6
- Using language server?
- rvm 1.29.4 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

### Expected behavior

When running debug configurations, the extension knows which is the user's active ruby environment from their folder.

### Actual behavior

Running the debug configuration does not appropriately load rvm scripts like ```[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*``` resulting in a ruby mismatch when trying to run the debugger.

This script is in my bash configurations files `.profile` `.bash_profile` `.bashrc`

*Debug Console Error*
```Uncaught exception: Your Ruby version is 2.5.1, but your Gemfile specified 2.2.8
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:496:in `validate_ruby!'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:471:in `validate_runtime!'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:101:in `setup'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	/Users/efagerberg/workspaces/yesware/Backend/bin/rspec:15:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.5.1/bin/rdebug-ide:23:in `load'
	/usr/local/rvm/gems/ruby-2.5.1/bin/rdebug-ide:23:in `<main>'
	/usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	/usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
/usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:496:in `validate_ruby!': Your Ruby version is 2.5.1, but your Gemfile specified 2.2.8 (Bundler::RubyVersionMismatch)
	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/definition.rb:471:in `validate_runtime!'
	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler.rb:101:in `setup'
	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/bundler/setup.rb:20:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/efagerberg/workspaces/yesware/Backend/bin/rspec:15:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:92:in `debug_load'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/ruby-debug-ide-0.6.1/lib/ruby-debug-ide.rb:92:in `debug_program'
	from /usr/local/rvm/gems/ruby-2.5.1/gems/ruby-debug-ide-0.6.1/bin/rdebug-ide:182:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.5.1/bin/rdebug-ide:23:in `load'
	from /usr/local/rvm/gems/ruby-2.5.1/bin/rdebug-ide:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `eval'
	from /usr/local/rvm/gems/ruby-2.5.1/bin/ruby_executable_hooks:24:in `<main>'
```

This seems like a known problem for this extensions as some docs suggest setting the rvm default to the one in your workspace. However, doing so is pretty tedious and only a work around. The workaround also for myself does not work.

I am not sure how this extension handles running configurations, if it does so in a bash login session or not, but it feels like it is not respecting the virtual ruby environments in the current context of the workspace. This unfortunately led to me having to download rubymine which handles rvm environments. However I really like using vscode and would love if the debugger for ruby could also handle this scenerio.

**Comment by wingrunr21** [comment]
Combining with #316
