### ISSUE TITLE
Separate styles for variable signs (@, @@ and $)

### ISSUE THREAD

**Issue by vizakenjack** [rubyide/vscode-ruby#420]
### Your environment

- `vscode-ruby` version: 0.21.0
- Ruby version: 2.5.3
- Ruby version manager (if any): rbenv
- VS Code version: 1.30.2
- Operating System: OS X 10.14.2
- Using language server? yes

### Expected behavior

I have tried to make my custom theme, but I haven't found a way to create different colors for a sign before the variable. I only found "punctuation.definition.variable.ruby" which is the same for all signs.

### Actual behavior

<img width="355" alt="screen" src="https://user-images.githubusercontent.com/91447/51419725-c0349e00-1b9d-11e9-9569-e65cb7f4052d.png">

It looks like this. Is there a way to change a color of $ sign?

**Comment by wingrunr21** [comment]
Probably not. It'd need to get a standalone scope to get targeted by the theming engine.
