### ISSUE TITLE
Ruby usually missing from debug add configuration

### ISSUE THREAD

**Issue by abraham** [rubyide/vscode-ruby#421]
### Your environment

- `vscode-ruby` version: 0.19.1
- Ruby version: 2.6.0
- Ruby version manager (if any): chruby 0.3.9
- VS Code version: 1.30.2
- Operating System: Ubuntu 18.10
- Using language server? yes

### Expected behavior

When I open the debugger sidebar and select "add configuration" "Ruby" should be a listed as an option.

### Actual behavior

When I go to add a configuration, "ruby" is not a listed environment. I've seen "Ruby" as an available selection for a few minutes earlier today and it's been there in previous weeks. I opened Code's developer tools and I didn't see any errors that looked related (there are errors from git and setting sync sometimes).

![screenshot from 2019-01-19 13-08-59](https://user-images.githubusercontent.com/3341/51431279-3f50c300-1bec-11e9-935f-8b4337f5cd61.png)

**Comment by klyonov** [comment]
I have the same problem but I haven't seen Ruby as available environment at all since installing it in VS Code. Again there are no errors in Problems window.
Windows 10 1809
Ruby 2.6.0p0 (2018-12-25 revision 66547) [x64-mingw32]
VS Code 1.30.2

**Comment by ptorrsmith** [comment]
Same issue, ruby not showing.   Though got it working... see below

![image](https://user-images.githubusercontent.com/17134063/70094953-7440f980-1688-11ea-8a49-8c11ab0abacf.png)

Hit "more" and takes me to an Extensions Marketplace panel with "tag:debuggers @sort:installs" preset.... but I have Ruby extension installed.
![image](https://user-images.githubusercontent.com/17134063/70094988-86229c80-1688-11ea-8be1-d7e2ee359fe9.png)

Uninstalled all extensions locally except "Remote - WSL".  Then re-added extensions required (see https://www.endpoint.com/blog/2019/04/04/rails-development-in-windows-10-pro-with-visual-studio-code-and-wsl)... at least Ruby... but made sure I selected "install WSL Remote" button, not "Install".  Did the reloads, but didn't help. Rebooted machine, then reopened VSCode and found the "Ruby" option shows in the New Configuration options.
Hope that helps.

**Comment by jawspeak** [comment]
I just had this problem, but it was (my) own user error. I didn't have a ruby file open in the editor, and unless I did it wouldn't show the ruby environment. Maybe this helps someone else.
