### ISSUE TITLE
Attach to subprocesses automatically

### ISSUE THREAD

**Issue by jmaroeder** [rubyide/vscode-ruby#424]
### Your environment

- `vscode-ruby` version: 0.21.0
- Ruby version: 2.5.3p105
- Ruby version manager (if any): asdf
- VS Code version: 1.30.2
- Operating System: OS X
- Using language server? No

### Expected behavior

When I launch a debugging instance, the debugger should auto attach to any child processes that are spawned.

### Actual behavior

Only the first process is attached to.

Example:

- Install the `rerun` Gem
- Put the following in `launch.json`:
```json
        {
            "name": "Rerun Test",
            "type": "Ruby",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}/bin/rerun",
            "args": [
                "--background",
                "--",
                "${workspaceRoot}/lib/mycode.rb"
            ],
            "showDebuggerOutput": true
        }
```
- Set a breakpoint in `mycode.rb`
- Start the debugger - it will run through the code as normal, but not stop at the breakpoint

#235 originally proposed this feature, but was cleaned up.

**Comment by kschoelhorn** [comment]
I think this would be useful addition. In more complex applications, you rarely start the actual ruby script you may want to debug directly, there are usually wrappers and start scripts.
