### ISSUE TITLE
server initialization failed

### ISSUE THREAD

**Issue by ckruse** [rubyide/vscode-ruby#425]
### Your environment

- `vscode-ruby` version: 0.21.0
- Ruby version: 2.6.1p33
- Ruby version manager (if any): rbenv
- VS Code version: 1.31.0
- Operating System: macOS
- Using language server? yes

### Expected behavior

proper startup

### Actual behavior

After the recent VSCode update I get the following error:

~~~
[Error - 7:54:49 AM] Server initialization failed.
  Message: Request initialize failed with message: No prebuilt binaries found (target=undefined runtime=undefined arch=undefined platform=undefined)
  Code: -32603 
~~~

**Comment by meddario** [comment]
Same also with rvm ruby version manager.

**Comment by compostbrain** [comment]
i use asdf for ruby version management and I'm getting this same error.

**Comment by abraham** [comment]
Same with `chruby: 0.3.9` on Ubuntu 18.10

**Comment by wingrunr21** [comment]
This is related to VSCode 1.31 upgrading Electron. I'll push a new version with the upgraded binaries

**Comment by wingrunr21** [comment]
Closing as dup of #415
