### ISSUE TITLE
Rubocop Formatting Doesn't Work Unless Installed At System-Level Ruby

### ISSUE THREAD

**Issue by ecbrodie** [rubyide/vscode-ruby#427]
I'm running yet again into IMO the most problematic part of this VSCode extension: **Rubocop Formatting**

### Your environment

- `vscode-ruby` version: 0.21.1
- Ruby version: 2.6.1
- Ruby version manager (if any): RVM
- VS Code version: 1.31.1
- Operating System: MacOS 
- Using language server? No (although I don't think it matters for this issue)

### Expected behavior

VSCode-Ruby should be able to detect the `rubocop` executable installed for the Ruby version of the current project's Ruby version. For example, if the contents of my `.ruby-version` file is like so:

```
2.6.1
```

Then VSCode-Ruby should be considering the installed gems for this Ruby version when looking for Rubocop. That means, it should be irrelevant whether I have Rubocop installed for my system-level Ruby installation. As long as I have run `gem install rubocop` (or `bundle install` on a project that has Rubocop specified in its `Gemfile`), then I should be fine.

### Actual behavior

VSCode-Ruby Rubocop formatting will only work if I ran `gem install rubocop` on my system-level Ruby (in my case, the Ruby 2.3.7 default installation for MacOS). It's as if VSCode-Ruby is running a `which rubocop` command against the system-level Ruby version and not on the project-specific Ruby version.

**NOTE:** I don't think this is a 100% reproducible bug. Perhaps 75% reproducible. I usually run into problems with Rubocop formatting when I don't have Rubocop installed on my system-level Ruby installation, but not on every single VSCode session.

Let me know if you need any more information. Thank you.

**Comment by wingrunr21** [comment]
All of this will be fixed via #405
