### ISSUE TITLE
Upgrading From 0.21.0 to 0.21.1 Breaks Highlighting

### ISSUE THREAD

**Issue by coby-spotim** [rubyide/vscode-ruby#429]
### Your environment

- `vscode-ruby` version: 0.21.1
- Ruby version: 2.3.1
- Ruby version manager (if any): rvm-1.29.4
- VS Code version: 1.31.1
- Operating System: macOS Mojave 10.14.3
- Using language server? No

### Expected behavior

The syntax highlighting should work, colouring and highlighting the code appropriately.

### Actual behavior

Before updating to the latest version, the highlighting of my Ruby file looked like this (version 0.21.0): 

![image](https://user-images.githubusercontent.com/41164052/52915863-b8bdfd00-32e1-11e9-9690-e54c6dee6d00.png)

After updating to the latest version, the highlighting and colours all disappeared (version 0.21.1):

![image](https://user-images.githubusercontent.com/41164052/52916101-41d63380-32e4-11e9-8a36-9305daced3a8.png)

**Comment by wingrunr21** [comment]
Are there any logs? I haven't seen this and I run this extension across multiple machines. There also weren't any changes between `0.21.0` and `0.21.1` which would cause this.

**Comment by coby-spotim** [comment]
I'm seeing in the `Log (Window)` Output pane the following errors:
```
[renderer5] [error] Unable to load and parse grammar for scope source.ruby from file:///Users/coby/.vscode/extensions/rebornix.ruby-0.21.1/syntaxes/ruby.cson.json

[renderer5] [error] No grammar provided for <source.ruby: Error: No grammar provided for <source.ruby
    at Registry.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:3583:39)
    at step (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:3511:23)
    at Object.next (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:3492:53)
    at fulfilled (/Applications/Visual Studio Code.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js:3483:58)
```

**Comment by coby-spotim** [comment]
@wingrunr21 These were the errors I'm seeing when using the latest version (0.21.1) however when using the earlier version (0.21.0) I see no error. Is there an extra install that has to happen or setting that has to be configured to load the grammar?

**Comment by wingrunr21** [comment]
No, it's automatic. I think you may have a bad download. Have you tried reinstalling the extension?

**Comment by wingrunr21** [comment]
The extension should be downloaded to `~/.vsCode/extensions/rebornix.ruby-0.21.1`. You can check the `syntaxes` directory to see if `ruby.cson.json` is there.

I just downloaded it off the marketplace and checked that syntax. It's in the extension and `jq` is happy with the JSON format.

**Comment by coby-spotim** [comment]
It looks like you are right, the `syntaxes` and `snippets` directories didn't even exist in the new version's directory, although I saw them in the old version.

I tried uninstalling it and reinstalling it multiple times, but the uninstall task doesn't actually remove the files for some reason, so the full fix is to uninstall the extension, make sure that the directory of the version that you uninstalled is deleted and if it isn't, manually delete it, and then reinstall to force a re-download of the files.

**Comment by wingrunr21** [comment]
Ok great. Not sure why that happened but good to know on the uninstall. Is your issue resolved?

**Comment by coby-spotim** [comment]
Yup! Closing now, thanks!
