### ISSUE TITLE
Language server crashes when linters other than reek or rubocop are enabled

### ISSUE THREAD

**Issue by pelletencate** [rubyide/vscode-ruby#437]
### Your environment

- `vscode-ruby` version: `0.22.1`
- Ruby version: `2.6.0`
- Ruby version manager (if any): `rvm`
- VS Code version: `1.31.1`
- Operating System: `macOS 10.14.3`
- Using language server? `yes`

### Steps to reproduce
Enable language server, use this config:

```
        "ruby.lint": {
            "reek": true,
            "rubocop": {
                "lint": true,
                "rails": true
            },
            "ruby": {
                "unicode": true,
            },
            "fasterer": true,
            "debride": true,
            "ruby-lint": true
        },
```

### Expected behavior

Server runs fine and only uses supported linters

### Actual behavior

Server crashes:

```
TypeError: LINTER_MAP[name] is not a constructor
    at getLinter (/Users/pelle/.vscode/extensions/rebornix.ruby-0.22.1/server/out/Linter.js:24:12)
[...]
```

A little investigation shows that LINTER only has 'rubocop' and 'reek' in there. See https://github.com/rubyide/vscode-ruby/blob/master/server/src/Linter.ts#L15.

**Comment by wingrunr21** [comment]
This is the same as #435

**Comment by wingrunr21** [comment]
I'm going to leave this open as the tracking ticket for this as the other issue has diverged a bit. Long story short, yes it's a bug I need to fix.

Also, in the language server, I am only supporting reek, rubocop, and standard for linting. The other linters will not be supported there. Removing those from your config for the time being will fix the problem.

**Comment by wingrunr21** [comment]
`v0.22.2` should fix this
