### ISSUE TITLE
language server crash on startup - Windows

### ISSUE THREAD

**Issue by clxy** [rubyide/vscode-ruby#438]
### Your environment

- `vscode-ruby` version: 0.22.2
- Ruby version: * ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]
- Ruby version manager (if any): NONE
- VS Code version: 1.3.1
- Operating System:  6.1.7601 Service Pack 1 ビルド 7601 x64
- Using language server? yes

### Requested by @wingrunr21 
- Using `cmd.exe`, PowerShell, or bash? cmd
- How do you have Ruby installed? RubyInstaller
- Is it in your system `PATH`? In my `PATH`, It's in my User Environment Variables path.
- How do you manage multiple versions of Ruby? Just one version

### Expected behavior
Working language server

### Actual behavior
The language server crashes with below error messages 

````
[Info  - 10:05:37] Initializing Ruby language server...
[Info  - 10:05:37] Rebuilding tree-sitter for local Electron version
[Info  - 10:05:38] Rebuild succeeded!
c:\Users\s37120.MICTOKYO\.vscode\extensions\rebornix.ruby-0.22.2\server\node_modules\rxjs\internal\util\hostReportError.js:4
    setTimeout(function () { throw err; });
                             ^

Error: Request workspace/rubyEnvironment failed with message: Command failed: C:\Users\s37120.MICTOKYO\.vscode\extensions\rebornix.ruby-0.22.2\client\out\util\shims\env.cmd.exe
'C:\Windows\system32\cmd.exe -i' This verison of this file is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need an x86 (32-bit) or x64 (64-bit) verion of the program...

    at handleResponse (c:\Users\s37120.MICTOKYO\.vscode\extensions\rebornix.ruby-0.22.2\server\node_modules\vscode-jsonrpc\lib\main.js:436:48)
    at processMessageQueue (c:\Users\s37120.MICTOKYO\.vscode\extensions\rebornix.ruby-0.22.2\server\node_modules\vscode-jsonrpc\lib\main.js:263:17)
    at Immediate.setImmediate (c:\Users\s37120.MICTOKYO\.vscode\extensions\rebornix.ruby-0.22.2\server\node_modules\vscode-jsonrpc\lib\main.js:247:13)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
[Info  - 10:05:39] Connection to server got closed. Server will restart.
````

**Comment by bgmat** [comment]
Hi,

I have the same issue since version upgraded to 0.22.2
OS Windows 10
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
vscode 1.31.1

### Info Requested by @wingrunr21
* Using `cmd.exe`, PowerShell, or bash? cmd
* How do you have Ruby installed? RubyInstaller
* Is it in your system `PATH`? Yes, In my `PATH`
* How do you manage multiple versions of Ruby? Just one version

**Comment by wingrunr21** [comment]
Great, thank you both. I will address this ASAP

**Comment by wingrunr21** [comment]
v0.22.3 has the bugfix for this
