### ISSUE TITLE
Improve display for debug console

### ISSUE THREAD

**Issue by FranklinYu** [rubyide/vscode-ruby#439]
This is a feature request and should probably be linked from #316.

It would be awesome if we can have better UI for [debug console](https://code.visualstudio.com/docs/editor/debugging#_debug-console-repl) return value. Current return value is string (which probably came out of `#inspect`). From the VS Code documentation page, we see beautiful UI for such tree-like structure.

**Comment by wingrunr21** [comment]
Updated in #316
