### ISSUE TITLE
Opening output window every time I save a file

### ISSUE THREAD

**Issue by stephenson** [rubyide/vscode-ruby#446]
### Your environment

- `vscode-ruby` version: 0.22.2
- Ruby version: 2.4.2
- Ruby version manager (if any): RVM
- VS Code version: 1.31.1
- Operating System: Mac OS
- Using language server? No

### Actual behavior

Every time I save a file VS Code will open the Output window and hide my terminal. I disabled all extensions until I diagnosed it was vscode-ruby that did it.

**Comment by wingrunr21** [comment]
Is there any output? What is your plugin config? Does the output window open even if it is collapsed (eg not on the terminal or that bottom area is not visible)?

**Comment by stephenson** [comment]
Yes output is:
<img width="986" alt="screen shot 2019-03-05 at 19 01 15" src="https://user-images.githubusercontent.com/60150/53826590-3851fa00-3f79-11e9-8e5b-7a75d69b7010.png">

I have not changed any configs, so standard. 

Yes it opens even if all terminals and output windows are collapsed.

**Comment by wingrunr21** [comment]
That screenshot has language server output in it. That is not enabled by default. Please post your config.

**Comment by wingrunr21** [comment]
I am guessing this is happening because the format command is failing (thus the 127 error code). The output window is opening up because of that error being returned by the language server.

**Comment by stephenson** [comment]
<img width="766" alt="screen shot 2019-03-05 at 21 14 03" src="https://user-images.githubusercontent.com/60150/53834559-a1426d80-3f8b-11e9-9c84-6833582ad3b3.png">
