### ISSUE TITLE
auto-indent issue with Ruby syntax

### ISSUE THREAD

**Issue by chriskacerguis** [rubyide/vscode-ruby#45]
### Your environment
- `vscode-ruby` version: 0.5.2
- Ruby version: 2.2.3
- VS Code version: 1.4.0
- Operating System: Mac OS X 10.11.6 (15G31)
- Hardware (optional): 15" MacBook Pro Retina
### Expected behavior

When coding in Ruby, there seems to be an issue with the auto-indent.  What I expect to have

``` ruby
def test_foo
  if cond == true
    p 'hello'
  end
end
```
### Actual behavior

This is the code that I get

``` ruby
def test_foo
if cond == true
p 'hello'
end
end
```
### Steps to reproduce the problem
1. Create a new file (set language to "Ruby")
2. Type the following: "def test_foo" (press enter) -> no auto-tab
3. Type "if cond == true" (press enter) -> no auto-tab
4. Type "p 'hello'"
5. Type "end" (press enter) -> You will note here, that the "end" does not auto-align with the "if"
6. Type "end" (press enter) -> again, same thing, end should be aligned with the "def"

**Comment by HookyQR** [comment]
Hi @chriskacerguis. decreaseIndentPattern won't solve your problem, it's only job is to un-indent the end for already indented code.

The code you should get (assuming you dont't un-indent manually) is:
```ruby
def test_foo
  if cond == true
    p 'hello'
    end
  end
```

Note that the `end`s don't automatically un-indent. My guess is your settings are a little bit off and I'm expecting your `"editor.tabSize"` is not set correctly. For ruby, this is generally set to `2`. Check your workspace (if you have one) and user settings files.

This doesn't rely on any additional packages being installed, so I would be very surprised if it's not a setting problem.

**Comment by odarriba** [comment]
Same problem here. Any work around?

**Comment by HookyQR** [comment]
Not really. There are snippets in the extension that will give you the blocks, but I don't use them either.

We've just included code formatting in the last release. You'll have to have rubocop installed for it to work though. That _should_ fix your un-indenting after the fact.

There are other languages with the same problem, so vs code _may_ give us a fix one day. Ask @rebornix nicely, he contributes to the main vscode repo. 😉

**Comment by HookyQR** [comment]
Are either of you still having problems with the auto indent still (except the non-un-indenting end)?

**Comment by chriskacerguis** [comment]
As of today, yes I'm still having the problem. (Latest stable VS code, latest Ruby plugin)

**Comment by jclay** [comment]
Same issue here. Did anyone find a suitable workaround?

**Comment by HookyQR** [comment]
Hey @jclay, @chriskacerguis, @odarriba. I'm going to close this issue as it references some very old versions. I'm running on MacOS (as well) and I'm not experiencing any of the problems that are listed here (excluding the non-un-indenting `end`), and I don't see any settings that would cause this to be a problem. If you're still experiencing issues with indenting, can you please raise another issues with an example of it not working.

Sorry for the stuff around.

**Comment by betam4x** [comment]
@HookyQR please reopen, this is definitely still an issue.  Tested on Windows 10 and the latest versions of VS code and this plugin.

**Comment by andrewmartin** [comment]
+1

**Comment by Thadeu** [comment]
+1

**Comment by askarhu** [comment]
This seem to be still an issue in 2019!
