### ISSUE TITLE
Language server spawning reek/rubocop processes without setting env

### ISSUE THREAD

**Issue by edmund** [rubyide/vscode-ruby#453]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: 2.6.2
- Ruby version manager (if any): none
- VS Code version: 1.32.2
- Operating System: Ubuntu 18.10
- Using language server? yes

### Expected behavior

Reek and rubocop should work with language server enabled.

### Actual behavior

Reek and rubocop fail with `/usr/bin/env: 'ruby': No such file or directory`, from the output tab.  Both work fine with the language server disabled.

I dug into it a little and found that it's because the spawned processes have no environment variables set.  Adding `console.info('this.config:', this.config);` to server/out/linters/BaseLinter.js:28 gives me:
```
[Info  - 14:21:34] Initializing Ruby language server...
[Info  - 14:21:34] Rebuilding tree-sitter for local Electron version
[Info  - 14:21:34] Rebuild succeeded!
Lint: executing reek -f json...
this.config: { env: {}, executionRoot: '/home/edmund/test', config: {} }
Lint: executing rubocop -s /home/edmund/test/test.rb -f json...
this.config: { env: {}, executionRoot: '/home/edmund/test', config: {} }
Lint: Received invalid JSON from reek:

/usr/bin/env: 'ruby': No such file or directory

Lint: Received invalid JSON from rubocop:

/usr/bin/env: 'ruby': No such file or directory
```

Adding `this.config.env.PATH = process.env.PATH; this.config.env.HOME = process.env.HOME;` to BaseLinter.js:28 resolves the problem, rubocop and reek both work fine with the language server.

This also affects the formatter, in the same way (Format Document seemed to work, but not Format Selected), with the same fix.

### Single files

The above happens when opening a directory - opening a single file gives a slightly different result:

```
[Info  - 14:43:58] Initializing Ruby language server...
[Info  - 14:43:58] Rebuilding tree-sitter for local Electron version
[Info  - 14:43:58] Rebuild succeeded!
Lint: executing reek -f json...
this.config: { env: undefined, executionRoot: 'undefined', config: {} }
Lint: executing rubocop -s /home/edmund/test/test.rb -f json...
this.config: { env: undefined, executionRoot: 'undefined', config: {} }
Lint: unable to execute /usr/local/ruby/bin/reek -f json as the command could not be found
Lint: unable to execute /usr/local/ruby/bin/rubocop -s /home/edmund/test/test.rb -f json as the command could not be found
Lint: Received invalid JSON from reek:


Lint: Received invalid JSON from rubocop
```
Note that `this.config.env` is undefined, while `this.config.executionRoot` is the string 'undefined'.

`this.config.executionRoot = process.env.HOME;` resolves the single file issue, despite env being undefined.

### Quick fix

I'm not at all familiar with Typescript, so I can't say what the root issue is or file a PR.  But I was able to get it working by bodging the .js files in the vscode extension.  

For now, I've added this to `~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/linters/BaseLinter.js`, just under line 27 (`console.info('Lint: executing...`) and `~/.vscode/extensions/rebornix.ruby-0.22.3/server/out/formatters/BaseFormatter.js`, just under line 36 (`console.info('Format: executing...`):
```
        if (this.config.executionRoot == 'undefined') {
            this.config.executionRoot = process.env.HOME;
        }
        this.config.env = {};
        this.config.env.PATH = process.env.PATH;
        this.config.env.HOME = process.env.HOME;
```

After restarting vscode, rubocop and reek work with the language server enabled, in both folders and single files.

No idea why this is only affecting me - not aware of anything particularly unusual about my system.  Removing ~/.config/Code and ~/.vscode made no difference.

**Comment by wingrunr21** [comment]
Sorry, but that's not a fix and will actually break the new environment detection functionality.

`process.env` does not always have the appropriate `PATH` and `HOME` variables as people do not always start VSCode from the command line. In addition, tools like `chruby` and `rbenv` can mutate the environment in order to support multiple versions.

How do you have Ruby installed? The language server spawns a login shell to inherit the appropriate environment variables. It appears there's something wrong with that process (which is why you are not seeing anything in the environment).

**Comment by edmund** [comment]
> Sorry, but that's not a fix and will actually break the new environment detection functionality.

Well - it fixes it for me!  Not suggesting that this is an improvement, I was just investigating what was causing my problem and found a workaround.

> How do you have Ruby installed?

No chruby, rvm, rbenv or anything else that affects the environment.

I use ruby-build to install to `/usr/local/ruby` (so ruby itself is `/usr/local/ruby/bin/ruby`), with `/usr/local/ruby/bin` added to the path in `/etc/environment`  Everything else works fine, including vscode-ruby without the language server.

>  The language server spawns a login shell to inherit the appropriate environment variables. It appears there's something wrong with that process (which is why you are not seeing anything in the environment).

Am I right in thinking that the issue is with the empty /undefined values in `this.config`? Or should the spawned processes be inheriting the environment from vscode or something?  Apologies if this is obvious, TS/JS really isn't my thing.

There's clearly something slightly weird about my setup that's causing it - would appreciate any ideas about what else I could check.

**Comment by wingrunr21** [comment]
If you spawn an interactive login shell and look at the environment exported (via `export`), do all of the variables look right?

**Comment by edmund** [comment]
> If you spawn an interactive login shell and look at the environment exported (via export), do all of the variables look right?

... OK - so now I know that spawning an interactive login shell (with `su - <username>`) on Ubuntu doesn't use `/etc/environment` for the base `$PATH`, but rather `/etc/login.defs`, which I'd never heard of before.  Thank you for pointing me in the right direction!

With that resolved, rubocop now works when opening a directory.  However, opening a single file still gives the same error, presumably because `this.config.executionRoot` is still `'undefined'`.  Commenting out the cwd line in the spawn parameters fixes this for single files, and doesn't affect opening directories.

**Comment by edmund** [comment]
Also - not sure if this is related, but it feels like the same kind of area.  Happy to open a new issue if it's a separate thing.

I'm getting an error in the vscode developer console, the first time a ruby file is opened.  Doesn't happen when opening a single file, only a directory.

```
[Extension Host] /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:272
bash: cannot set terminal process group (3027): Inappropriate ioctl for device
bash: no job control in this shell
```

The bash error lines are both in the same entry.  It sometimes points at `console.ts:134` instead of `workbench.main.js:272`, no obvious pattern.  I would have assumed it was something to do with vscode itself, but it doesn't happen without vscode-ruby installed, and then only when opening a .rb file. 

Disabling everything - code completion, formatting, intellisense, linters - makes no difference, but disabling the language server does prevent it.  Nothing unexpected in the output tab.

Something isn't happy about not having a TTY, by the looks of it.  Doesn't appear to be doing any harm.

**Comment by wingrunr21** [comment]
The language server spawns a TTY within the working directory of the file (either the workspace or otherwise) so that it can figure out the Ruby environment. Nearly all of the Ruby version managers expose their APIs as functions within an interactive login shell so the only way to figure out the correct ruby version, gemset, whatever is to spawn a shell and `cd` to the correct directory.

There appears to be something specific with your setup that is causing this. I've got an Ubuntu test VM that I use to troubleshoot thing on Linux and I haven't run across this issue. I also was using a version manager there though.
