### ISSUE TITLE
RuboCop works as linter and fails as formatter (on one project only)

### ISSUE THREAD

**Issue by MikeMcQuaid** [rubyide/vscode-ruby#458]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: 2.5.2/multiple
- Ruby version manager (if any): rbenv/none
- VS Code version: 1.32.3
- Operating System: macOS Mojave
- Using language server? yes

### Expected behavior

On all projects if RuboCop works as a linter it works as a formatter.

### Actual behavior

See `Format: executing rubocop -s` output as expected but RuboCop error code of 2 is returned:

<img width="701" alt="Screenshot 2019-03-18 at 10 58 41" src="https://user-images.githubusercontent.com/125011/54525779-de840380-496c-11e9-9f67-72a0e3300a91.png">

If I add `console.log`s around the code I can see the output of the formatter is as expected and it doesn't note any error code. If I run the command manually I don't see any errors.

---

As this is specific to a single project I'm working on (e.g. it doesn't happen when I'm working on Homebrew) this issue is perhaps more "how can I get additional debugging information/error output" rather than "there is an issue for you to fix here".

Thanks for all your great work on this project and for your contributions to the open source community @wingrunr21 and all: you all rock ❤️

**Comment by wingrunr21** [comment]
Hi,

Looks like you've already done the initial debug step I ask for (run the command manually). Would you be able to paste any part of the output and/or the RuboCop configuration? Also, when running manually, do you still get a `0` or `1` exit code?

Exit code 2 normally means an exception or error occurred within RuboCop itself. It is possible RuboCop has streamed the output to `stdout` and then encounters an error. The way the code works the `stdout` will be captured and processed but if a non `0` or `1` exit code is encountered it will alert VSCode that the command failed.

I'm curious what's causing this problem!

**Comment by MikeMcQuaid** [comment]
> Would you be able to paste any part of the output and/or the RuboCop configuration? 

Sure: 
```console
$ ./bin/rubocop /Users/mike/GitHub/github/app/models/user.rb -a && echo success
Inspecting 1 file
.

1 file inspected, no offenses detected
success
```

> Also, when running manually, do you still get a `0` or `1` exit code?

`0`.

> It is possible RuboCop has streamed the output to `stdout` and then encounters an error. The way the code works the `stdout` will be captured and processed but if a non `0` or `1` exit code is encountered it will alert VSCode that the command failed.

Gotcha. Is it possible somehow (even if it involves modifying the vscode-ruby JS code locally) to output any additional error output to a log somewhere?

I was able to use `console.log` in https://github.com/rubyide/vscode-ruby/blob/2d8e443a33bb56662fe3ad23d2b049b52021acb7/server/src/formatters/RuboCop.ts#L19-L24 to output the command output to the log and it all looked as expected (same output as above but with the appended contents of the file too due to the `-s` usage).

**Comment by wingrunr21** [comment]
Can you run rubocop with `stdin` and see if it also returns 0? Rubocop behaves slightly differently in `stdin` mode so want to verify that.

`cat /Users/mike/GitHub/github/app/models/user.rb | ./bin/rubocop  -s user.rb -a`

In terms of additional diagnostics;

`processResults` is all of the output that comes back from the command line. `stderr` and `stdout` are merged into a single output stream so you should get both back in that output.

`processError` will run when a non-0 or non-1 exit code is returned.

The command is constructed [here](https://github.com/rubyide/vscode-ruby/blob/master/server/src/linters/RuboCop.ts#L52) so you could pass additional flags to Rubocop (like the `-d` debug flag) to maybe make it more verbose.

**Comment by MikeMcQuaid** [comment]
> Can you run rubocop with `stdin` and see if it also returns 0? Rubocop behaves slightly differently in `stdin` mode so want to verify that.

Yup, still getting the same `0` exit code. Weird!

> The command is constructed [here](https://github.com/rubyide/vscode-ruby/blob/master/server/src/linters/RuboCop.ts#L52) so you could pass additional flags to Rubocop (like the `-d` debug flag) to maybe make it more verbose.

Just to make sure we're on the same page: it's in language server mode and only the formatter that fails. The linter behaves as expected.

When I log in`processError` in https://github.com/rubyide/vscode-ruby/blob/2d8e443a33bb56662fe3ad23d2b049b52021acb7/server/src/formatters/RuboCop.ts#L26-L30 and https://github.com/rubyide/vscode-ruby/blob/2d8e443a33bb56662fe3ad23d2b049b52021acb7/server/src/formatters/BaseFormatter.ts#L129-L135 I never see any output in my `failed with code=2` case but do see it if there's an exit code of `1`. Looking at the message it's coming from https://github.com/rubyide/vscode-ruby/blob/2d8e443a33bb56662fe3ad23d2b049b52021acb7/src/format/RuboCop.ts#L126: does this mean it's using different a different format code path in this/some cases? That's helped me figure out my issue which is that this is not using the same/correct RuboCop binary as the linter for some reason.

When I add this to my workspace settings it works as expected:
```
  "ruby.lint": {
    "rubocop": {
      "exe": "/Users/mike/GitHub/github/bin/rubocop"
    }
  },
```

I'm still a bit confused as to why the linting doesn't require this but the formatting does but I have my issue resolved for now.

Happy to keep this open or have it closed based on your preferences. Equally, happy to answer any questions and provide any more debugging information that would be useful or needed.

**Comment by MikeMcQuaid** [comment]
To be specific what exactly helped be debug: adding `vscode.window.showErrorMessage(`rubocop failed with code=${data}`);` to `rubo.stderr.on('data', data => {` let me see what the exact error was which pointed me to the fact it was using the wrong `rubocop` binary.

**Comment by MikeMcQuaid** [comment]
Closing as this is resolved (but now affected by https://github.com/rubyide/vscode-ruby/issues/460 😅). Thanks again @wingrunr21!
