### ISSUE TITLE
How does this plugin really work

### ISSUE THREAD

**Issue by guledali** [rubyide/vscode-ruby#464]
So I have installed this plugin from https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby

How can I tell that it works is there? Is there some additional steps that I need to take other than installing. 

Do  I have to use it together with https://marketplace.visualstudio.com/items?itemName=castwide.solargraph to notice some difference?

**Comment by wingrunr21** [comment]
The README details getting this plugin running.

You do not need to use Solargraph alongside it but I would recommend it as Solargraph provides a lot of good additional functionality that this extension does not provide at this time.

**Comment by guledali** [comment]
@wingrunr21 It would be nice if this plugin could work without having to configure stuff. 
DX(developer experience) is really important for me and I like my stuff to work **out-of-box**.

**Comment by wingrunr21** [comment]
Thank you for the feedback but some stuff is impossible to work **out of the box**. How do you suggest we ship a Ruby interpreter?  How do we handle individuals with multiple version requirements? How do we handle linting?

The Ruby grammar and other passive features work out of the box.
