### ISSUE TITLE
Provided formatter is named 'Ruby', makes it hard to distinguish between formatters

### ISSUE THREAD

**Issue by connorshea** [rubyide/vscode-ruby#467]
### Your environment

- `vscode-ruby` version: 0.22.3 
- Ruby version: `2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]`
- Ruby version manager (if any): rbenv 1.1.2
- VS Code version: 1.33.0
- Operating System: macOS 10.14.4
- Using language server? Yes

### Expected behavior

The formatter provided by this extension should have an obvious name, e.g. `VSCode Ruby` or `Rubocop`.

### Actual behavior

The formatter name is `Ruby`, which is also what another formatter I have installed is called (I'm not sure which other extension I have installed provides a formatter for Ruby, unfortunately. I have Solargraph installed but disabled.). This makes it pretty confusing what formatter I should be using.

<img width="621" alt="Screen Shot 2019-04-07 at 6 20 49 PM" src="https://user-images.githubusercontent.com/2977353/55694256-99059580-5970-11e9-9f71-57fd510ebf63.png">

VS Code 1.33.0 added a feature where you can pick which formatter should be used when multiple are registered for the same file type, which is why this was never relevant before.

### Settings
These are my relevant settings:

```json
"ruby.format": "rubocop",
"ruby.lint": {
    "rubocop": true
},
"ruby.useLanguageServer": true,
"[ruby]": {
    "editor.formatOnSave": true
 }
```

**Comment by connorshea** [comment]
Actually, after choosing between the two it seems like they're both from this extension. Either way I do it, both of them end up with this in the `settings.json`:

```json
"[ruby]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "rebornix.ruby"
}
```

You can trigger this problem by opening any Ruby file with VSCode 1.33 and then running `Format Document`. I assume the formatter is being registered twice somehow?

**Comment by connorshea** [comment]
Also I just noticed this commit, which might have already fixed this problem? cb03f63b8444a02e16184a93c8e51c0ed855872a

**Comment by wingrunr21** [comment]
That is likely what is causing the duplicate, yes.

In terms of the name, VSCode uses the name of the extension ([which is `Ruby`](https://github.com/rubyide/vscode-ruby/blob/master/package.json#L2-L3))

**Comment by connorshea** [comment]
To make the source of the formatter more clear, I opened [a PR in VS Code](https://github.com/Microsoft/vscode/pull/71910) to display the extension ID as well, so I'll close this issue.
