### ISSUE TITLE
Sorry, but there is no formatter for 'ruby'-files installed.

### ISSUE THREAD

**Issue by rezamarandi** [rubyide/vscode-ruby#469]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
- Ruby version manager (if any): chruby
- Operating System: macOS High Sierra
- VS Code version: 1.33.1
- Using language server? Yes

### VSCode config
```
// Ruby Configs
    "ruby.format": "rubocop",
    "editor.formatOnSaveTimeout": 1000,
    "ruby.codeCompletion": "rcodetools",
    "ruby.intellisense": "rubyLocate",
    "ruby.lint": {
        "rubocop": true,
        "ruby": true,
        "ruby-lint": true
    },
```
### Expected behavior
I can use rubocop to do formatting

### Actual behavior
I get the `sorry, but there is no formatter for 'ruby'-files installed.

Everything was working alright until i updated ruby on project into latest version with chruby and removed rbenv
i already have .rubocop.yml in the root of project directory

```
R3za-MBPro:Codebase r3za$ ruby -v
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
R3za-MBPro:Codebase r3za$ gem list | grep rubocop
rubocop (0.67.2, 0.58.1)
rubocop-performance (1.1.0)
R3za-MBPro:Codebase r3za$ rubocop -v
0.67.2
R3za-MBPro:Codebase r3za$ 
```

**Comment by wingrunr21** [comment]
The aspects of the Github issue template that you omitted are there for a reason.

What is your configuration? Are you using the language server?

**Comment by rezamarandi** [comment]
> The aspects of the Github issue template that you omitted are there for a reason.
> 
> What is your configuration? Are you using the language server?
I update the issue .. how can i debug whats happening here ?

**Comment by chioi** [comment]
Same issue here
### Enviroment
- `vscode-ruby` version: 0.22.3
- `ruby` version: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
- `rvm`
- macOS Mojave version 10.14.4
- Visual Studio Code version 1.33.1

### VSC config
```
{
   "ruby.format": "rubocop",
    "ruby.codeCompletion": "rcodetools",
    "ruby.intellisense": "rubyLocate",
    "ruby.lint": {
        "rubocop": true,
        "ruby": true
    },
    "editor.formatOnSave": true,
    "editor.formatOnPaste": true,
    "editor.formatOnSaveTimeout": 1500,
    "ruby.useBundler": true,
    "ruby.useLanguageServer": true,
}
```

```
$ gem list | grep rubocop
rubocop (0.69.0)
```

**Comment by minkir014** [comment]
For a temporary solution there's a Rubocop extension which doesn't' have these problems.
https://marketplace.visualstudio.com/items?itemName=misogi.ruby-rubocop

**Comment by wingrunr21** [comment]
@rezamarandi what is the language server logging?

@chioi You have `useBundler` set to true but `rubocop` installed globally. The language server logs what it is trying to run.

@minkir014 it has the exact same issues. That extension relies on the user starting VSCode up with the correct environment already loaded.

**Comment by choosen** [comment]
```
    "ruby.useBundler": true,
    "ruby.useLanguageServer": true,
```
solved me same problem

**Comment by andyw8** [comment]
A tip for anyone running into this: You may need to restart VS Code after changing the config.
