### ISSUE TITLE
Calling a class method renders a Constant in code outline

### ISSUE THREAD

**Issue by jtgrenz** [rubyide/vscode-ruby#473]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version:2.6.2
- Ruby version manager (if any): chruby
- VS Code version: Version 1.33.1 (1.33.1)
- Operating System: MacOS 10.14.4 (Mojave)
- Using language server? yes

### Expected behavior

The outline displays Modules, Classes, Constants and Methods with is great. However, I expect it to show Constants that are declared, not classes called.

### Actual behavior

Constant declared and called:
[![alt](https://screenshot.click/25-02-epis3-x4du5.jpg)](https://screenshot.click/25-02-epis3-x4du5.jpg)

[![alt](https://screenshot.click/25-04-fkqmv-h8fw1.jpg)](https://screenshot.click/25-04-fkqmv-h8fw1.jpg)

Class method called inside another method
[![alt](https://screenshot.click/25-05-kfepj-g6nas.jpg)](https://screenshot.click/25-05-kfepj-g6nas.jpg)

[![alt](https://screenshot.click/25-06-2lybj-8uzak.jpg)](https://screenshot.click/25-06-2lybj-8uzak.jpg)

**Comment by wingrunr21** [comment]
Hmm, interesting. Are you using `rubyLocate` as well?

I'll take a look at this. It's also technically reporting the wrong constant there.

**Comment by jtgrenz** [comment]
It looks like. My settings.json is set to

```json
 "ruby.locate": {
        "exclude": "{**/@(test|spec|tmp|.*),**/@(test|spec|tmp|.*)/**,**/*_spec.rb}",
        "include": "**/*.rb"
    },
```

**Comment by wingrunr21** [comment]
Ok cool thanks for the information.
