### ISSUE TITLE
can you please add atom editor version?

### ISSUE THREAD

**Issue by FlowerWrong** [rubyide/vscode-ruby#475]
### Your environment

- `vscode-ruby` version: no
- Ruby version: 2.6.3
- Ruby version manager (if any): rbenv instead
- VS Code version: no
- Operating System: darwin
- Using language server? no

### Expected behavior

atom editor support

**Comment by wingrunr21** [comment]
Can you elaborate here? What feature are you looking for that Atom does not provide? There's a pretty rich Ruby ecosystem in Atom already
