### ISSUE TITLE
Remote debugger does not honor value of remoteWorkspaceRoot

### ISSUE THREAD

**Issue by the-vk** [rubyide/vscode-ruby#476]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
- Ruby version manager (if any): none
- VS Code version: 1.33.1
- ruby-debug-ide version: 0.6.1
- debase version: 0.2.2
- Dev machine Operating System: dev machine: Windows 8.1
- Debug machine: 
uname -a
Linux 92e88cab8f65 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
- Using language server? Yes

### Steps to repro

1. Setup launch configuration to attach
```
{
  "name": "attach to remote",
  "type": "Ruby",
  "request": "attach",
  "cwd": "${workspaceRoot}",
  "remoteHost": "123.123.123.123",
  "remotePort": "23456",
  "remoteWorkspaceRoot": "/nano-ci",
}
```
2. Run script on remote Linux machine with redebug-ide
3. Open VS Code at workspace e:\work\nano-ci
3. Attach debugger using configuration "attach to remote"
3. Set breakpoint

### Expected behavior

Debugger rewrites path to file using cwd and remoteWorkspaceRoot when making a request to set a breakpoint.

### Actual behavior

Path to file is not changed; breakpoint does not work.

Output of redebug-ide from remote machine when started with key -d

1: Processing in control: break e:\work\nano-ci\lib\nanoci\build_scheduler.rb:226
1: \<breakpointAdded no="4" location="e:\work\nano-ci\lib\nanoci\build_scheduler.rb:226"/>

I expect path to be "/nano-ci/lib/nanoci/build_scheduler.rb:226"

The setup was working fine sometime ago (about a month or so).

**Comment by wingrunr21** [comment]
Dup of #316

**Comment by minkir014** [comment]
Instructions say that you must open the workspace you want in vscode and start debugging it.
I mean run the project on another computer and open the root in vscode in your local machine that might work.
