### ISSUE TITLE
broken bracket matching with inline if/unless

### ISSUE THREAD

**Issue by matkoniecz** [rubyide/vscode-ruby#484]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: `ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-linux-gnu]`
- Ruby version manager (if any): none
- VS Code version:  1.33.1
- Operating System: Ubuntu 16.04
- Using language server? I am not aware that I am using one, I use default settings

### Expected behavior

Bracket matching works for 

```
if a < b
  next if a == b

  puts a
end
```

### Actual behavior

![Selection_003](https://user-images.githubusercontent.com/899988/57966383-624c7300-7951-11e9-9ed9-c19c2d43dce4.png)

**Comment by wingrunr21** [comment]
Please enable the language server (see the README) and see if this is still an issue. Balanced pair matching was one of issues specifically addressed (also in the README).

**Comment by matkoniecz** [comment]
After enabling language server (that was disabled by default) it works.
