### ISSUE TITLE
HEREDOC syntax issues

### ISSUE THREAD

**Issue by Wuerfel21** [rubyide/vscode-ruby#485]
### Your environment

- `vscode-ruby` version: 0.22.3
- Ruby version: 2.5
- Ruby version manager (if any):
- VS Code version: 1.33.1
- Operating System: Windows 7 64 bit
- Using language server? not sure

### Expected behavior
Correct syntax highlighting of HEREDOCS.

### Actual behavior
All text that follows on the same line after a HEREDOC is treated as a string literal. (Issue #183 was already filed about this, but inexplicably got closed). Even worse, when there are multiple HEREDOCS on one line, only the first one's contents are recognized as a string literal.
![image](https://user-images.githubusercontent.com/6944842/58183537-ce134080-7caf-11e9-8379-d55a4596aae5.png)

**Comment by wingrunr21** [comment]
It inexplicably got closed because of stale issue clean up (which was clearly posted in the issue).

Can you please post what TM Scopes the grammar is matching for the offending syntax? `Developer: Inspect TM Scopes` tool in the command palette.

**Comment by Wuerfel21** [comment]
For what token in particular? (I get a popup that displays a lot of info about the token under the cursor)
I think it'd make more sense for you to paste the code into an editor yourself:
```ruby
p(<<~'SOMETEXT' , <<~OTHERTEXT, Time.now)
    test1 if unless else "foorbar"
SOMETEXT
    test2 if unless else "foobar"
OTHERTEXT
```
(GitHub has the same broken highlighting, nice)

**Comment by minkir014** [comment]
It maybe a problem with vs code. See this might help you solve the issue.
https://stackoverflow.com/questions/55614584/syntax-highlighting-of-vs-code-broken-with-heredoc

**Comment by wingrunr21** [comment]
@Wuerfel21 I think @minkir014 is right. The highlighting is based on older heredoc syntax.

When VSCode lands semantic highlighting support (meaning I can highlight based on the AST and not grammar regexes) this will be fixable. Otherwise, we'll need a fix pushed to the upstream [atom/language-ruby](https://github.com/atom/language-ruby) grammar and I can pull it in.

**Comment by amerov** [comment]
This bug comes from vscode https://github.com/microsoft/vscode/issues/62812

**Comment by amerov** [comment]
I played with this tree-sitter extension https://github.com/georgewfraser/vscode-tree-sitter it is ok with heredoc.

**Comment by wingrunr21** [comment]
It doesn’t support themes. If you are ok with its static theming the its an option. I also use tree sitter so when VSCode exposes the APIs to support TextMate scopes I can support this the same way
