### ISSUE TITLE
Run VS Code with admin privileges so the changes can be applied.

### ISSUE THREAD

**Issue by Yukaii** [rubyide/vscode-ruby#49]
### Your environment

- `vscode-ruby` version: 0.5.3
- Ruby version: 2.3.1
- VS Code version: 1.4.0
- Operating System: macOS El Capitan
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

Autocomplete

### Actual behavior

After install the latest vscode-ruby, autocomplete doesn't show any result, and get a error info:

```
Run VS Code with admin privileges so the changes can be applied.
```

![screen shot 2016-08-27 at 8 41 25 am](https://cloud.githubusercontent.com/assets/4230968/18023914/740c7e98-6c32-11e6-8454-00913497b35a.png)

After restarting VSCode or reinstall the extension, the problem still remains.

When I use `sudo code` to run VSCode, the autocomplete **works**, but VSCode itself warns me not to run it in root mode.

**Comment by dlanileonardo** [comment]
I have the same problem:

Ubuntu: 15.10

Erro Backtrace:

**Comment by Yukaii** [comment]
I found this is related to ruby installation way.

I use rbenv and ruby is installed under user directory (`/Users/username/.rbenv/shims/` on macOS)

After switching to system ruby and install `rcodetools` gem, this issue seems to be resolved.

```bash
su -
gem install rcodetools
```

However I think it's not a **clean** workaround.

**Comment by orta** [comment]
I wonder if this can be fixed by these config variables: https://github.com/rubyide/vscode-ruby/pull/50/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R81

That let you use the path for ruby & rct-complete

**Comment by Yukaii** [comment]
@orta It works! Thanks.
