### ISSUE TITLE
LANG env variable needed for proper Rufo formatting

### ISSUE THREAD

**Issue by pmk1c** [rubyide/vscode-ruby#493]
### Your environment

- `vscode-ruby` version: 0.23.0
- Ruby version: 2.4.6
- Ruby version manager (if any): asdf
- VS Code version: 1.35.1 
- Operating System: Fedora Linux
- Using language server? (eg `useLanguageServer` is true?) yes

### Expected behavior

Formatting Ruby files with rufo as formatter should work if the file contains multibyte utf8 characters like `"“”"`

### Actual behavior

It gives an error:

```
Format: executing rufo --filename=/path/to/file.rb -x...
[Error - 11:12:15] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: 
    unable to execute rufo --filename=/path/to/file.rb -x:
    Error: Failed with exit code: 1 - unknown error
  Code: -32603 
```

When running Rufo with the same arguments in the command line on the file content, it works:

```
cat /path/to/file.rb | rufo --filename=/path/to/file.rb -x
```

 When running the same command with the `LANG` env variable unset an error occurs:

```
LANG= cat /path/to/file.rb | rufo --filename=/path/to/file.rb -x
# Error: ./path/to/file.rb has syntax errors
```

So the reason seems to be, that the `LANG` environment variable is not set to something with utf8 support like `C.UTF-8`.

**Comment by minkir014** [comment]
I think it's problem with environment not the extension.

**Comment by pmk1c** [comment]
Since my environment declares `LANG` I think this is a problem with the language server.

I understood this code as if there was some kind of ENV Whitelist? https://github.com/rubyide/vscode-ruby/blob/master/client/src/util/env.ts#L82

But I maybe wrong.

**Comment by minkir014** [comment]
You must add arguments that set `LANG` variable that may work

**Comment by pmk1c** [comment]
I changed the extension's code to see if my guesses were true. And it did help solve the issue for me.

So here's the PR: #494 

I don't see a reason not to pass the host's `LANG` env variable along. So I think this should be a quite unobtrusive change.

**Comment by wingrunr21** [comment]
Yes, that's an ENV whitelist. It's there to demonstrate I'm not pulling in potentially sensitive variables (like `AWS_` stuff).
