### ISSUE TITLE
Incorrect ERB syntax highlighting when used inside HTML tags

### ISSUE THREAD

**Issue by mabras** [rubyide/vscode-ruby#498]
### Your environment

- `vscode-ruby` version:
0.23.0
- Ruby version:
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin18]
- Ruby version manager (if any):
rbenv 1.1.2
- VS Code version:
Version 1.35.1 (1.35.1)
- Operating System:
macOS
- Using language server?
No

### Expected behavior
Valid erb syntax
### Actual behavior
Invalid erb syntax

This what I get when I try to write dynamic attribute inside html opening tag:

<img width="426" alt="Screenshot 2019-06-26 at 8 01 49 PM" src="https://user-images.githubusercontent.com/9248917/60200139-2c52b680-984e-11e9-9950-b8b98319a9d2.png">

**Comment by wingrunr21** [comment]
What language has VSCode detected that file as (lower right corner)?

**Comment by mabras** [comment]
erb
