### ISSUE TITLE
language server crashing on latest vscode

### ISSUE THREAD

**Issue by paranoidaditya** [rubyide/vscode-ruby#502]
### Your environment

- `vscode-ruby` version: `0.24.0`
- Ruby version:  `2.6.3` 
- Ruby version manager (if any): `chruby`
- VS Code version: `Version 1.36.0 (1.36.0)`
- Operating System: `macOS Mojave 10.14.5 (18F132)`
- Using language server? `Yes`

### Expected behavior

Should start up

### Actual behavior

```
[Info  - 3:33:07 PM] Initializing Ruby language server...
[Info  - 3:33:07 PM] Rebuilding tree-sitter for local Electron version
[Error - 3:33:07 PM] Server initialization failed.
  Message: Request initialize failed with message: No prebuilt binaries found (target=undefined runtime=undefined arch=undefined libc=undefined platform=undefined)
  Code: -32603 
```

**Comment by kascote** [comment]
the last vscode is using node v69 and the last tree-sitter-ruby is against v64 and isn't founding the url to download:

https://github.com/tree-sitter/tree-sitter-ruby/releases/download/v0.15.0/tree-sitter-ruby-v0.15.0-electron-v69-linux-x64.tar.gz

we have to wait to tree-sitter-ruby generate a new release in that case ?

btw: the last message with undefined values, seems related to ```prebuildInstall.download``` 
https://github.com/rubyide/vscode-ruby/blob/master/server/src/util/rebuilder.ts#L38

isn't sending all the data to show the error: 
https://github.com/prebuild/prebuild-install/blob/04be92d2ead6459741e0fb64cc44735f6c2fa519/download.js#L66

**Comment by wingrunr21** [comment]
This is known and we already have a PR upstream to fix it.

If you have build tooling installed on your system you can perform the following:

```bash
cd ~/.vscode/extensions/rebornix.ruby-0.24.0/server
npm install
```

That should trigger prebuild to build the binary

**Comment by wingrunr21** [comment]
I'm closing this as this is a dup of #486

**Comment by yyyc514** [comment]
```
% npm install                                              2.6.3
added 389 packages from 755 contributors and audited 1925 packages in 6.016s
found 0 vulnerabilities
```

This didn't fix the issue though.  Guess I'll wait for an upstream fix?

**Comment by wingrunr21** [comment]
`v0.24.1` was just published with the updated binaries
