### ISSUE TITLE
Language server fails VS Code v1.36.0

### ISSUE THREAD

**Issue by raywagner88** [rubyide/vscode-ruby#503]
### Your environment

- `vscode-ruby` version: 0.24.0
- Ruby version: 2.3.8
- Ruby version manager (if any): rvm
- VS Code version: 1.36.0
- Operating System: MacOS 10.14.5
- Using language server? (eg `useLanguageServer` is true?) yes

### Expected behavior
I expect the language server to initialize and run in the latest version of VS Code.
### Actual behavior
Server initialization fails

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*
```
[Info  - 10:45:31 AM] Initializing Ruby language server...
[Info  - 10:45:31 AM] Rebuilding tree-sitter for local Electron version
[Error - 10:45:32 AM] Server initialization failed.
  Message: Request initialize failed with message: No prebuilt binaries found (target=undefined runtime=undefined arch=undefined libc=undefined platform=undefined)
  Code: -32603 
```

**Comment by minkir014** [comment]
Dublicate #486

**Comment by wingrunr21** [comment]
Agreed. I will push on upstream to get that PR merged so I can get this addressed.
