### ISSUE TITLE
Migrate tree-sitter and tree-sitter-ruby to WASM distribution

### ISSUE THREAD

**Issue by wingrunr21** [rubyide/vscode-ruby#506]
Move `tree-sitter` and `tree-sitter-ruby` to use a WASM build instead of prebuilt binaries. This should yield a better user experience + allow us to drop `prebuild`.

More info [here](https://github.com/tree-sitter/tree-sitter/pull/321)

**Comment by wingrunr21** [comment]
WASM support was started over the weekend. Just need to test a few things out and verify the solution works cross-platform. VSCode does not officially support WASM in extensions so want to make sure this is functioning as expected.

**Comment by Razzeee** [comment]
Btw just FYI, here's another VSCode addon that has been shipping wasm tree sitter files for some time now https://github.com/georgewfraser/vscode-tree-sitter/tree/master/parsers

**Comment by wingrunr21** [comment]
https://github.com/rubyide/vscode-ruby/tree/tree_sitter_wasm ;-)

**Comment by Razzeee** [comment]
> VSCode does not officially support WASM in extensions so want to make sure this is functioning as expected.
Just meant to mention that due to that, especially as I'm interested in your findings there. Might have implications for my LS implementation.

**Comment by minkir014** [comment]
When do you intend to fully convert prepuilt binaries to WASM to solve problems of prebuilt binaries instead of fixing node-tree-sitter problems since the PR against node-tree-sitter has some problems.

**Comment by wingrunr21** [comment]
@Razzeee Ya, I think support works in practice but https://github.com/Microsoft/vscode/issues/65559. Luckily, the way `tree-sitter` is built the appropriate member functions for memory management can be defined in the types it ships vs those from the WASM spec or emscripten

@minkir014 ASAP

**Comment by minkir014** [comment]
Have you encountered any problems with WASM or it's working properly??

**Comment by wingrunr21** [comment]
This change is in `master`. It will go out with the next release.

**Comment by minkir014** [comment]
When will WASM version of the extension go out??
Maybe, this will help to fix all issues.

**Comment by wingrunr21** [comment]
This was shipped in v0.25.0. There was an issue with publishing that version to the Marketplace so v0.25.1 is the first version with the WASM switch.
