### ISSUE TITLE
Ruby language server fails to start with error 'dyld: lazy symbol binding failed: Symbol not found:'

### ISSUE THREAD

**Issue by devopskatas** [rubyide/vscode-ruby#511]
### Your Environment

- `vscode-ruby` version: 0.24.1
- Ruby version: 2.6.3p62
- Ruby version manager (if any): rbenv 1.1.2
- VS Code version: 1.35.1
- Operating System: Mac OSX Mojave
- Using language server? (eg `useLanguageServer` is true?)  yes/true

### Expected behavior
Ruby language server starts successfully on VS Code startup

### Actual behavior
Ruby language server fails to start with this error:

```
[Info  - 10:54:05 AM] Initializing Ruby language server...
[Info  - 10:54:05 AM] Rebuilding tree-sitter for local Electron version
[Info  - 10:54:05 AM] Rebuild succeeded!
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/ds063137/.vscode/extensions/rebornix.ruby-0.24.1/server/node_modules/tree-sitter-ruby/build/Release/tree_sitter_ruby_binding.node
  Expected in: flat namespace
```

The language server attempts to start five times, then VS Code raises the "toast" notification at the bottom right that, saying it failed five times in three minutes and will not be restarted.

**Comment by devopskatas** [comment]
Turns out I had the VS Code app file in Downloads.  Moved that to the Applications folder, now I'm getting this: 

```
[Info  - 11:25:53 AM] Initializing Ruby language server...
[Info  - 11:25:53 AM] Rebuilding tree-sitter for local Electron version
[Error - 11:25:54 AM] Server initialization failed.
  Message: Request initialize failed with message: No prebuilt binaries found (target=undefined runtime=undefined arch=undefined libc=undefined platform=undefined)
  Code: -32603
```

I've read the issues related to this error, supposedly it is fixed but I'm still getting this error on the latest versions of all relevant components.

**Comment by wingrunr21** [comment]
Dup of #486
