### ISSUE TITLE
Cannot find module 'ruby-method-locate'

### ISSUE THREAD

**Issue by rpbaltazar** [rubyide/vscode-ruby#513]
### Your environment

- `vscode-ruby` version: 0.24.2
- Ruby version: 2.6.3
- Ruby version manager (if any): rbenv
- VS Code version: 1.36.1
- Operating System: OsX
- Using language server? (eg `useLanguageServer` is true?)

### Expected behavior

Extension to load properly

### Actual behavior

Extension fails to load

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*

I've loaded the developer tools and it is throwing an error when trying to load the extension:

`Cannot find module 'ruby-method-locate'`

which halts the loading. This leads to the syntax highlighting to be broken as well.

**Comment by wingrunr21** [comment]
This is a known issue. Syntax highlighting likely breaks as the extension is failing to load (which would include the grammars).

The extension has been migrated to using webpack as a bundler (now in `master`) so the next release should resolve this. I do not have an ETA on this as there are a few other things I want to get into the next release.

**Comment by wingrunr21** [comment]
This was corrected in v0.25.0. There was an issue with publishing that version to the Marketplace so v0.25.1 is the first version with the WASM switch.
