### ISSUE TITLE
Issues not being able to step through code in ruby debugger VSCode

### ISSUE THREAD

**Issue by mskogen** [rubyide/vscode-ruby#517]
### Your environment
- `vscode-ruby` version: 0.24.2
- Ruby version: 2.5x and 2.6x builds
- VS Code version: (User Install) x64 1.37.0
- Operating System: Windows 10

### Expected behavior
When using ruby debugger (gem ruby-debug-ide) and debugging from a local file, I can set a break-point on a script and then step line-by-line on the script and see how the code functions. If there are multiple breakpoints in the script it should stop at each of those breakpoints before continuing running the rest of the code.
 
### Actual behavior
When I set the breakpoint on the script, the vscode debugger stops at the breakpoint with everything populated up to that point, but then when I try to step into the next line of code the rest of the script completes without stepping and finished the script. This will happen even if I set multiple breakpoints in the script and it stops on the first breakpoint and then when I click the step into and/or step over button it completes the remainder of the script without even stopping at the next break points.

**Comment by mskogen** [comment]
This issue has been occurring for me since the afternoon of 8/6/2019 which it looks like the travis-ci build has been failing from build #653 and higher https://travis-ci.org/rubyide/vscode-ruby/builds

**Comment by mskogen** [comment]
Upon looking into the issue further, it seems like the issue may be with the latest version of the gem 'debase'.

**Comment by Sabutobi** [comment]
I had the same issue. Try to set up debugger in another way. Maybe that will be helpful.. Link to solution - https://www.endpoint.com/blog/2019/04/04/rails-development-in-windows-10-pro-with-visual-studio-code-and-wsl

**Comment by DerekZiemba** [comment]
Which alternative debugger are you using to fix this? sabutobi's link does not have a fix, it just talks about normal setup.

I have the same issue, but worse. It initially was just the issue described. Now if I hit a breakpoint, code will never continue from there. It also does not show any variables or let me run expressions in the console. After hitting a breaking, I have to restart everything over. Right now, I have no debugging basically. 

Tried ruby 2.5.7 and 2.6.5. Tried latest debase and rdebug-ide and also the preview versions. Last time I remember it working was ruby 2.5.3. I'm going to try older versions of everything later today
