### ISSUE TITLE
Goto Definition / Intellisense not working in 0.25.1

### ISSUE THREAD

**Issue by klueless-io** [rubyide/vscode-ruby#525]
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

- `vscode-ruby` version:
- Ruby version: 2.5.3
- Ruby version manager (if any): rbenv 1.1.2
 VS Code version:  1.37.1
- Operating System: Mac Mojave 10.14.6
Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	Intel Core i7

- Using language server? (eg `useLanguageServer` is true?)
NO - False

### Actual behavior

1. Go to Definition
2. No definition found for 'method_or_class_name'

### Extra

I tried re-installing visual code studio from scratch and still have this problem

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*

![image](https://user-images.githubusercontent.com/2956762/64101911-3646e780-cdb2-11e9-954f-ba1dc0b9b455.png)

![image](https://user-images.githubusercontent.com/2956762/64101979-54ace300-cdb2-11e9-9f62-c539b803426e.png)

**Comment by wingrunr21** [comment]
What version of the extension are you using? Are you using `rcodetools` or `Solargraph` for these features?

**Comment by saimageshvar** [comment]
I updated this extension today and I am also facing the same issue. 
Version - 0.25.1

**Comment by minkir014** [comment]
Is the setting `useLanguageServer` is set to true or No?

**Comment by chronustdd** [comment]
> Is the setting `useLanguageServer` set to true or No?

Mine is set to false and it was working good before this update

**Comment by wingrunr21** [comment]
What is everyone's `ruby.intellisense` setting?

**Comment by byczkowskip** [comment]
I have the same problem, after update intellisense not working.

**Comment by wingrunr21** [comment]
Hi everyone,

I would like everyone to stop for a second and imagine you are getting a bug report like the ones you are giving me right now. No additional information provided except "it doesn't work anymore". How would you feel about such reports?

Now, I need everyone to tell me two things:

1. Are you using the internal language server?
2. What is your intellisense setting?

**Comment by byczkowskip** [comment]
![Capture](https://user-images.githubusercontent.com/11057069/64171318-a7d67280-ce52-11e9-94e1-de37050caaf6.PNG)
![Capture2](https://user-images.githubusercontent.com/11057069/64171320-a86f0900-ce52-11e9-872c-27cf529eaf27.PNG)

**Comment by wingrunr21** [comment]
@byczkowskip thanks, appreciate it

**Comment by wingrunr21** [comment]
`v0.25.2` is going out with a fix

**Comment by wingrunr21** [comment]
Should be published. Please let me know if it does not resolve your issue

**Comment by klueless-io** [comment]
Resolved for me, thanks

**Comment by pmcnano** [comment]
Question. I see referrences to version 0.25.2 and I see the last version is 0.27.0 however in my extension marketplace I only see version 0.25.0.

I actually downloaded the 0.27.0 extension and manually installed and it did not solve my issues. 

Am I missing something? Thanks
