### ISSUE TITLE
Improve variable syntax grammar

### ISSUE THREAD

**Issue by amerov** [rubyide/vscode-ruby#527]
- `vscode-ruby` version: 1.37.1
- Ruby version: 2.5.5
- Ruby version manager: rvm
- VS Code version: 1.37.1
- Operating System: Linux Mint

### Expected behavior
Highlight variables correctly
### Actual behavior
if variable name is matching the method name from `Kernel` or `Object`  grammar scope is a method. 
![Screenshot from 2019-09-04 00-17-50](https://user-images.githubusercontent.com/196747/64202360-65408480-ceaa-11e9-82b6-5c82a41f88a2.png)

**Comment by wingrunr21** [comment]
Your theme just doesn't target the more specific scope so the theming engine falls back to `support.function`. You can see that a more specific TM scope is still applied.

**Comment by amerov** [comment]
@wingrunr21 
![Screenshot from 2019-09-04 23-51-13](https://user-images.githubusercontent.com/196747/64282456-e7927c80-cf6e-11e9-8ffc-3566284b9e60.png)

**Comment by wingrunr21** [comment]
The grammar [already identifies keywords as being a part of `Kernel`](https://github.com/rubyide/vscode-ruby/blob/master/syntaxes/ruby.cson.json#L241). You can see that in your original screenshot as the token has a theming scope of `support.function.kernel.ruby`. However, your theme _does not_ specify a specific theming option for that scope. So, the VSCode theming engine falls back to using `support.function`. Your theme thus applies the same color.

To "fix" this you should add an entry for the `support.function.kernel.ruby` theme scope with the color of your choice. [This documentation](https://code.visualstudio.com/docs/getstarted/themes#_customizing-a-color-theme) details the user settings to do that.

Another option would be to switch that to be under the `keyword` namespace, but I'd love to see what you propose the new scope should be.

**Comment by amerov** [comment]
I am not about theme support.
I want to highlighting `exit = SomeClass.new` as a regular variable. cos it is not calling global method.

**Comment by wingrunr21** [comment]
That is currently not possible. Highlighting is performed via regular expressions. There is no insight into the actual context the Ruby code is running within. Semantic highlighting is a feature the VSCode team is looking into shipping but do not have a timeline. Until that happens, this isn't something that I can support without completely overriding a user's theme.

**Comment by wingrunr21** [comment]
Closing as this is not currently actionable
