### ISSUE TITLE
It is not recognizing 'ext install Ruby' so it is not installing

### ISSUE THREAD

**Issue by rkentmc** [rubyide/vscode-ruby#53]
### Your environment

- `vscode-ruby` version: 1.4 not installing
- Ruby version: 2.3
- VS Code version: 1.4
- Operating System: El Capitan
- Hardware (optional): Macs

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

**Comment by orta** [comment]
Please follow the steps in this PR instead: https://github.com/rubyide/vscode-ruby/pull/54/files
