### ISSUE TITLE
Confused, just need some guidance

### ISSUE THREAD

**Issue by mattpker** [rubyide/vscode-ruby#530]
Hey @wingrunr21,

First I just want to thank you on the work on this extension!

I just have some questions that I find a little confusing, and it may just be that I have started using this extension while it seems that it is being converted to a different language server.

Out of the box it did not seem like it did much. I read the docs and realized that I need to enable the language server. I did this and I started getting most of the features I am used to, but the Go to/Peek did not seem to be working like it does with my Javascript stuff. From the docs on language-server.md, it says that it should be providing those features I think: "Intellisense support". I ended up getting this working by turning on the "legacy" feature from the legacy.md documentation called "ruby.intellisense": "rubyLocate".

I guess my questions are: 

What features should I have expected from enabling the language server? 
Should the go to/peek have worked with the language server? 
Do I need "ruby.intellisense": "rubyLocate" on for now while the language server is still being developed?
Where is the repo for the language server?
Is there a list of working/not working/todo for the language server?

Adding this sort of docs or FAQ to the README may really help new folks like me that really just don't understand what all I need to enable to get the basic functionality.

Thanks again! Looking forward to your response!

**Comment by wingrunr21** [comment]
Hi @mattpker,

Sorry it's taken me a few days to get back to you.

1. Features are [documented here](https://github.com/rubyide/vscode-ruby/blob/master/docs/language-server.md) for the language server
2. The language server currently supports same-file Document Symbols. This powers the Outline view. Definitions and workspace symbols are not yet supported and thus require `ruby-locate` to enable.
3. This is the repo for the language server. It's a monorepo so the [`packages`](https://github.com/rubyide/vscode-ruby/tree/master/packages) directory contains all sub-packages for the extension
4. Github issues mostly for todo on the extension itself.

There's not documentation on which aspects of the language server protocol the server supports vs not. Definitely something that should be added.

`v1.0` will see the language server enabled by default (although I am heavily considering swapping that constraint earlier). I've been slowly moving older features under the language server umbrella as they are implemented. Notably, workspace wide completion, docs, and goto definition are not yet implemented.

I have purposefully kept the extension settings relatively conservative while I migrate it away from the legacy implementation. This was to avoid breaking people's setups as much as possible. I'm aiming to provide much better "fresh install" settings for the extension for v1.0

From a general roadmap sense, I updated some of the [milestones](https://github.com/rubyide/vscode-ruby/milestones?with_issues=no) to give an idea of what I'm working on. I am really hoping to hit v1.0 by RubyConf this year. We will see.

If there are areas where the documentation can be improved I'd really love contributions there.

**Comment by mattpker** [comment]
@wingrunr21,

Thanks for all the info, makes a lot more sense now!
