### ISSUE TITLE
Rubocop - Parent Lint Error Makes Squiggly Lines for all Children

### ISSUE THREAD

**Issue by cameck** [rubyide/vscode-ruby#535]
### Your environment

- `vscode-ruby` version: 0.25.3
- Ruby version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
- Ruby version manager (if any): rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
- VS Code version: 1.38.1
- Operating System: macOS Mojave 10.14.5 (18F132)
- Using language server? (eg `useLanguageServer` is true?) Yes

### Expected behavior
Errors like `Metrics/ClassLength` or `Metrics/MethodLength` should only do the squiggly line on the Parent for example the class name or method name.
### Actual behavior
If the class-level error or a method-level error is active, every child of that method or class gets a squiggly line. This makes it really hard to read and pinpoint the issue. I don't want to disable these rules, as I find them helpful.

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*
For example:
![Screen Shot 2019-09-18 at 12 03 06 PM](https://user-images.githubusercontent.com/12278390/65178470-a2aa2380-da0d-11e9-96ec-0c1d3bed3554.png)

**Is there a way to customize how this is displayed in the settings?**

I reviewed the linting docs on Rubocop and didn't see anything in this regard.

**Comment by wingrunr21** [comment]
If RuboCop returns that the issue size is the whole file then that’s how it gets displayed.

**Comment by cameck** [comment]
@wingrunr21 Okay gotcha. It sounds like something changed with my rubocop gem then? The reason I ask is that it only started doing this recently.    
Is there a way to customize this from the extension settings or should I dive into Rubcop configs?

**Comment by wingrunr21** [comment]
Support for more accurate reporting of lint errors was introduced recently. It was a fix for zero length RuboCop errors and having those report properly in the editor.

There is not a way to customize this as the lint results are mapped based on the cops feedback

**Comment by cameck** [comment]
Good to know. Thanks for the details and feedback :).
