### ISSUE TITLE
Syntax Highlighting Breaks via Remote-WSL

### ISSUE THREAD

**Issue by ecielam** [rubyide/vscode-ruby#537]
### Your environment

- `vscode-ruby` version: 0.25.3
- Ruby version: 
- Ruby version manager (if any): No
- VS Code version: Latest
- Operating System: Win 10 + WSL
- Using language server? (eg `useLanguageServer` is true?) Yes

### Expected behavior

When I am running locally, syntax highlighting is correct:

![image](https://user-images.githubusercontent.com/1396086/65390335-a215d380-dd12-11e9-80d7-5c243d7b7dbc.png)

### Actual behavior

If I am running via Remote-WSL, syntax highlighting is broken.

![image](https://user-images.githubusercontent.com/1396086/65390373-d4bfcc00-dd12-11e9-80ce-62348f89ca5f.png)

No errors in the language server console.

**Comment by wingrunr21** [comment]
This has been resolved in `v0.26.0`
