### ISSUE TITLE
Ruby syntax recognition for methods with ? or ! at the end

### ISSUE THREAD

**Issue by dnamsons** [rubyide/vscode-ruby#540]
### Expected behavior
For `some_method!` and `some_other_method?` to be recognized as a method by the TextMate grammar upon invocation.
![with highlight](https://user-images.githubusercontent.com/24278257/66068881-117f9480-e557-11e9-8c63-9878d9eb74c0.png)

### Actual behavior
`some_method!` and `some_other_method?` don't get any syntax grammar scopes if there are no arguments specified.
![without highlight](https://user-images.githubusercontent.com/24278257/66068895-180e0c00-e557-11e9-83d6-56ff336985b4.png)

I am willing to add this myself if this is a desirable addition.

**Comment by wingrunr21** [comment]
Yep! Please open a PR!
