### ISSUE TITLE
Code actions for Rubocop warnings

### ISSUE THREAD

**Issue by dnamsons** [rubyide/vscode-ruby#544]
### Expected behavior
To provide quick fixes for some Rubocop cop warnings, for example, `Style/StringLiterals` would provide an option to replace double-quoted strings with single-quoted strings.

Some more info - https://code.visualstudio.com/docs/editor/refactoring#_code-actions-quick-fixes-and-refactorings

### Actual behavior
Currently there are no code actions for Rubocop warnings

<br>
I could take a crack at this, if this seems desirable

**Comment by andrewmcodes** [comment]
Can’t you just run the format command? Otherwise I feel like this would be a welcome addition if you are willing to take a stab at it 😄

**Comment by technicalpickles** [comment]
Formatting is definitely one way to fix the warnings.

Another way is to "fix" is to disable that check using a comment like `# rubocop:disable Style/StringLiterals`, or adding an ignore to .rubocop.yml.

It will depend a lot on the project and warning which is preferred.
