### ISSUE TITLE
Ruby 2.3 squiggly heredoc support

### ISSUE THREAD

**Issue by pRdm** [rubyide/vscode-ruby#545]
There appears to have been regression in the way squiggly heredocs are handled.

Someone has already mentioned this in a closed issue #110 but that appears to have gone unnoticed so I've created a new one here.

### Your environment
- **VS Code version**:
```
Version: 1.38.1
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:31:32.854Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0
```
- **vscode-ruby version**: `0.25.3`
- **Ruby version**: `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin18]`
- **Ruby version manager**: `rvm 1.29.4 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]`
- **Operating System**: `macOS Mojave 10.14.6`
- Using language server? (eg `useLanguageServer` is true?): `false`

### Expected behavior
Quotes inside the heredoc should be recognised as text and not code syntax

![Expected behaviour](https://cloud.githubusercontent.com/assets/823894/21713029/1b4e6860-d3f8-11e6-83d2-bcfc107e8b89.png)

### Actual behavior
Having unbalanced quotes in the heredoc breaks the syntax coloring for the rest of the file.

![Actual behaviour](https://cloud.githubusercontent.com/assets/823894/21713063/53cbaaae-d3f8-11e6-922e-7abfddf3cfeb.png)

**Comment by pRdm** [comment]
My bad, it appears to have been another plugin that was causing the issue. Closing.

**Comment by BradleyJohnson** [comment]
@pRdm Do you happen to recall which plugin was the source of the issue?

**Comment by mdlima** [comment]
In my case, disabling the [Apollo GraphQL Extension](https://marketplace.visualstudio.com/items?itemName=apollographql.vscode-apollo) is what fixed it.
