### ISSUE TITLE
Debugger doesn't start with `rails server`

### ISSUE THREAD

**Issue by nicolasrouanne** [rubyide/vscode-ruby#555]
### Your environment

- `vscode-ruby` version: `0.25.3`
- Ruby version: `2.5.0p0`
- Ruby version manager (if any): `rvm`
- VS Code version: ` 1.39.2`
- Operating System: Mac OS Catalina `10.15 (19A602)`
- Using language server? (eg `useLanguageServer` is true?) No

### Expected behavior
When launching the debugger for `rails server`, it starts the debugger normally.

### Actual behavior
The debugger doesn't start, only the orange bar is displayed and nothing is printed. The **"orange bar"** is displayed and it stalls.

<img width="916" alt="Screenshot 2019-10-30 at 18 06 02" src="https://user-images.githubusercontent.com/12157019/67882933-6c4ee080-fb43-11e9-9ac7-2cffc6d96dff.png">

Interestingly enough:
- it used to work with the same setup a couple of days ago. Didn't update `ruby`, `rails`, `vscode-ide` nor `vscode`. 🤷‍♂ 
- it works fine on a brand new `rails` setup (won't help reproducing 🤦‍♂ )

Here is my configuration
```json
{
      "name": "Rails server",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rails",
      "args": ["server"]
    }
```

When finally stopping the debugger, it prints out the following:
<img width="456" alt="Screenshot 2019-10-30 at 18 06 17" src="https://user-images.githubusercontent.com/12157019/67883104-c2238880-fb43-11e9-9d25-003b6e73f6f5.png">

> I'm ready to make more tests, with different params, to help fix it 🙏

**Comment by karuppasamy** [comment]
I would suggest you to try with the below additional configs,

```
"useBundler": true,
"pathToBundler": "/path/to/rubygem/bin/bundle", // if 'bin/' is not working then replace with 'wrappers'
"pathToRDebugIDE": "/path/to/rubygem/gems/ruby-debug-ide-x.x.x/bin/rdebug-ide"
```

I have documented the rails debugging for the different use cases [here.](https://github.com/microsoft/vscode-recipes/tree/master/debugging-Ruby-on-Rails). I hope it'll useful.

**Comment by erikthered** [comment]
I'm having a similar problem but I'm using the following:

- vscode-ruby version: 0.26.0
- Ruby version: ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-linux]
- Ruby version manager (if any): none
- Rails version: 3.2.22.5
- VS Code version: 1.41.1
- Operating System: Mac OS Catalina 10.15
- Using language server? Yes

However, I am trying run in docker using the devcontainers feature in VS Code. When launching rails using the following:
```json
    {
      "name": "Start Rails server",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rails",
      "args": [
        "server",
        "-p",
        "3000",
      ],
    }
```
the bottom bar briefly flashes orange and the only thing in the debug console is `Fast Debugger (ruby-debug-ide 0.7.0, debase 0.2.4.1, file filtering is supported) listens on 127.0.0.1:1234`.

I also tried running from the Terminal and attaching the debugger using the following command:
`bundle exec rdebug-ide --debug --host 0.0.0.0 --port 1234 -- bin/rails s -p 3000 -b 0.0.0.0` and then attaching with the following:
```json
    {
      "name": "Attach to Debugger",
      "type": "Ruby",
      "request": "attach",
      "cwd": "${workspaceRoot}",
      "remoteHost": "127.0.0.1",
      "remotePort": "1234",
      "remoteWorkspaceRoot": "${workspaceRoot}",
      "showDebuggerOutput": true
    }
```
which pauses here until I attach:
```
Fast Debugger (ruby-debug-ide 0.7.0, debase 0.2.4.1, file filtering is supported) listens on 0.0.0.0:1234
```
and after attaching I see these lines and then the debugger dies in VS Code:
```
Connected from 127.0.0.1
24583: Starting control thread
24583: Processing in control: catch off
24583: Processing in control: start
24583: Starting: running program script
```
After these lines WEBrick and Rails start.

If this should go into a separate issue please do let me know.

**Comment by nicolasrouanne** [comment]
Stopped experiencing the bug for a while. 
I also bumped ruby to 2.7, don't know if changes anything.
