### ISSUE TITLE
Language server seems to do nothing

### ISSUE THREAD

**Issue by gnarfle** [rubyide/vscode-ruby#556]
### Your environment

- `vscode-ruby` version: 0.25.3
- Ruby version: 2.6.4
- Ruby version manager (if any): asdf
- VS Code version: 1.40.0
- Operating System: OSX 10.15.1
- Using language server? (eg `useLanguageServer` is true?) yes

### Expected behavior

Linting, some output, anything

### Actual behavior

Nothing happens. The Ruby Language Server output just shows:

```
[Info  - 6:03:49 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/ccunningham/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/tree-sitter-ruby.wasm
```

That's it. Opening files, saving files, any other activity, has no further output. Seems like something is hanging? I've tried various settings, using rubocop vs standard for formatting, using bundler or not, and just nothing happens. If there's anything else I can do to debug let me know!

**Comment by wingrunr21** [comment]
What is the contents of the directory `/Users/ccunningham/.vscode/extensions/rebornix.ruby-0.25.3/dist/server/`?

**Comment by chadcf** [comment]
* index.js
* index.js.map
* rubyfmt.rb
* tree-sitter-ruby.wasm
* tree-sitter.wasm

**Comment by mjhoy** [comment]
same happens for me, vscode-ruby `0.26`, ruby `2.6.3`.

**Comment by combor** [comment]
Same here. Linting starts with
```
[Info  - 16:02:58] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from ~/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/tree-sitter-ruby.wasm
Lint: executing rubocop -s ~/dev/src/bitbucket.bip.uk.fid-intl.com/filcf/fil-nsx-client/lib/fil-nsx-client/nsx_application.rb -f json -l...
```
after this it gets stuck and never returns. 
```
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
```
and
```
brew info rbenv 
rbenv: stable 1.1.2 (bottled), HEAD
```

**Comment by atipugin** [comment]
Same here, ruby 2.7.0,. ext version 0.26.0:

```
[Info  - 1:55:38 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/atipugin/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/tree-sitter-ruby.wasm
```

**Comment by hd321kbps** [comment]
We are waiting for corrections

**Comment by andy-preston** [comment]
No one seems to care!

**Comment by futurepaycc** [comment]
ruby 2.7 same problem

**Comment by naiyt** [comment]
Has anyone had any luck with this? It seems to just get stuck on `Initializing Ruby language server...` for me, with no errors or additional output.
