### ISSUE TITLE
File is not formatted (Standard) on save

### ISSUE THREAD

**Issue by roykolak** [rubyide/vscode-ruby#559]
### Your environment

- `vscode-ruby` version: 0.25.3
- Ruby version: 2.6.5
- Ruby version manager (if any):
- VS Code version: 1.40.1
- Operating System: MacOS (10.14.5)
- Using language server? (eg `useLanguageServer` is true?) Yes

### Expected behavior

When 'standard' is selected to be the formatter, it should format the saved file.

### Actual behavior

It does not format the file. 

I do see formatting output in the Ruby Language Server console...

```
Format: executing standardrb -s /Users/path/to/file.rb --fix
```

and if I run that command in the terminal, it just hangs. Should note that linting w/ `standardrb` works fine and if I drop the `-s` from the command above, the file is fixed.

**Comment by wingrunr21** [comment]
Please review the troubleshooting documentation and post back

**Comment by roykolak** [comment]
Ah, when I run the command w/ the `cat file.rb | ` prefix, I do see the fixed file outputted to the console. It's just that this fixed version is not getting save.

**Comment by wingrunr21** [comment]
ok great. So, you are not using any version manager? And standard is installed globally?

**Comment by roykolak** [comment]
I'm using rbenv (forgot to mention), standard is installed via a project Gemfile and used via a binstub

**Comment by wingrunr21** [comment]
How are you loading the bundler `bin` directory into your `PATH`?

**Comment by roykolak** [comment]
that happens via a `.envrc` when the project directory is entered 

`export PATH=$PWD/bin:$PATH`

**Comment by wingrunr21** [comment]
Hmm, via `direnv`? What shell do you use?

I haven't tested `direnv` with the environment detection. It _should_ work but don't know for sure.

**Comment by roykolak** [comment]
I'm using bash. Yep, via direnv. 

Wondering if you have any guesses why linting would work fine, but formatting would be having troubles. That makes me think everything w/ the standardrb executable and it's path is not the problem.

**Comment by wingrunr21** [comment]
That’s interesting. The same spawn settings are used for lint and format so you’re right it should work. You don’t have useBundler enabled for the linter do you?

**Comment by roykolak** [comment]
I don't have bundler enabled for linting, but when I do enable it, it still lints just fine w/ a `bundle exec` prepended.

**Comment by wingrunr21** [comment]
ok, so are you seeing the file formatted correctly within VSCode? Running the format command does not change the file on disk (as the file as it exists in VSCode is not guaranteed to be on disk) so the only place you'd see the formatted file is within VSCode. Sorry, just trying to check how things are working as it is strange the linting works but the format does not.

**Comment by roykolak** [comment]
I do not see the file formatted correctly in vscode. When I have formatting set to `standard`, I see the format log entry in the Ruby Language Server output, but the open file in vscode does not change.

**Comment by joshclow** [comment]
I'm seeing the same behaviors on macOS with standard (and rubocop too), with the file not updating in vscode

**Comment by joshclow** [comment]
The output I'm seeing when I try to use bundler for either Linting for Formatting implies that it's looking for bundler in the system install of Ruby, instead of what's defined by `.ruby_version` in the directory:

```/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.2) ```

**Comment by tbsvttr** [comment]
I have similar problem. If I format the file I see (correct) changes and I can save the file. On save however it only saves and lins my file, but does not correct it.

I am using rbenv with Ruby 2.6.5 on macOS 10.15.2. My VSCode is on 1.40.2. I am using zsh 5.7.1 with some plugins via Oh My Zsh and Powerline 10k.

**Comment by tan-wei** [comment]
Same probelm on Windows.

**Comment by jorgegonzalez** [comment]
I'm having a similar issue on macOS but with Rubocop. File does not format on save, but it does format with the `CMD+Shift+P > "Format Document"` command.

```json
  "ruby.useBundler": true,
  "ruby.useLanguageServer": true,
  "ruby.lint": {
    "rubocop": true
  },
  "ruby.format": "rubocop"
```

**Comment by simonmd** [comment]
Same on MacOS. Thought it was a conflict with SolarGraph but it happens even with it uninstalled completely.

**Comment by senordelaflor** [comment]
@roykolak did you ever figure this one out? Having the same issue once we updated to Standard version 1.19.1. This was working with Standard 1.0.5

**Comment by roykolak** [comment]
@senordelaflor Like most things, it was a configuration issue for me. I was missing this from my vscode settings...

```json
  "[ruby]": {
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "rebornix.ruby"
  },
```
