### ISSUE TITLE
Do not step into gems, only debug my code

### ISSUE THREAD

**Issue by nabheet** [rubyide/vscode-ruby#562]
### Your environment

- `vscode-ruby` version: latest (not sure how to get it)
- Ruby version: ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux]
- Ruby version manager (if any):
- VS Code version: 1.40.1
- Operating System: Linux aacf6a6efc1c 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (VS Code remote containers)
- Using language server? (eg `useLanguageServer` is true?) yes

### Expected behavior
I have searched quite a bit and haven't been able to find an answer to this question. I apologize if this is really basic, my google-fu is not strong enough to find this information.

Lets say the gems used by our application are installed in /usr/locaI/bundle. I was wondering if there was a way to prevent the debugger from stepping into files in that directory. In other words, is it possible to force the debugger to only step into files that are in my workspace and continue or step over the code that is in gems in a different directory.

I have been able to attach to the debugger using VS Code Remote Containers. During my debug attemps, I have ended up in files for rspec and rails in the bundle directory which has cause some confusion during my debugging attempts. So was hoping that if directories could be excluded or forcibly included, it would solve my problem

Any advice would be helpful.

https://github.com/ruby-debug/ruby-debug-ide/issues/181

### Actual behavior
While debugging VS Code ends up in the gems directory when I step out of some of my functions.

**Comment by jrenton** [comment]
+1 on this. There is a similar issue here: https://github.com/rubyide/vscode-ruby/issues/354 which references "skipFiles" that Node.js debugging uses: https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome

There is also a comment on the general "Debugger improvements" thread: https://github.com/rubyide/vscode-ruby/issues/316#issuecomment-467405168

This feature would be huge! I'd love to help out with this but for some reason in development it does nothing attach I attempt to attach to a process. @wingrunr21
