### ISSUE TITLE
Format with Rubocop does not respect .rubocop.yml inherit_from overrides

### ISSUE THREAD

**Issue by bessey** [rubyide/vscode-ruby#566]
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: 2.6
- Ruby version manager: rbenv
- VS Code version: 1.40.1
- Operating System: Ubuntu 19.04
- Using language server: false

### Expected behavior

If open VS Code at the root of an app (Rails, though I don' think thats relevant) and have this file structure:
```
.rubocop.yml
app/
  thing.rb
spec/
  .rubocop.yml
  thing_spec.rb
```

with `spec/rubocop.yml` containing

```yaml
inherit_from: ../.rubocop.yml

# Some cop overrides
```

and I open `spec/thing_spec.rb`, the linting errors that appear should be based on `spe/.rubocop.yml`, and formatting should remove any autocorrect-able errors.

### Actual behavior

The linting errors I see is correct, e.g. cops that are disabled in `spec/rubocop.yml` are indeed disabled. However, when I format the file the formatting is done based on the root `.rubocop.yml` configuration, not the `spec/.rubocop.yml` overrides, resulting in autocorrection of valid code.

This is super frustrating because in my case it is auto-correcting valid `spec/` code to invalid `spec/` code on every save, and the only solution is to disable format on save and format manually for `app/` files.

**Comment by pre** [comment]
I can confirm the behaviour with VSCode 1.43.2.

When path to inherit_from is relative, VSCode will find the file, but any relative paths defined there (eg. `../../common/rubocop-defaults.yml`)  will **not** work.

The problem exists even when I explicitly open VSCode with `code` command in the project's exact directory from where I can run `bundle exec rubocop`.

It should be possible to define the Rubocop Current Working Directory per-project basis. For example, I have a monorepo which has multiple projects which each inherit from the same `../../common/.rubocop-defaults-yml`, but each project is independent from each other. 

It should be possible to define `spec/xyz/*` in `rubocop-defaults.yml` and that `spec/` should be relative to the Current Working Directory from where VSCode was started from with `code`. 

That would be a straightforward solution: no extra configuration needed, just use the directory where `code` was executed in as the CWD for `rubocop`. 

## Example

* `inherit_from: ../../common/rubocop-defaults.yml` 
* Start VSCode with `code` in the project root directory (ie. the same directory where `spec/` exists)
 
###  **NOT WORKING**: relative path in Exclude

```yaml
Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
```

###  **DOES WORK**: absolute path in Exclude

```yaml
Metrics/BlockLength:
  Exclude:
    - "/Users/thatsme/dev/path/to/project/spec/**/*.rb"
```
