### ISSUE TITLE
Could not locate Gemfile or .bundle/ directory

### ISSUE THREAD

**Issue by mdesson** [rubyide/vscode-ruby#568]
A quick note: I'm very new to Ruby and was setting up the linter and formatter as a part of getting set up. I've looked through troubleshooting and tried looking for existing issues before posting. I apologize in advance if this seems obvious!

### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: ruby 2.6.5p114
- VS Code version: 1.40.0
- Operating System: Manjaro
- Using language server? yes

### Expected behavior
Linter lints, and format on save formats on save.

### Actual behavior

No effect on the file. The language server output is (after opening a file and then saving):

```
[Info  - 11:48:50 p.m.] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /home/mike/.vscode-oss/extensions/rebornix.ruby-0.26.0/dist/server/tree-sitter-ruby.wasm
Lint: executing bundle exec rubocop -s /home/mike/school/2019-Fall/COMP-348/ri20min.rb -f json...
Lint: executing bundle exec reek -f json...
Could not locate Gemfile or .bundle/ directory

Could not locate Gemfile or .bundle/ directory

Lint: executing bundle exec rubocop -s /home/mike/school/2019-Fall/COMP-348/ri20min.rb -f json...
Lint: executing bundle exec reek -f json...
Could not locate Gemfile or .bundle/ directory

Could not locate Gemfile or .bundle/ directory

Lint: executing bundle exec rubocop -s /home/mike/school/2019-Fall/COMP-348/ri20min.rb -f json...
Lint: executing bundle exec reek -f json...
Could not locate Gemfile or .bundle/ directory

Could not locate Gemfile or .bundle/ directory

Format: executing bundle exec rubocop -s /home/mike/school/2019-Fall/COMP-348/ri20min.rb -a...
Could not locate Gemfile or .bundle/ directory

[Error - 11:48:54 p.m.] Request textDocument/formatting failed.
  Message: Request textDocument/formatting failed with message: 
    unable to execute bundle exec rubocop -s /home/mike/school/2019-Fall/COMP-348/ri20min.rb -a:
    Error: Failed with exit code: 10 - unknown error
  Code: -32603  exit code: 10 - unknown error
  Code: -32603 
```

My settings are from the extension description:
```
 "ruby.useBundler": true, //run non-lint commands with bundle exec
  "ruby.useLanguageServer": true, // use the internal language server (see below)
  "ruby.lint": {
    "rubocop": {
      "useBundler": true // enable rubocop via bundler
    },
    "reek": {
      "useBundler": true // enable reek via bundler
    }
  },
  "ruby.format": "rubocop" // use rubocop for formatting
```

Versions
```
rubocop -v
0.77.0

reek -v
reek 5.5.0
```

**Comment by ackinc** [comment]
Perhaps you got rubocop and reek installed without bundler (i.e. by running the equivalent `gem install ...` commands?

Try changing your rubocop and reek settings to:
```
"rubocop": {
    "useBundler": false
},
"reek": {
    "useBundler": false
}
```

**Comment by mdesson** [comment]
That fixed it for reek! rubocop is not formatting, but it's possible I need to configure it. I'm willing to close this one out and try to investigate why rubocop isn't formatting.

If I wanted to use bundler, where would I put the bundle file for the language server to pick it up? Would it go here?
``
/home/mike/.vscode-oss/extensions/rebornix.ruby-0.26.0/dist/server
```
