### ISSUE TITLE
Linting fails with `Lint: unable to execute rubocop -s ... -f json as the command could not be found`

### ISSUE THREAD

**Issue by ackinc** [rubyide/vscode-ruby#569]
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: 2.6.1
- Ruby version manager (if any): RVM
- VS Code version: 1.40.2
- Operating System: Ubuntu 19.04
- Using language server? (eg `useLanguageServer` is true?) Yes

### Expected behavior
The extension's linting feature works (I see lint squiggles in my IDE?)

### Actual behavior
Nothing happens to indicate linting is working. I see `Lint: unable to execute rubocop -s ... -f json as the command could not be found` in the OUTPUT terminal (see screenshot)

![Screenshot from 2019-12-01 04-07-32](https://user-images.githubusercontent.com/4007598/69906877-67a27400-13f0-11ea-87a9-df5c864c4dfb.png)

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*

**Comment by ackinc** [comment]
My VSCode user settings:

```
{
    "terminal.integrated.fontSize": 12,
    "window.zoomLevel": 0,
    "editor.tabSize": 2,
    "editor.renderWhitespace": "all",
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true,
    "html.format.endWithNewline": true,
    "explorer.confirmDragAndDrop": false,
    "explorer.confirmDelete": false,
    "ruby.format": "rubocop",
    "ruby.codeCompletion": "rcodetools",
    "ruby.intellisense": "rubyLocate",
    "ruby.useLanguageServer": true,
    "ruby.lint": {
        "rubocop": {
            "useBundler": false // enable rubocop via bundler
        },
        "reek": {
            "useBundler": false // enable reek via bundler
        }
    },
    "terminal.integrated.shellArgs.linux": [
        "--login"
    ],
}
```

I have no workspace-settings

**Comment by ackinc** [comment]
Running the linting commands directly in the VSCode terminal works fine. Screenshot below:

![Screenshot from 2019-12-01 04-15-23](https://user-images.githubusercontent.com/4007598/69906921-48581680-13f1-11ea-9feb-310d649c63bb.png)

**Comment by ackinc** [comment]
Also, the language server crashed shortly after I start working. This was the error: `Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}`

Full log of error:
```
[Info  - 4:25:26 am] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/tree-sitter-ruby.wasm
/home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16
var r=function(t,e){return(r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(t,e){t.__proto__=e}||function(t,e){for(var n in e)e.hasOwnProperty(n)&&(t[n]=e[n])})(t,e)};function i(t,e){function n(){this.constructor=t}r(t,e),t.prototype=null===e?Object.create(e):(n.prototype=e.prototype,new n)}},function(t,e,n){"use strict";n.d(e,"a",function(){return l});var r=n(0),i=n(26),o=n(57),s=n(5),u=n(42),a=n(14),c=n(37),l=function(t){function e(n,r,i){var s=t.call(this)||this;switch(s.syncErrorValue=null,s.syncErrorThrown=!1,s.syncErrorThrowable=!1,s.isStopped=!1,arguments.length){case 0:s.destination=o.a;break;case 1:if(!n){s.destination=o.a;break}if("object"==typeof n){n instanceof e?(s.syncErrorThrowable=n.syncErrorThrowable,s.destination=n,n.add(s)):(s.syncErrorThrowable=!0,s.destination=new f(s,n));break}default:s.syncErrorThrowable=!0,s.destination=new f(s,n,r,i)}return s}return r.a(e,t),e.prototype[u.a]=function(){ret

Error: [UriError]: Scheme is missing: {scheme: "", authority: "", path: "undefined", query: "", fragment: ""}
    at /home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:62004
    at e.t (/home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:62624)
    at new e (/home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:64286)
    at Function.t.parse (/home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:63519)
    at /home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293468
    at /home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293515
    at Array.map (<anonymous>)
    at e.project (/home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:293302)
    at e._tryNext (/home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:30637)
    at e._next (/home/anirudh/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/index.js:16:30539)
```

This error occurred 5 times in succession, then the language server stopped restarting

**Comment by gi** [comment]
@ackinc Do you have Ruby installed with `rbenv` or `asdf`? I have run into this same error message when trying to view or lint a file which is not in a project directory and with no global Ruby version installed. Thus, the tool cannot find `ruby`. You might try setting/configuring the global Ruby version if you use one of those version managers.

**Comment by patrykk21** [comment]
I have the same issue after updating vs code.
Everything works fine from terminal.

Using rvm with
ruby 2.5.7 and rubocop 0.88.0

**Comment by Cobalt7291** [comment]
Wondering if anyone has run into this issue with respect to the new ARM processors on the Mac m1?

**Comment by TSMMark** [comment]
Having this issue when using rvm

**Comment by fazo96** [comment]
What fixes it for me is running VS Code using `code .` in the terminal instead of using the .desktop launcher (I am on Linux). I also have ruby installed through rvm

Another option is updating the .desktop launcher so that it runs vscode through bash, so vscode has access to ruby installed through RVM.

I also had this issue https://github.com/rubyide/vscode-ruby/issues/533 with the language server crashing on vscode launch which also gets fixed the same way
