### ISSUE TITLE
Error: ENOENT: no such file or directory language-configuration-ruby.json

### ISSUE THREAD

**Issue by mmarinaccio** [rubyide/vscode-ruby#571]
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: 2.3.8
- Ruby version manager (if any): rbenv
- VS Code version: 1.40
- Operating System: Mac OS 10.15.1
- Using language server? (eg `useLanguageServer` is true?) Yes

Hello -

I recently installed VS Code and the Ruby extensions but am now struggling to spin up the language server. More generally, none of the linting functionality appears to be working.

When I view the `Language Server Output Channel`, the server appears to be hanging at `Loading Ruby tree-sitter syntax from /Users/mike/.vscode/extensions/rebornix.ruby-0.26.0/dist/server/tree-sitter-ruby.wasm`.

When I view the Developer Tools debugging console, I see the following error:
```Error: Unable to read file (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '/Users/mike/.vscode/extensions/rebornix.ruby-0.26.0/language-configuration-ruby.json')```

Before installing the Ruby extensions, I `brew` installed `rbenv` and then installed ruby version 2.3.8.

My `settings.json` looks like this:
```json
{
    "workbench.colorTheme": "Default High Contrast",
    "terminal.integrated.shell.osx": "/bin/bash",
    "window.zoomLevel": 0,
    "ruby.useLanguageServer": true,
    "ruby.format": "rubocop",
    "[ruby]": {

    }
}
```

Any help would be greatly appreciated.

Thanks!

**Comment by gopeter** [comment]
How did you solved it?

**Comment by dolsem** [comment]
I was able to fix this by running `curl https://raw.githubusercontent.com/rubyide/vscode-ruby/master/packages/vscode-ruby/language-configuration-ruby.json > ~/.vscode/extensions/rebornix.ruby-0.27.0/language-configuration-ruby.json`

**Comment by quoyi** [comment]
> curl https://raw.githubusercontent.com/rubyide/vscode-ruby/master/packages/vscode-ruby/language-configuration-ruby.json > ~/.vscode/extensions/rebornix.ruby-0.27.0/language-configuration-ruby.json

Same to `curl https://raw.githubusercontent.com/rubyide/vscode-ruby/master/packages/vscode-ruby/language-configuration-erb.json > ~/.vscode/extensions/rebornix.ruby-0.27.0/language-configuration-erb.json`

**Comment by alexanderadam** [comment]
@wingrunr21 it seems that this is still an issue in `rebornix.ruby-0.28.1`.
Any reason why this is the case?
And is this solvable?

**PS:** Thank you so much for `vscode-ruby`. It is so great! :pray:

**Comment by heynan0** [comment]
I get this issue as well. What is the status?

```
Error: Unable to read file '/Users/heynan0/.vscode/extensions/rebornix.ruby-0.28.1/language-configuration-ruby.json' (Error: Unable to resolve nonexistent file '/Users/heynan0/.vscode/extensions/rebornix.ruby-0.28.1/language-configuration-ruby.json')
```

**Comment by thomthom** [comment]
I'm also seeing the same thing with 0.28.1 on Windows.

```
languageConfigurationExtensionPoint.ts:147 Error: Unable to read file 'c:\Users\user\.vscode\extensions\rebornix.ruby-0.28.1\language-configuration-ruby.json' (Error: Unable to resolve nonexistent file 'c:\Users\user\.vscode\extensions\rebornix.ruby-0.28.1\language-configuration-ruby.json')
```
