### ISSUE TITLE
Highlighting for '!!' (double bang)

### ISSUE THREAD

**Issue by AlexStoll** [rubyide/vscode-ruby#573]
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: N/A
- Ruby version manager (if any): N/A
- VS Code version: 1.41.0
- Operating System: mac 10.14.5
- Using language server? (eg `useLanguageServer` is true?)

### Expected behavior

Syntax highlighting for 'double bang' (`!!some_thing`) seems off.
I would expect it to look like it does in Sublime Text -  show below.
![Sublime screenshot](https://user-images.githubusercontent.com/44987522/71328348-8addb200-24ca-11ea-8a2c-783023223097.png).

### Actual behavior

Instead, it does the first `!` in red, but assumes the second one is part of whatever comes after. This doesn't seem like the clearest highlighting. Here's an example of how it looks for me.
![Example in VS Code](https://user-images.githubusercontent.com/44987522/71328374-2707b900-24cb-11ea-9178-138c93d2598e.png)

**Comment by wingrunr21** [comment]
I'll try and find some time to take a look. In the mean time, the grammar has tests and is available [here](https://github.com/rubyide/vscode-ruby/tree/master/packages/vscode-ruby). A PR would be great.

**Comment by AlexStoll** [comment]
I’ll dive in and see what I can figure out tomorrow!
