### ISSUE TITLE
Linting code via language server does not respect pathToBundler setting

### ISSUE THREAD

**Issue by pmk1c** [rubyide/vscode-ruby#581]
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: 2.6.5
- Ruby version manager (if any): asdf
- VS Code version: 1.41.1
- Operating System: Fedora
- Using language server? (eg `useLanguageServer` is true?) yes

### Expected behavior

Linting code calls `${ruby.pathToBundler} exec rubocop …` when `ruby.useBundler` is set to true. 

### Actual behavior

Linting code calls `bundle exec rubocop …` when `ruby.useBundler` is set to true.

Output in console:

```
Lint: executing bundle exec rubocop -s /home/user/projects/…/file.rb -f json...
```

The same is happening when formatting code, but this is already being fixed in https://github.com/rubyide/vscode-ruby/pull/576.

**Comment by earksiinni** [comment]
This problem affects me, too. Any chance that we could get #596 merged?
