### ISSUE TITLE
Add support for Sorbet type checker

### ISSUE THREAD

**Issue by lloeki** [rubyide/vscode-ruby#583]
Sorbet (https://sorbet.org) is a very efficient type checker for Ruby gaining great traction.

As of today it is not in the list of supported linters of this extension.

Vim's ALE extension [uses the following](https://github.com/dense-analysis/ale/pull/2614/files#diff-c1fd480b189fe32e40b111be97b570d2R8-R11) to run Sorbet, enabling integrated Language Server Protocol mode:

```
srb tc --lsp --disable-watchman
```

**Comment by wingrunr21** [comment]
Why would you want to use this extension vs Sorbet's own VSCode extension?

**Comment by lloeki** [comment]
> Sorbet's own VSCode extension

I'm not sure what you're talking about. There is no reference to any Sorbet's own VSCode extension in:

- their [home page](https://sorbet.org/)
- their [doc](https://sorbet.org/docs/overview)
- the [community links](https://sorbet.org/en/community)
- their [README](https://github.com/sorbet/sorbet/blob/master/README.md) on GitHub
- their [org](https://github.com/sorbet/) has four repos, none being a VSCode extension
- VSCode extension search for `sorbet` returns `No extension found`

† This is the only place where an IDE/editor is mentioned:

> IDE-ready: Sorbet works with your favorite editor to provide IDE features like autocomplete and jump to definition. It’s easy to add to your CI setup.

Additionally, sorbet is a code checker tool exactly like rubocop, rubyfmt, etc... I feel like it makes perfect sense to have this integrated into vscode-ruby, notably due to all the things that vscode-ruby does, like handling bundler/chruby/etc... I'd hate to have to configure two tools and have them generally behave differently when one does the job perfectly and is actually designed for exactly to do that.

**Comment by dnamsons** [comment]
https://github.com/sorbet/sorbet/issues/1013 

Editor support for sorbet is being developed, but it hasn't been open-sourced yet.

**Comment by wingrunr21** [comment]
I will not be supporting Sorbet in this extension.
