### ISSUE TITLE
Ruby language server ignore .ruby-version and .ruby-gemset 

### ISSUE THREAD

**Issue by michal-samluk** [rubyide/vscode-ruby#585]
### Your environment

- `vscode-ruby` version: 0.26.0
- Ruby version: 2.6.5
- Ruby version manager (if any): rvm
- VS Code version: 1.41.1
- Operating System: osx 
- Using language server? (eg `useLanguageServer` is true?): true

### Expected behavior
Ruby language server should use ruby defined in `.ruby-version` and `.ruby-gemset` file. 

### Actual behavior
Currently I need to run this command: `rvm --default use 2.6.5@gemset` to make ruby language server to work with rubocop. Behavior is the same when I am not using gemset.

**Comment by wingrunr21** [comment]
Can you provide some more information on your directory structure? There are quite a few RVM users who have reported this has worked in the past

**Comment by michal-samluk** [comment]
@wingrunr21 What directories are you interested in? 

```
$ which ruby                                                                                                                                                                                                                 
/Users/myuser/.rvm/rubies/ruby-2.6.5/bin/ruby
```

`.ruby-version` and `.ruby-gemset` are in directory: 
```
/Users/myuser/Projects/myproject
```

**Comment by ikirifqi** [comment]
Me experiencing this as well, even by overriding `"command": "$HOME/.rvm/gems/ruby-2.3.8@gemset/bin/rubocop"` in vscode config. It seems `$PATH` doesn't changed and they still look to default ruby version (mine `2.6.5`).

```
[Info  - 11:34:22 AM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /Users/***/.vscode/extensions/rebornix.ruby-0.27.0/dist/server/tree-sitter-ruby.wasm
Lint: executing /Users/***/.rvm/gems/ruby-2.3.8@gemset/bin/rubocop -s /Users/***/Documents/ruby/project/test/spec/tasks/tech_support_spec.rb -f json -R...
/Users/***/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem rubocop (>= 0.a) with executable rubocop (Gem::GemNotFoundException)
	from /Users/***/.rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	from /Users/***/.rvm/gems/ruby-2.3.8@gemset/bin/rubocop:23:in `<main>'
	from /Users/***/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/***/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by michal-samluk** [comment]
More information from me. After upgrading to `ruby-2.7.1`, applying default gemset and restarting vscode multiple times (or window reload), ruby language server was still using older version of ruby. Restarting my Mac helped.
