### ISSUE TITLE
Incorrect grammar scope assigned for hash keys that match "core" Ruby functions

### ISSUE THREAD

**Issue by arempe93** [rubyide/vscode-ruby#591]
Scopes for keywords/hash keys seem broken unless there is a `.` preceding the method call.

### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.6.2
- Ruby version manager (if any): rvm
- VS Code version: 1.42.1
- Operating System: OSX 10.15.3 Catalina
- Using language server? (eg `useLanguageServer` is true in your configuration?): No

### Expected behavior

Before changes in #579:

<img width="292" alt="Screen Shot 2020-03-02 at 10 28 38" src="https://user-images.githubusercontent.com/4637120/75696743-af47ce80-5c71-11ea-84c8-18b7c0a09fb5.png">

All keyword arguments/hash keys have scopes:

```
constant.language.symbol.hashkey.ruby
meta.function-call.ruby
source.ruby
```

First group additionally has:

```
punctuation.definition.constant.hashkey.ruby
```

### Actual behavior

After upgrading to 0.27.0:

<img width="292" alt="Screen Shot 2020-03-02 at 10 43 41" src="https://user-images.githubusercontent.com/4637120/75697452-b91e0180-5c72-11ea-9bc7-7dd002b1f800.png">

**First group** keyword arguments/hash keys have scopes:

```
support.function.core.ruby
meta.function-call.ruby
source.ruby
```

**Second group** have scopes:

```
constant.language.symbol.hashkey.ruby
source.ruby
```

*Code Sample*
```ruby
find!(id: 1)
find!({ id: 1 })

Candidate.find!(id: 1)
Candidate.find!({ id: 1 })
```

**Comment by wingrunr21** [comment]
This appears to be specific to methods the grammar flags as `support.function.core.ruby`. If you use a hash key that is not "core" (eg `foobar`, highlighting is correct).
