### ISSUE TITLE
Incorrect scopes after update to 0.27

### ISSUE THREAD

**Issue by thedanbob** [rubyide/vscode-ruby#592]
Similar to [this issue](https://github.com/rubyide/vscode-ruby/issues/591) I found a few incorrect TM grammar scopes after updating to 0.27.

### Your environment

- `vscode-ruby` version: 0.27
- Ruby version: 2.3.3
- Ruby version manager (if any): rbenv
- VS Code version: 1.42.1
- Operating System: Linux
- Using language server? (eg `useLanguageServer` is true in your configuration?) false

### Expected behavior
0.26:
![initializer-0 26](https://user-images.githubusercontent.com/1530175/75723915-dff42c00-5ca2-11ea-9fc8-2283f3c93d4e.png)
![gemfile-0 26](https://user-images.githubusercontent.com/1530175/75723932-e682a380-5ca2-11ea-86f0-aa299b018c94.png)

### Actual behavior
0.27:
![initializer-0 27](https://user-images.githubusercontent.com/1530175/75723956-f9957380-5ca2-11ea-835b-434582a103fb.png)
![gemfile-0 27](https://user-images.githubusercontent.com/1530175/75723967-fd28fa80-5ca2-11ea-95c9-47181d1cd668.png)
If I find any others I'll add them.

**Comment by wingrunr21** [comment]
Yep. And those are all setters, which are functions.

**Comment by thedanbob** [comment]
Oh true, good point. Just the gemfile ones then (`source` and `group` are also affected).
