### ISSUE TITLE
Rubocop cache not honoring the correct tmp dir

### ISSUE THREAD

**Issue by ianks** [rubyide/vscode-ruby#594]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.6.5
- Ruby version manager (if any): asdf
- VS Code version:  1.43.0
- Operating System: Mac
- Using language server? (eg `useLanguageServer` is true in your configuration?) no

### Expected behavior

Rubocop caches should be saved in the directory relative to .rubocop.yml

### Actual behavior

Rubocop caches are saved to the directory reltaive to the file being linted

<img width="370" alt="Screen Shot 2020-03-17 at 3 17 51 PM" src="https://user-images.githubusercontent.com/3303032/76893515-dc47d400-6862-11ea-9a7f-453b654b3236.png">

### Heres my config

<img width="328" alt="Screen Shot 2020-03-17 at 3 18 23 PM" src="https://user-images.githubusercontent.com/3303032/76893477-cafec780-6862-11ea-9384-6941f8128787.png">

**Comment by wingrunr21** [comment]
You have the cache root set to a relative directory. RuboCop is not executed with a working directory of the `.rubocop.yml`. For legacy linting that working directory is the file's directory. For the language server that's either the workspace root or soon it will also be the file's directory (to support nested `.rubocop.yml` files).

If you wish the cache directory to be consistent it needs to be an absolute path. This would be consistent with [rubocop's defaults](https://docs.rubocop.org/en/stable/caching/)
