### ISSUE TITLE
cannot run the extension in VSCode's debugger

### ISSUE THREAD

**Issue by doudou** [rubyide/vscode-ruby#595]
### Your environment

- `vscode-ruby` version: 0.27.0
- VS Code version: 1.43.1
- Operating System: Ubuntu 19.10
- Using language server? (eg `useLanguageServer` is true in your configuration?): no

### Expected behavior

After following "Getting Started" instructions in https://github.com/rubyide/vscode-ruby/blob/master/docs/developing.md, I am expecting to be able to run the extension using the "Launch Extension" debug target.

I have

- cloned the repo
- run `yarn install`
- run `yarn watch`

with output

~~~
[.../vscode/vscode-ruby]% yarn install
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning ruby@0.27.0: The engine "vscode" appears to be invalid.
warning vscode-ruby@0.27.0: The engine "vscode" appears to be invalid.
warning vscode-languageclient@5.2.1: The engine "vscode" appears to be invalid.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 1.76s.

 (15:44) doudou@narinari 
[.../vscode/vscode-ruby]% yarn watch  
yarn run v1.21.1
$ lerna run watch
lerna notice cli v3.16.4
lerna info Executing command in 3 packages: "yarn run watch"
~~~

### Actual behavior

VSCode's development host starts but reports

~~~
Activating extension 'rebornix.ruby' failed: Cannot find module '/home/doudou/dev/vscode/vscode-ruby/packages/vscode-ruby-client/dist/client/ruby.js'
Require stack:
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js.
~~~

**Comment by dget** [comment]
I've got the same issue. Running `yarn run lerna list` only shows the package for the server (which appears to have its own `dist` subdirectory, but not where anything expects it.

```
Daniels-MBP-2:vscode-ruby danielgetelman$ yarn run lerna list
yarn run v1.22.4
$ <home>/Code/vscode-ruby/node_modules/.bin/lerna list
lerna notice cli v3.16.4
language-server-ruby
lerna success found 1 package
✨  Done in 0.98s.
```

**Comment by wingrunr21** [comment]
Did either of you check if the symlinks were created properly? There are three compilation targets that need to be symlinked into the extension's `dist` directory.

**Comment by dget** [comment]
I don't have a root `dist` directory, and I don't see symlinks in the `packages/vscode-ruby-client/dist` directory either. I eventually was able to see changes by running `yarn package`, which I _believe_ created files in `packages/vscode-ruby-client/dist`, but I could be misreading it.

**Comment by wingrunr21** [comment]
There is no `dist` directory in the root of the repo. The `dist` directory is in the `vscode-ruby-client` directory as that's where the extension is defined.

**Comment by dget** [comment]
Got it. Yeah, it looks like the symlinks aren't getting setup by the script.

**Comment by wingrunr21** [comment]
ok. That's a bit strange but if you run the bash script manually it should setup the symlinks.

**Comment by tvallois** [comment]
Hello,

I have same issue as @doudou , i'm trying to debug the debugger with Extension w/ Debug Server config. The extension host start but i'm unable to start a debugging process on my rails app.
