### ISSUE TITLE
Linting doesn't work with chruby

### ISSUE THREAD

**Issue by dget** [rubyide/vscode-ruby#597]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.6.5 in chruby, 2.3.7 system
- Ruby version manager (if any): chruby
- VS Code version: 1.43.2
- Operating System: MacOS Mojave
- Using language server? (eg `useLanguageServer` is true in your configuration?) Yes.

### Expected behavior

I expect the language server to run, and linting to happen.

### Actual behavior

I get "The Ruby server crashed 5 times in the last 3 minutes. The server will not be restarted."

The following is in my Language Server logs: 
```
Lint: executing rubocop -s <file>.rb -f json...
Lint: unable to execute rubocop -s <file>.rb -f json as the command could not be found
```

My best guess is that it's running with the system ruby (which doesn't have rubocop setup), rather than chruby. If I try with bundler enabled, I get a similar message except it can't find bundler.

**Comment by wingrunr21** [comment]
Linting works fine with `chruby`. I use `chruby` personally.

That feels to me like the environment detection is not loading correctly. The crash is related to an annoying node bug that causes an uncatchable exception when you attempt to pipe `stdin` to an incorrectly spawned process (eg the command does not exist).

Can you give me some more details on what your setup looks like?

- What shell?
- What does your project directory structure look like?
- How are you selecting a Ruby to use?
- How is rubocop installed?

**Comment by dget** [comment]
I agree that's what's happening. If I run the shim from the directory in my project, I see it works. If I run it from `node` (`<path>/vscode-ruby/packages/vscode-ruby-client/dist/server/shims/env.bin.bash.sh`), it doesn't get any of the ruby vars.

Shell: bash
Directory structure: Monorepo, with each set up as a folder in the VSCode workspace. Each folder with Ruby has its own Gemfile + .ruby-version. 
Selecting a ruby to use: Auto-switching with .ruby-version. Fwiw, from printing out env variables, I can see it's running my `.bash_profile` where it loads the autoswitcher, but it doesn't seem to be loading any of the Ruby env variables.
Rubocop installed: Using bundler. I did try running this with the option set, but I got the same error only about bundler not being installed either.

**Comment by dget** [comment]
Actually -- I'm realizing that what I thought was it running the .bash_profile was probably it just inheriting my path. So... my read is that since it's setting up a non-interactive shell, the environment detection shim is not running the `.bash_profile` that deals with setting up chruby / the autoloader, so the environment vars aren't being set. Does that sound right? If it does, I'm wondering what's different between my setup and yours.

**Comment by wingrunr21** [comment]
This may sound dumb but you have the workspace open in VSCode right? Otherwise it'll default to the root directory that's opened in VSCode and that means environment detection will be run in that directory.

**Comment by dget** [comment]
Always good to check :) But yeah, I stuck an extra console log in to make sure it was calling the shim with the right cwd.

**Comment by wingrunr21** [comment]
Ok, another question: you said you are using `.bash_profile`. Have you tried `.bashrc`? The shims spawn an interactive shell but not a login shell, so I'd expect `.bashrc` to load but not `.bash_profile`.

**Comment by dget** [comment]
Good catch! That was it. Thank you for the help.

**Comment by wingrunr21** [comment]
Ok great. That's definitely something I'm going to want to document in the troubleshooting section. And/or I wonder if I should just consider a login shell in the shims so that it is more resilient with people's setups.
