### ISSUE TITLE
Textmate scopes and syntax highlighting

### ISSUE THREAD

**Issue by sandstrom** [rubyide/vscode-ruby#601]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.4.1
- Ruby version manager (if any): chruby
- VS Code version: 1.43.2
- Operating System: macOS 10.15.4 (Catalina)
- Using language server? nope

### Expected behavior

I had expected `user` and `company` (second last line) to get the same syntax highlight treatment. One is classified as a `support.function.core.ruby` and the other `entity.name.function.ruby`.

### Actual behavior
![sh1](https://user-images.githubusercontent.com/122287/78645214-7249aa00-78b7-11ea-9df6-efd9d7c807c6.png)

![sh2](https://user-images.githubusercontent.com/122287/78645209-707fe680-78b7-11ea-9f05-856d066e8a92.png)

**Comment by smridge** [comment]
I had the same issue, it looks like this will be resolved with the next release https://github.com/rubyide/vscode-ruby/commit/73e8e6fbdaa0884a65a6f64f4805bc32d484ff57

**Comment by sandstrom** [comment]
Great news! thanks @smridge for letting me know! 👍

**Comment by sandstrom** [comment]
fixed in https://github.com/rubyide/vscode-ruby/commit/73e8e6fbdaa0884a65a6f64f4805bc32d484ff57
