### ISSUE TITLE
Rubocop Ignored Files Not Respected

### ISSUE THREAD

**Issue by ecbrodie** [rubyide/vscode-ruby#612]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.6.5
- Ruby version manager (if any): rvm
- VS Code version: 1.44.2
- Operating System: Mac OS 10.15.4
- Using language server? *Yes*

### Expected behavior

Ignored files specified in the `AllCops.Exclude` list in `.rubocop.yml` are respected, when Rubocop linting is run by the extension.

### Actual behavior

The ignored files list is not being respected. The extension is underlining code due to a Rubocop violation. However, the entire file should have been excluded (and it is indeed excluded when I run `rubocop` directly on the command line).

In my case, I ignored all DB migration files, as in `db/migrate/*`. Looks like this isn't getting picked up properly by the extension.

Thank you.

**Comment by dmin** [comment]
I had a similar issue. After a little digging I found that the `forceExclusion` option fixes this issue for me (it essentially tells Rubocop to honor `Exclude`s in the config).

You can enable it in VS Code's settings.json as follows:
```
  "ruby.lint": {
    "rubocop": {
      "forceExclusion": true
    }
  },
```

**Comment by jmschp** [comment]
Hey!

The "forceExclusion": true options is not working for me!

- Macbook Pro (13-inch, 2017) - Big Sur 11.6
- Ruby version: 3.0.2
- Ruby version manager (if any): rbenv
- VS Code 1.60
- vscode-ruby 0.28.1



The extension is picking up the .rubocop.yml but it is. not excluding my db/schema.rb

```json
  "ruby.useLanguageServer": true,
  "ruby.format": "rubocop",
  "ruby.lint": {
    "rubocop": {
      "forceExclusion": true
    },
  },
```

It seems that if I disable the Language Server "ruby.useLanguageServer": false,
It respects the "forceExclusion": true.

But then I end up with the problem that the rubocop warnings don't disappear upon closing the file, from the problems panel.

Any ideias! 😄
