### ISSUE TITLE
$SAFE will become a normal global variable in Ruby 3.0

### ISSUE THREAD

**Issue by appomsk** [rubyide/vscode-ruby#618]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.7.0
- Ruby version manager (if any):
- VS Code version: 1.45.1
- Operating System: Linux Kubuntu 20.04
- Using language server? (eg `useLanguageServer` is true in your configuration?) Yes

### Expected behavior
No any messages

### Actual behavior
After every step in debugger the message appears in debug console: 
"NAME_OF_SCRIPT: $SAFE will become a normal global variable in Ruby 3.0." 

I changed debase to byebug but the behavior is the same.  I've found the similar problem was with pry, they somehow fixed it. But I'm a novice and I'm really don't understand where these messages come from and what I can do.

**Comment by jabamaus** [comment]
This message is really annoying. I spent some time looking into it but couldn't find the source of it. Apparently its output when deprecated calls to taint are made but I searched all the projects and couldn't find any calls, not direct ones anyway. I had look through the ruby codebase too.

On a separate note, how does byebug perform compared to debase? How do you get ruby_debug_ide to use byebug instead of debase?

**Comment by appomsk** [comment]
I really did not have time to compare. I uninstalled debase (and something like debase-core, I think) but it was not enough. Then I uninstalled ruby_debug_ide and installed again, and then byebug. I do not think I reinstalled vscode-ruby but it's possible.
It  was something I simply tried - I did not pay a lot of attention what I did. At the same time I googled about $SAFE variable  (the warning appeared in ruby 2.7) -  and grepped gems. I did not find anything - only in robocop, but it is not the cause.

**Comment by jabamaus** [comment]
I think that when you installed ruby-debug-ide it probably reinstalled debase and used that and not byebug. ruby-debug-ide is hard coded to debase which is why I was intrigued as to how you got it working.

**Comment by appomsk** [comment]
Hm... Yes. It's possible. 
```
/usr/bin/gem list | grep debase
debase (0.2.4.1)
debase-ruby_core_source (0.10.9)
```
Then instructions here are inaccurate:

> If you are using Ruby v2.x
> 
>     gem install ruby-debug-ide
>     gem install debase (or gem install byebug)

Anyway I've simply installed ruby 2.6.6 through rbenv, changed paths in vscode-ruby configuration and everything works now.
