### ISSUE TITLE
Ruby version not correctly parsed when using RVM

### ISSUE THREAD

**Issue by ferdaber** [rubyide/vscode-ruby#620]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.7.1
- Ruby version manager (if any): RVM
- VS Code version: 1.45.1
- Operating System: MacOS 10.15.4
- Using language server? (eg `useLanguageServer` is true in your configuration?) `true`

### Expected behavior

When linting or formatting (like with Rubocop) and using bundler, no errors are outputted and formatting behavior works.

### Actual behavior

**Workspace settings:**
```json
{
  "ruby.useBundler": true,
  "ruby.useLanguageServer": true,
  "ruby.codeCompletion": false,
  "ruby.intellisense": false,
  "ruby.format": "rubocop",
  "ruby.lint": {
    "rubocop": {
      "useBundler": true
    }
  }
}
```

**Directory structure:**
```
|- app.rb
|- Gemfile
|- Gemfile.lock
```

The following error is logged due to the wrong version of Ruby being loaded:
```
Lint: executing bundle exec rubocop -s /Users/admin/my-app/app.rb -f json...
/Users/admin/.rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/definition.rb:495:in `validate_ruby!': Your Ruby version is 2.6.3, but your Gemfile specified 2.7.1 (Bundler::RubyVersionMismatch)
	from /Users/admin/.rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/definition.rb:470:in `validate_runtime!'
	from /Users/admin/.rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler.rb:143:in `setup'
	from /Users/admin/.rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /Users/admin/.rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:136:in `with_level'
	from /Users/admin/.rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/ui/shell.rb:88:in `silence'
	from /Users/admin/.rvm/gems/ruby-2.6.3/gems/bundler-2.1.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from /Users/admin/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/admin/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

The content of `app.rb` itself is empty, meaning it's not affected by the source code.

### Hypothesis
When RVM is loaded, it aliases the `rvm` command as a function and sets up appropriate environment variables (like `RUBY_VERSION`) which is usually set at a user's `~/.profile` or `~/.bash_profile` dotfile. However those dotfiles are only sourced when running a shell with the login flag `/bin/bash -l`, otherwise RVM isn't loaded at all.

It seems that the fix would be to change this line to also pass the `-l` flag https://github.com/rubyide/vscode-ruby/blob/master/packages/vscode-ruby-common/src/environment.ts#L44.

I haven't tested it yet but it may also require a `cd .` statement to trigger RVM's automatic Ruby loading when changing directories.

**Comment by Yorkshireman** [comment]
I'm having the same problem.

**Comment by ferdaber** [comment]
@Yorkshireman a workaround is to open the extension folder, which is usually under `~/.vscode/extensions/rebornix.ruby-xxx` (`xxx` is the current extension version), and change this file: `dist/server/shims/env.bin.{shell}.sh` (`shell` will be whatever your default shell is). It'll look something like:

```sh
#!/bin/zsh -i
export
```

You want to add the `-l` flag in the hashbang header:

```sh
#!/bin/zsh -i -l
export
```

**Comment by Yorkshireman** [comment]
It worked! Brilliant, thanks @ferdaber

**Comment by nicolasrouanne** [comment]
Great workaround @ferdaber ! Is there something preventing the addition of the `-l` flag in the shebang for everyone? I could drop a PR if it's just that...

**Comment by bjelline** [comment]
Isn't `dist/` the wrong place to change something?

the file `src/util/env.ts` seems promising:

```
function getTemplate(shell: string): string {
	let template;
	if (isWindows()) {
		template = 'SET';
	} else {
		template = `#!${shell} -i -l\nexport`;   // <--- add the -l option here
	}

	return template;
}
```

did not work for me on mac os though, the shim-files `dist/server/shims/env.bin.{shell}.sh` are
not being generated

**Comment by ferdaber** [comment]
> Great workaround @ferdaber ! Is there something preventing the addition of the `-l` flag in the shebang for everyone? I could drop a PR if it's just that...

I think as long as `-l` is universal enough that most shells use the same letter for that login flag, it's fine. It does seem like the templating assumes that each shell has the same flag behavior.

**Comment by nratter** [comment]
> I took a different route an changed the function `getProcessEnv()` to change the ruby versions according to the settings in vscode.

can you give some more details on this?

**Comment by gregawoods** [comment]
I have this issue as well. The fix proposed by @ferdaber worked for me - however, I'd like to find a solution that doesn't require everyone on my team manually editing their vs code extensions. 

It seems to me in practice that whatever ruby version you have set as default (`rvm use [x.x.x] --default`) is what gets used by the language server. 

Would be really nice if a fix for this could be merged in. 🙂

**Comment by KoderMAL** [comment]
I had the following error: Bundler::RubyVersionMismatch
@ferdaber 's solution solved it: https://github.com/rubyide/vscode-ruby/issues/620#issuecomment-632857207

**Comment by Nowaker** [comment]
`#!/bin/zsh -i -l` did nothing to fix it for me.

Why does Ruby language server not pick the right Ruby version in the first place?

**Comment by JohnSmall** [comment]
I didn't even have a `dist/server/shims/env.bin.{shell}.sh` in `~/.vscode/extensions/rebornix.ruby-0.28.1` so I created it and put 

```
#!/bin/zsh -i -l
export
```
in it as suggested above. And....

It had no effect

Presumably because things have moved on since @ferdaber suggested the workaround in 2020, and the suggested workaround no longer works.

Does anyone have any suggestions how to fix this? 

My low tech workaround is to keep a separate terminal open running zsh and switch  from vscode to that when I run stuff.
