### ISSUE TITLE
"Go to definition" ignores module chain

### ISSUE THREAD

**Issue by henrahmagix** [rubyide/vscode-ruby#623]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-darwin19]
- Ruby version manager (if any): rbenv 1.1.2 
- VS Code version: 1.45.1
- Operating System: macOS 10.15.4
- Using language server? (eg `useLanguageServer` is true in your configuration?) yes

### Setup

```rb
# app/first.rb
module FirstModule
  class LovelyClass
  end
end
```
```rb
# app/second.rb
module SecondModule
  class LovelyClass
  end
end
```

### Expected behavior

cmd+click on `LovelyClass` (or right-click "Go to Definition") should go straight to `app/first.rb` because we're accessing it through `FirstModule`:
```rb
# app/something.rb
def something
  ::FirstModule::LovelyClass.new
  #              ^^^^^^^^^^^
end
```

### Actual behavior

Peek definition is opened with both `app/first.rb` and `app/second.rb` highlighting a `LovelyClass` definition:
![image](https://user-images.githubusercontent.com/1429026/83163975-92e9ef80-a103-11ea-8e99-39dc2a0fb8f0.png)

**Comment by henrahmagix** [comment]
@rebornix Could this issue be reopened please? I've been using this extension every workday (working solely on a ruby codebase) and I jump around the code a lot, so this would be really useful where we have lots of similarly named classes (like `Form`) but in unique module paths.

**Comment by 4ybakut2004** [comment]
@rebornix, @henrahmagix Yes, it's very inconvenient to get a list of classes instead of going directly to a class in a specific module. To avoid problems when going to the definition, i have to add suffixes to class names that duplicate the name of the module. For example:

```ruby
module FilmErrors
  class FilmUpdatingError; end
end

module GenreErrors
  class GenreUpdatingError; end
end
```

Because of this, the length of the string increases:

```ruby
FilmErrors::FilmUpdatingError.new
GenreErrors::GenreUpdatingError.new
```

Although it would be much more convenient to read the code like this, but go to declaration is broken:
```ruby
FilmErrors::UpdatingError.new
GenreErrors::UpdatingError.new
```
