### ISSUE TITLE
Support latest versions of rubyfmt

### ISSUE THREAD

**Issue by wadetandy** [rubyide/vscode-ruby#627]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: any
- Ruby version manager (if any): rvm
- VS Code version: 1.45.1
- Operating System: OSX
- Using language server? yes

### Expected behavior

I have installed the latest version of rubyfmt per the [readme instructions](https://github.com/penelopezone/rubyfmt#how-do-i-use-it), so it is available on my bash `PATH` as `rubyfmt`. I would expect this command to get run when the vscode formatter runs.

### Actual behavior

Per [this file](https://github.com/rubyide/vscode-ruby/blob/master/packages/language-server-ruby/src/formatters/RubyFMT.ts#L4), vscode-ruby embeds a much older version of rubyfmt, which the author notes as broken in https://github.com/penelopezone/rubyfmt/pull/201.

**Comment by wingrunr21** [comment]
I haven't looked at `rubyfmt` in a while. It looks like it is getting transitioned to something I shouldn't vendor any longer. I'll have to do some work to redo the integration to allow it to be external similar to other formatters.

**Comment by wadetandy** [comment]
@wingrunr21 Opened #628 to address this change.

**Comment by wingrunr21** [comment]
`v0.28.0` contains this support
