### ISSUE TITLE
Cannot debug programs that read from STDIN

### ISSUE THREAD

**Issue by kevcunnane** [rubyide/vscode-ruby#63]
### Your environment
- `vscode-ruby` version: 0.6.0
- Ruby version: 2.3.1
- VS Code version: 1.5.0-insider
- Operating System: MacOS

I'm trying to debug a basic Hello World app that requires basic console input (e.g. gets.chomp) via VSCode. The integrated Debug Console does not support user input so I'd like to launch an external console (this is supported in the Python and Node debuggers, for instance), but this does not seem to be currently supported. This would be a very nice feature for those getting started with Ruby who want to use VSCode.
### Expected behavior

launch.json has a "externalConsole": true option in the configuration that launches an the console as an external window. This matches the Node debugger behavior.
### Actual behavior

This option is not available so anything that uses gets will be blocked forever waiting for user input.

**Comment by rebornix** [comment]
@kevcunnane thanks for the issue report, we didn't catch up with Code API for a while but yes this is an valid request indeed.

**Comment by RalphMcTavish** [comment]
Any news on this feature?

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.

**Comment by Drew-Goddyn** [comment]
Does this feature request exist anywhere else or can it be re-opened? I'd like to be able to run my rspec debugger in the integrated terminals so I can have colors and styling.

**Comment by minkir014** [comment]
@Drew-Goddyn Have you ran into that issue again.

**Comment by arturotramontini** [comment]
debugging  ruby  as "Debug Local File"  gets stuck.
Some suggestion to resolve ?
Thanks.

**Comment by arturotramontini** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/15611649/86621270-301b2c00-bfbe-11ea-8a6e-9922edf24361.png)

**Comment by SolaWing** [comment]
use `rdebug-ide -- script.rb` to launch a rdebug server, and attach it with socket. this way can input and output from terminal, and debug also fine.
