### ISSUE TITLE
Debugger fails either with ECONNRESET or no error message on macOS

### ISSUE THREAD

**Issue by patrickkidd** [rubyide/vscode-ruby#649]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
- Ruby version manager (if any): rum
- VS Code version: 1.48.0
- Operating System: macOS Catalina 10.15.6
- Using language server? (eg `useLanguageServer` is true in your configuration?) tried with both yes and no

### Expected behavior

VS Code Debugger should run and connect to rails server

### Actual behavior

- On first run the following error is printed to the VS Code `Debugger` window: "Debugger error: Client: Error: read ECONNRESET"
- On subsequent runs, debugger quits without any output at all. Ruby process is left running until "killall -HUP ruby."

NOTE: The debugger documentation says to use "${workspaceRoot}/main.rb" for "program" in launch.json. A deep googling did not reveal any clear way to run a rails server from such a script, so I am resorting to the "bin/rails" script with the "server" argv.

launch.json: 

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "trace": true,
    "configurations": [
        {
            "name": "Rails server",
            "type": "Ruby",
            "request": "launch",
            "program": "/Users/patrick/.rvm/gems/ruby-2.6.3@triplynx/bin/rails",
            "cwd": "${workspaceRoot}",
            "env": {
                "PATH": "/Users/patrick/.rvm/gems/ruby-2.6.3@triplynx/bin:/Users/patrick/.rvm/gems/ruby-2.6.3@global/bin:/Users/patrick/.rvm/rubies/ruby-2.6.3/bin:/Users/patrick/.rvm/bin:/usr/local/opt/curl-openssl/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin",
                "GEM_HOME": "/Users/patrick/.rvm/gems/ruby-2.6.3@triplynx",
                "GEM_PATH": "/Users/patrick/.rvm/gems/ruby-2.6.3@triplynx:/Users/patrick/.rvm/gems/ruby-2.6.3@global",
                "RUBY_VERSION": "ruby-2.6.3"
            },
            "args": [
                "server"
            ]
        }
    ]
}
```

**Comment by patrickkidd** [comment]
For what it's worth, while I cannot get the debugger to launch and connect to a rails server, I am able to get the debugger to connect by starting the server with the following command...

```bundle exec rdebug-ide --debug --host 0.0.0.0 --port 1234 -- bin/rails s -p 3000 -b 0.0.0.0```

...and then using the following launch config in launch.json:

```
        {
            "name": "Listen for rdebug-ide",
            "type": "Ruby",
            "request": "attach",
            "remoteHost": "127.0.0.1",
            "remotePort": "1234",
            "remoteWorkspaceRoot": "${workspaceRoot}"
        },
```

**Comment by jonibatista** [comment]
I've the same problem when I try to attach  the debbuger to a rails 5.2 app (ruby 2.6.3) with VS Code (1.46).

I already added the fowling gems:
```

gem 'ruby-debug-ide', '~> 0.7.2'
gem 'debase', '~> 0.2.2'
```

and I successfully created a config that lunches the app in debugging, using VS Code
```

{
    "name": "Rails server",
    "type": "Ruby",
    "request": "launch",
    "program": "${workspaceRoot}/bin/rails",
    "args": [
        "server"
    ],
    "useBundler": true,
    "cwd": "${workspaceRoot}"
}
```

Then I wanted to create a attach configuration to avoid restarting the server.

The configuration looks like

```
{
    "name": "Attach rails server",
    "request": "attach",
    "type": "Ruby",
    "cwd": "${workspaceRoot}",
    "remoteHost": "127.0.0.1",
    "remotePort": "3000",
    "remoteWorkspaceRoot": "${workspaceRoot}",
}
```

but when I run it I get the following error in the Debugger console

`Debugger error: Client: Error: read ECONNRESET`

and a standard HttpParserError in my rails server

`HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>`

**Comment by exocode** [comment]
@jonibatista can you tell me what you did to solve that `HTTP parse error, malformed request (): #<Puma::HttpParserError: Invalid HTTP format, parsing fails.>` issue? 

I also try to start debugging Rails within a container (Kubernetes cluster). And have that same error message
