### ISSUE TITLE
Prompt user to install tools when necessary

### ISSUE THREAD

**Issue by chrisdias** [rubyide/vscode-ruby#65]
### Your environment
- `vscode-ruby` version: 0.6.0
- Ruby version: 2.3.1p112
- VS Code version: Insiders 1.6
- Operating System: OSX
- Hardware (optional): 

Install Ruby
Open VS code
Install Ruby extension
write simple `main.rb` file:

``` ruby
def hi(name)
   puts "Hello #{name}"
   end

hi("there")
```

Press F5 to create a `launch.json`
Choose the 'debug local file' option
Press F5 again

Result: Nothing happens
Expected: Prompt that says "ruby-debug-ide" is not installed 

Better yet, can we install this on first activation of the extension?

**Comment by rebornix** [comment]
@chrisdias thanks for reporting this issue! Yes a prompt will be better. 

The problem about auto-install `ruby-debug-ide` is the version we should install is dependent on Ruby version and OS users are using, which makes the auto installation somewhat unreliable. A proper solution in my mind right now is putting all the dependencies into container without asking users to install gems. I'll if I can integrate this part with vscode-docker.

**Comment by chrisdias** [comment]
yes, i can see this would be tricky.  but, taking a dependency on docker containers seems heavy. 

at a minimum, could you provide an information message when the user tries to debug, with a link to a wiki page on what tools are needed for a great experience?

**Comment by rebornix** [comment]
sure, it should be an easy fix. Thanks!

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
