### ISSUE TITLE
@do causes wrong syntax highlighting

### ISSUE THREAD

**Issue by Nowaker** [rubyide/vscode-ruby#658]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.6.3p62
- Ruby version manager (if any): rvm
- VS Code version: 1.49.1
- Operating System: Arch Linux
- Using language server? yes

### Actual behavior

![image](https://user-images.githubusercontent.com/611746/93824552-403fc080-fc29-11ea-9323-3daedd24d46d.png)

### Expected behavior

Proper syntax highlighting. `@do` is mistaken for `do`. `@do` is legal instance variable name, not a keyword, so it shouldn't cause this problem.

**Comment by wingrunr21** [comment]
Resolved by #660
