### ISSUE TITLE
Semantic Highlighting not enabled?

### ISSUE THREAD

**Issue by Wonderer0** [rubyide/vscode-ruby#659]
### Your environment

- `vscode-ruby` version:  0.27.0
- Ruby version: 2.6.6
- Ruby version manager (if any):
- VS Code version: 1.49.1
- Operating System: Windows 10 x64
- Using language server? (eg `useLanguageServer` is true in your configuration?) true
- Other Ruby Extensions
  - ruby-robocop 0.8.4
  - Ruby Solargraph 0.21.1

#### settings.json
Here are the relevant parts of settings.json that have been set.
```json
{
    "workbench.colorTheme": "Default Light+",
    "workbench.iconTheme": "vscode-great-icons",
    "window.zoomLevel": 0,
    "editor.semanticHighlighting.enabled": true,
    "editor.semanticTokenColorCustomizations": {
        "enabled": true,
        "rules": {
            "function.declaration": {
                "underline": true
            }
        }
    },
    "editor.tokenColorCustomizations": {
        "comments": "#FF0000",
        "functions": "#02b902",
    },
    // Ruby extension
    // --------------
    // Basic settings: turn linter(s) on
    "ruby.lint": {
        "reek": false,
        "rubocop": true,
        "ruby": false, //Runs ruby -wc
        "fasterer": false,
        "debride": false,
        "ruby-lint": false
    },
    "debride": {
        "rails": true //Add some rails call conversions.
    },
    "ruby-lint": {
        "levels": [ /* a subset of these */
            "error",
            "warning",
            "info"
        ],
        "classes": [ /* a subset of these */
            "argument_amount",
            "loop_keywords",
            "pedantics",
            "shadowing_variables",
            "undefined_methods",
            "undefined_variables",
            "unused_variables",
            "useless_equality_checks"
        ]
    },
    "rubocop": {
        "lint": true, //enable all lint cops.
        "only": [ /* array: Run only the specified cop(s) and/or cops in the specified departments. */],
        "except": [ /* array: Run all cops enabled by configuration except the specified cop(s) and/or departments. */],
        "require": [ /* array: Require Ruby files. */],
        "rails": false //Run extra rails cops
    },
    "ruby.locate": {
        "include": "**/*.rb",
        "exclude": "{**/@(test|spec|tmp|.*),**/@(test|spec|tmp|.*)/**,**/*_spec.rb}"
    },
    "ruby.useLanguageServer": true,
    "ruby.useBundler": false,
    "ruby.format": "rubocop",
    "[ruby]": {
        "editor.defaultFormatter": "misogi.ruby-rubocop"
    }
}
```
### Expected behavior
That in the text editor window:
* `Developer: Inspect Editor Tokens and Scopes` would show `semantic token type` etc in the pop-up when clicked on various tokens.
* Function definitions would be underlined, as specified in `editor.semanticTokenColorCustomizations`, and functions called without parameters would be recognised and coloured.

### Actual behaviour
* No semantic information was shown about tokens.
* Function definitions were not underlined, and functions called without parameters were not coloured.

These suggest that semantic highlighting is not working.  Are additional settings or packages required to enable it to do so?
(Semantic highlighting is working OK for Typescript)

### Code Sample
```
def foo
  puts 'Fooing'
end

foo

```

**Comment by wingrunr21** [comment]
I do not currently have support for semantic highlighting

**Comment by Wonderer0** [comment]
The Ruby (Peng Lv) extension has VSCode Ruby as a dependency, so I assumed that the semantic highlighting that the Ruby extension says it supports is provided by VSCode Ruby.  How is semantic highlighting enabled in Ruby, is it provided by a further extension?  I already have Rubocop and Ruby Solargraph installed and enabled.  Clicking on the Ruby extension's Repository button in VSCode opens this repository, so it's not clear where else to so for support.
