### ISSUE TITLE
IntelliSense dropdown when pressing dot

### ISSUE THREAD

**Issue by chrisdias** [rubyide/vscode-ruby#66]
### Your environment
- `vscode-ruby` version: 0.6.0
- Ruby version: 2+
- VS Code version: insiders 1.6 
- Operating System: osx
- Hardware (optional): 

I installed rcodetools per the extension readme.  

Assume the following code:

``` ruby
x = "hello"
x.
```
### Expected behavior

I expect the IntelliSense list to appear when i press `.`
### Actual behavior

I have to type in a character that matches something in the IntelliSense list (for example `c` for `capitalize`, but `x` doesn't do anything) or press Ctrl+Space to get IntelliSense to appear.  Languages such as JavaScript and TypeScript show the list on `.`

**Comment by HookyQR** [comment]
Should work with current version. Let us know how it is at your end now please @chrisdias.

**Comment by castwide** [comment]
This will work as of https://github.com/rubyide/vscode-ruby/pull/248.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
