### ISSUE TITLE
When language server starts, it is executing RuboCop lint with invalid option: -R

### ISSUE THREAD

**Issue by klueless-io** [rubyide/vscode-ruby#675]
### Your environment

- `vscode-ruby` version:
- Ruby version:  ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]
- Ruby version manager (if any): asdf 2.7.1
- VS Code version:

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:53:05.704Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

- Operating System:

Catalina. 10.15.6

- Using language server? (eg `useLanguageServer` is true in your configuration?)
useLanguageServer: true

### Expected behavior

Doesnt use the invalid option: -R

### Actual behavior

![image](https://user-images.githubusercontent.com/2956762/97764687-8f9bd980-1b63-11eb-9ae9-6f899613f5de.png)

**Comment by SkipKayhil** [comment]
See https://github.com/rubyide/vscode-ruby/issues/598#issuecomment-627704426
