### ISSUE TITLE
language server not working

### ISSUE THREAD

**Issue by futurepaycc** [rubyide/vscode-ruby#680]
### Your environment

- `vscode-ruby` version: 0.27.0
- Ruby version: 2.7.2p137
- Ruby version manager (if any): no
- VS Code version: 1.51.0
- Operating System: arch linux
- Using language server? (eg `useLanguageServer` is true in your configuration?) yes

### Expected behavior
code completion
### Actual behavior
nothing,log stuck:

`[Info  - 4:04:49 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /home/liunix/.vscode/extensions/rebornix.ruby-0.27.0/dist/server/tree-sitter-ruby.wasm`

![ruby_lsp](https://user-images.githubusercontent.com/9865554/99179944-fc66c480-275c-11eb-8ca1-70bacea8a4c6.png)

**Comment by RB-Lab** [comment]
I've been experiencing the same issue (which for me was manifesting itself in not working syntax errors highlighting) until I came across this issue. I've noticed that in my console I see similar input for Language server. Than I decided to check, if errors would be highlighted if I disable language server. And indeed, when I've disabled language server for Ruby, errors start to be highlighted. Then I've enabled server back, to copy console output here. Here it is:
```
[Info  - 12:01:12 PM] Initializing Ruby language server...
Loading Ruby tree-sitter syntax from /home/***/.vscode/extensions/rebornix.ruby-0.27.0/dist/server/tree-sitter-ruby.wasm
```
However syntax checks seem to be working now, with language server enabled. So does the code completion.
Apparently
a) `[Info  - 12:01:12 PM] Initializing Ruby language server...` is not supposed to end with `[OK]` or something
b) disabling and re-enabling language server could fix the problem.

P.S. I'm on Ubuntu, so maybe it is something Linux-related. 
P.P.S VS Code version is 1.51.1

**Comment by rjmascolo** [comment]
I am getting the same error. This started happening yesterday.
![Screen Shot 2020-11-17 at 10 43 11 AM](https://user-images.githubusercontent.com/8290015/99411628-d27ae280-28c1-11eb-8fda-2672d6575d82.png)
![Screen Shot 2020-11-17 at 10 43 41 AM](https://user-images.githubusercontent.com/8290015/99411635-d4dd3c80-28c1-11eb-840d-eaf7cfeefb3b.png)
