### ISSUE TITLE
Language server lint cannot use command from workspace folder starting from version 0.28.0

### ISSUE THREAD

**Issue by frullah** [rubyide/vscode-ruby#697]
### Your environment

- vscode `ruby` version: 0.28.0
- Ruby version: 3.0.0
- Ruby version manager (if any): rbenv
- VS Code version: 1.52.1
- Operating System: Arch Linux
- Using language server? yes

using command for lint from workspace folder does not work starting from `ruby` extension version 0.28.0 

### Expected behavior

lint works as well as `ruby` extension version 0.27.0 do

Lint: executing bin/standardrb -s /home/... -f json --no-fix...
Running via Spring preloader in process 34801

### Actual behavior

Lint: unable to execute bin/standardrb -s '/home/...' -f json --no-fix as the command could not be found

**Comment by whysthatso** [comment]
i see the same problem, running fish shell
