### ISSUE TITLE
Linter doesn't work with rubocop-daemon-wrapper

### ISSUE THREAD

**Issue by orthodoX** [rubyide/vscode-ruby#700]
### Your environment

- `vscode-ruby` version: 0.28.1
- Ruby version: 2.6.6
- Ruby version manager (if any): asdf
- VS Code version: 1.52.1
- Operating System: macOS Big Sur 11.1
- Using language server? (eg `useLanguageServer` is true in your configuration?) yes

### Expected behavior
Linting works with `/usr/local/bin/rubocop-daemon-wrapper/rubocop` the same as with local rubocop exec.

### Actual behavior

I switched today to using `rubocop-daemon` with the wrapper since it's much much faster. I created a symlink `ln -fs /usr/local/bin/rubocop-daemon-wrapper /Users/orthodox/.asdf/shims/rubocop` and the format on save started working 
blazing fast.

But the linter is stopped working. When I check the output, it states `Lint: Received invalid JSON from rubocop.` When I switched the linter config to point to a local rubocop gem, not the daemon, the linter started working again. With delays, of course, due to local rubocop execution speed. I compared the json returned by the daemon-wrapper and local rubocop and they are exactly the same:
```json
{
  "metadata": {
    "rubocop_version": "1.8.1",
    "ruby_engine": "ruby",
    "ruby_version": "2.6.6",
    "ruby_patchlevel": "146",
    "ruby_platform": "x86_64-darwin20"
  },
  "files": [
    {
      "path": "app/controllers/admin/reporting_controller.rb",
      "offenses": [
        {
          "severity": "convention",
          "message": "Inconsistent indentation detected.",
          "cop_name": "Layout/IndentationConsistency",
          "corrected": false,
          "correctable": true,
          "location": {
            "start_line": 11,
            "start_column": 11,
            "last_line": 13,
            "last_column": 11,
            "length": 154,
            "line": 11,
            "column": 11
          }
        },
        {
          "severity": "convention",
          "message": "`end` at 13, 8 is not aligned with `m.failure(:report_not_selected) do` at 11, 10.",
          "cop_name": "Layout/BlockAlignment",
          "corrected": false,
          "correctable": true,
          "location": {
            "start_line": 13,
            "start_column": 9,
            "last_line": 13,
            "last_column": 11,
            "length": 3,
            "line": 13,
            "column": 9
          }
        }
      ]
    }
  ],
  "summary": {
    "offense_count": 2,
    "target_file_count": 1,
    "inspected_file_count": 1
  }
}
```
So I have no idea what is invalid there. The daemon wrapper and local rubocop versions are the same.

**Comment by nwoeddie** [comment]
@orthodoX try this:
```bash
ln -fs /usr/local/bin/rubocop-daemon-wrapper $(asdf which rubocop)
```

**Comment by orthodoX** [comment]
@nwoeddie Hi, thanks for suggestion. I've tried the above and I still get the same error on linting. Formatting still works.

**Comment by orthodoX** [comment]
I've just retried this on Ruby 3.0.1 on macOS 11.3 running on Apple Silicon chip and it's the same error.
