### ISSUE TITLE
In VSCode, rubocop linter doesn't show the Rails/HasManyOrHasOneDependent cop

### ISSUE THREAD

**Issue by prdetective** [rubyide/vscode-ruby#713]
### Your environment

- `vscode-ruby` version: v0.28.1
- Ruby version: 3.0.0p0
- Ruby version manager (if any): rbenv
- VS Code version: 1.54.2
- Operating System: Mac Os 11.2.2
- Using language server? yes

### Expected behavior

I have the rubocop and rubocop-rails gems installed. `.rubocop.yml` file has `require: rubocop-rails` string. Rails cops work fine in console and in VSCode.

Creating a file:
```ruby
class User < ApplicationRecord
  has_many :messages
end
```

If I run the rubocop from the console I see the cop as expected:

```
Rails/HasManyOrHasOneDependent: Specify a :dependent option.
```

It should warn about this in VSCode too.

### Actual behavior

Linter is being run, but the line with the cop stays w/o any error indication. If I add other problematic lines, they get underlined just fine.

**Comment by prdetective** [comment]
Additionally, if I try to disable this cop locally, I get the `Unnecessary disabling of Rails/HasManyOrHasOneDependent.` error.

**Comment by FooBarWidget** [comment]
I think this issue is a duplicate of #227 (of which the root cause is #719).
