### ISSUE TITLE
autocomplete not working inside methods

### ISSUE THREAD

**Issue by didacusAbella** [rubyide/vscode-ruby#72]
### Your environment
- `vscode-ruby` version: 0.8.0
- Ruby version: 2.3.1p112
- VS Code version: 1.5.3
- Operating System: AntergosOS
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !
### Expected behavior

when i use a variable and call autocomplete it should list all methods of this variable
### Actual behavior

autocomplete work only if the variable is outside the method
### Steps to reproduce the problem

[1, 2, 3].e  => inside a method does nothing
[1, 2, 3].e => outside methods autocomplete works as expected

**Comment by HookyQR** [comment]
Seems rctools hasn't lived up to what we were hoping for. It's all we have right now, sorry.

**Comment by Mexxerio** [comment]
@HookyQR Did you look into using https://github.com/rsense/rsense instead of rctools?

**Comment by HookyQR** [comment]
@rebornix was looking into this early on. I have been focusing on staying an implementation that doesn't have to rely on ruby calls. That's a long way off though.

Pinging @mattn and @rebornix for this.

**Comment by sunnyrjuneja** [comment]
Just as a heads up, rsense is very dead. In case you're ready to maintain the project, I don't think it's worth integrating.

Not to hijack this thread but I just want to know if you can point me to where rctools is hosted. I did a quick google search and couldn't find anything.

**Comment by mattn** [comment]
Currently, I'm contributor of rcodetools. But still not fixed. Patches welcome!

https://github.com/rcodetools/rcodetools

**Comment by dgutov** [comment]
If I'm reading rcodetools' documentation right, it expects to be able to hook into your tests, and run the tests corresponding to the current class during completion, to analyze its methods.

Example: https://github.com/rcodetools/rcodetools/blob/8ac2a25c975d7377c10822b0159c43b3b5401340/test/data/rct-complete-TDC/completion_in_method__testscript.taf

Not sure I like this approach, personally.

**Comment by didacusAbella** [comment]
Are there any updates for resolve this problem?

**Comment by hackhowtofaq** [comment]
FYI I find this promising https://github.com/castwide/solargraph

**Comment by castwide** [comment]
https://github.com/rubyide/vscode-ruby/pull/248 should resolve this issue.

**Comment by mattn** [comment]
@castwide thank you. After I sent PR to enable completion on vscode with rcodetoolsI became the maintainer of rcodetools, but since it is too old and flaky, I had hesitant to release fix.

**Comment by didacusAbella** [comment]
Perfect. I'm very happy that @castwide extension is used in combination with this project. I close the issue because the problem is solved
