### ISSUE TITLE
Wrong indent with `end` symbol or arguments with line break

### ISSUE THREAD

**Issue by amerov** [rubyide/vscode-ruby#740]
### Your environment

- `vscode-ruby` version: 0.28.1
- Ruby version: 2.71.
- Ruby version manager: rvm
- VS Code version: 1.56.2
- Operating System: Linux
- Using language server?: yes 

### Expected behavior
indent correctly
### Actual behavior
C-p: Indent lines action result:
```ruby
class Myapp
  def path
    return MyLib1.info unless can_access?
    params = {
      param1: 'aaa',
    end: 'bbbb'
  }
end
end
```

# UPD 2021-06-26
Another example that wrongly indented after "Reindent lines" command: 
```ruby
describe MyApp do
  let(:user) do
    User.create(name: 'User name 1', bday: '1988 06 01', country: 'Russia',
      active: true)
  end
end
```

**Comment by wingrunr21** [comment]
What formatter are you using?

**Comment by amerov** [comment]
> What formatter are you using?

C-p Reindent lines
