### ISSUE TITLE
Automatic Syntax Highlighting in ERB based on document format?

### ISSUE THREAD

**Issue by OmriSama** [rubyide/vscode-ruby#741]
Hey. I was wondering if it's possible to create rules that will allow you to use ERB in every file while still retaining the original file's markup/syntax highlighting. `file.md.erb` will have Markdown syntax highlighting, etc.

Are there any blockers on the VS Code side?

**Comment by OmriSama** [comment]
@wingrunr21 @rebornix any chance this could be looked at? Do you folks happen to know what VS Code allows in terms of dynamic grammar definitions?

**Comment by wingrunr21** [comment]
We have to specify in the language definition embedded languages but I’m not aware of a way to do this dynamically or based on the file type as would be Rails convention.

see [embedded languages](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages)
