### ISSUE TITLE
Doubt Standard and rubocop projects

### ISSUE THREAD

**Issue by igorgesso** [rubyide/vscode-ruby#743]
I have projects that use standard and other rubocop, as I configure it to be smart and know which one to use in each project and not have to keep changing it

**Comment by wingrunr21** [comment]
I'm not following the ask here. Are you needing guidance on how to configure different projects to use rubocop or standard and not have to update your user settings?

**Comment by igorgesso** [comment]
I think that would be it, how can I configure different projects to use different linters.

**Comment by igorgesso** [comment]
I didn't know about vscode's workspace functionality. I managed using the workspace.
