### ISSUE TITLE
"go to the definition" does not find method definition

### ISSUE THREAD

**Issue by MathieuDerelle** [rubyide/vscode-ruby#746]
### Your environment

- `vscode-ruby` version: v0.28.1
- Ruby version: 2.4.10 
- Ruby version manager (if any): rvm
- VS Code version: 1.57.0
- Operating System: macOS Catalina 10.15.7 (Darwin x64 19.6.0)
- Using language server? no

### Expected behavior

```ruby
# app/asynctasks/check_pending_collections.rb

    deadends = []
    UserCollection
      .uncompleted
      .includes(:collected_items, collection: :collection_items)
      .find_each do |uc|
        deadends << uc if uc.all_pieces_collected?
      end
```

cmd+clic on `all_pieces_collected?` should go to the definition of the method (or show all the definitions)

### Actual behavior

The method definition is not found
![image](https://user-images.githubusercontent.com/16286023/122545332-0374ee80-d02e-11eb-8fc7-90cf8d23178b.png)

but it's defined in a concern

```ruby
# app/models/concerns/user_collections/completion.rb

    def all_pieces_collected?
      collected_item_ids.uniq.sort == collection.collection_item_ids.sort
    end
```

That's a big repo, is it possible that the files indexed are limited by the size of the repo ?
I've got other projects where "go to definitions" finds all the definitions for a given method name, list them all and let's me choose between them

**Comment by MathieuDerelle** [comment]
I've found those issues 
- https://github.com/rubyide/vscode-ruby/issues/294
- https://github.com/microsoft/vscode/issues/45915

and I can confirm I have `"ruby.intellisense": "rubyLocate",`

**Comment by MathieuDerelle** [comment]
still happening

**Comment by gastonmorixe** [comment]
+1
