### ISSUE TITLE
Bring in upstream changes

### ISSUE THREAD

**Issue by sandstrom** [rubyide/vscode-ruby#748]
The syntax is currently based on an old version of the ruby grammar (see commit below), from 2018.

https://github.com/rubyide/vscode-ruby/blob/da0d5d4d8d5b2d3ed3b57112e7e32a3645ef7da6/packages/vscode-ruby/syntaxes/ruby.cson.json#L3-L7

There has been some [changes](https://github.com/atom/language-ruby/commits/master/grammars/ruby.cson) in the upstream files, how about bringing this repo/file up to date?

***

Also, somewhat related, but since Atom is basically abandonware now (declining usage over time), at some point you should probably consider detaching yourself from `atom/language-ruby` and take PRs directly onto this repo. When you do, it would probably make sense to look at [tree-sitter](https://tree-sitter.github.io/tree-sitter/syntax-highlighting), and see if it's better to use them (somehow).

**Comment by wingrunr21** [comment]
You need to look at the commit history on that grammar and what the language server is using.

**Comment by sandstrom** [comment]
alright, thanks @wingrunr21
