### ISSUE TITLE
'Show Language Server Output Channel' and 'Show Output' commands are failing

### ISSUE THREAD

**Issue by andyw8** [rubyide/vscode-ruby#750]
### Your environment

- `vscode-ruby` version: 0.28.0
- Ruby version: 2.7.4
- Ruby version manager (if any): chruby
- VS Code version:  1.5.8
- Operating System: Mac OS 11.4
- Using language server? (eg `useLanguageServer` is true in your configuration?)

### Expected behavior

Following these instructions:

https://github.com/rubyide/vscode-ruby/blob/main/docs/troubleshooting.md

I should see the output channels.

### Actual behavior

Both commands fail with an error:

* Command 'Ruby: Show Language Server Output Channel' resulted in an error (command 'ruby.showLanguageServerOutputChannel' not found)
* Command 'Ruby: Show Output Channel' resulted in an error (command 'ruby.showOutputChannel' not found)

A similar problem was reported in https://github.com/rubyide/vscode-ruby/issues/674 but for me restarting does not solve it.

**Comment by islamhanafi94** [comment]
@andyw8 did you come up with a solution for this ?

**Comment by Zeroxk** [comment]
Encountering same issue with these settings:
OS: Windows 10 using WSL2 Debian Bullseye
VScode 1.63.2
vscode-ruby v0.28.0
Ruby version manager (if any): rvm
Using language server? Yes

**Comment by andyw8** [comment]
> @andyw8 did you come up with a solution for this ?

I think the cause was attempting to run "Ruby: Show Output Channel - opens output channel for the Ruby extension" or "Ruby: Show Language Server Output Channel" before I had opened any Ruby files in the current VS Code session.

**Comment by wingrunr21** [comment]
VSCode won’t activate the extension until a Ruby file has been opened, so the command not working would be expected.

I will reopen to get some more info from the other comments here.

**Comment by mariliah** [comment]
Has anybody figured this out?

**Comment by harryuan65** [comment]
well, I forgot to turn on `useLanguageServer`
this works for me now
```json
    "ruby.useLanguageServer": true,
    "ruby.languageServer": {
        "logLevel": "info"
    },
```

<img width="398" alt="image" src="https://user-images.githubusercontent.com/33657734/157369512-c007ca10-0639-4124-8746-e3d56bc3f896.png">

**Comment by wingrunr21** [comment]
I am going to close this issue. Thanks all.
