### ISSUE TITLE
[RFE] add envFile / .env support

### ISSUE THREAD

**Issue by thoraxe** [rubyide/vscode-ruby#752]
Currelntly, `env` is supported and [documented here](https://github.com/rubyide/vscode-ruby/wiki/2.-Launching-from-VS-Code#env)

However, `envFile` support doesn't appear to be present similar to Node:
https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_load-environment-variables-from-external-file

It would be nice to get `.env` support. The "workaround" is to connect to an existing rdebug session. Committing env vars to source code is not ideal, especially in development where they frequently change.

**Comment by 0x2C6** [comment]
any news?
