### ISSUE TITLE
Ruby linting broken - invalid value in default settings

### ISSUE THREAD

**Issue by fredgoya** [rubyide/vscode-ruby#76]
### Your environment

- `vscode-ruby` version: 0.8.0
- Ruby version: ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin12.0]
- VS Code version: 1.5.3
- Operating System: OSX El Capitan
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
editors should show rubocop lint output

### Actual behavior
after latest update and restart of VS Code, editing 'user settings' or 'workspace settings' produces a single item in the warnings pane reading 'Value is not an accepted value. Valid values: ["rubocop"] (767, 20)'

The default settings can't be edited, so this error can't be fixed.

### Steps to reproduce the problem
Install vscode-ruby
Open user or workspace settings
![ruby_default_settings_invalid](https://cloud.githubusercontent.com/assets/16245823/19167310/e87ae97a-8bbf-11e6-918e-5f49ebc50911.png)

**Comment by HookyQR** [comment]
Hmm, that shouldn't have stopped linting. We're still waiting on @rebornix to publish the last couple of changes (I don't have access to publish to the marketplace for this repo) so getting a fix in may take a while anyway. I'll look into a work around if necessary.

**Comment by fredgoya** [comment]
You know what, you're absolutely right. I had inadvertently written a bad change to my ~/.rubocop.yml file, but the process was still linting until I restarted VSCode after updating the extension (so it looked like the issue was caused by the update). Fixing .rubocop.yml restored linting, so I've updated the issue description to just include the "invalid setting" warning.

**Comment by rebornix** [comment]
@HookyQR @fredgoya I've already published 0.9.0 please take a look if you can update the ext to latest one and see if the problem still exists :)
