### ISSUE TITLE
Huge system load due to permanent linting

### ISSUE THREAD

**Issue by artem-sidorenko** [rubyide/vscode-ruby#77]
### Your environment

- `vscode-ruby` version: 0.9.0
- Ruby version: 2.3.1
- VS Code version: 1.5.2
- Operating System: Linux Mint 18
- Hardware (optional): X220

vscode-ruby configuration:
```json
    "ruby.lint": {
        "rubocop": true,
        "debride": true,
        "ruby": true,
        "reek": true,
        "fasterer": true
    }
```

### Expected behavior
Linters are called during file opening/saving only. If linters are called during the file modification, they should be throttled to avoid linters call 20 times for 20 characters.

### Actual behavior
Assumption: linters are called for each file modification. If I type something pretty fast, I run into a huge system load and have to wait a bit for a cooldown :)
![screenshot from 2016-10-11 08-30-54](https://cloud.githubusercontent.com/assets/1645670/19261049/edbf5560-8f8e-11e6-8338-00a73841159c.png)
![screenshot from 2016-10-11 08-37-29](https://cloud.githubusercontent.com/assets/1645670/19261050/edc1d1aa-8f8e-11e6-9aa6-d1003cf23a1d.png)

### Steps to reproduce the problem
- Install and enable all linters
- Run "top" and press "c"
- Create some ruby file
- Type very fast some code with 10 lines
- Take a look to the "top"

**Comment by HookyQR** [comment]
Ouch. Could totally use some work. I'm planning on working on this extension a little this weekend. I'll put some focus into this area.

**Comment by HookyQR** [comment]
This is working out to be a substantial refactor to get this to work right. May not be ready for another week.

**Comment by artem-sidorenko** [comment]
many thx! :-)
