### ISSUE TITLE
The extension set by default is undesirable

### ISSUE THREAD

**Issue by noko1024** [rubyide/vscode-ruby#770]
### Your environment

- `vscode-ruby` version: 0.28.0
- Ruby version: ruby 3.0.2p107
- VS Code version: 1.60.2
- Operating System: Windows10 21H1

### Expected behavior
When you create a new file and save it, it will be saved as hoge.rb

### Actual behavior
When you create a new file and save it, it will be saved as hoge.arb

I want to Request a correction or explanation please.

**Comment by bcaplan** [comment]
Adding a comment to keep this open since I'm also experiencing this.

* `vscode-ruby` version: 0.28.1
* Ruby version: multiple
* VS Code version: 1.62.3
* Operating System: macOS 10.14.6

**Comment by Birdie0** [comment]
It seems `.arb` [being first in the list of extensions](https://github.com/rubyide/vscode-ruby/blob/main/packages/vscode-ruby/package.json#L72) is the reason why this happens. Is alphabetic order really required there, if not this can be easily fixed by moving `.rb` extension to the top.
