### ISSUE TITLE
Support no folder debugging

### ISSUE THREAD

**Issue by isidorn** [rubyide/vscode-ruby#771]
Hi VS Code PM here 👋 

1. Purple no folder VS Code -> create a new ruby file
2. Press `F5` -> notice how we offer the user to download your extension 👏 
3. Now the user presses `F5` again and wants to debug, but nothing happens since ruby is not supporting no folder debugging

Easiest to do this is to have a dynamic `resolveDebugConfiguartion` that will provide a launch configuration on the fly. [Example](https://github.com/microsoft/vscode-mock-debug/blob/main/src/activateMockDebug.ts#L161)

Apart from that consider contributing to the Editor title area menu, such that a Play button would appear in the Editor Title area (picture below). Example how to do this https://github.com/microsoft/vscode-mock-debug/blob/main/package.json#L80

I think both of these are super important and would really love that we improve this experience 💯  
Let me know if I can help somehow. I am also open to a quick 30 min meeting where we can discuss about the new cool VS Code debug features that ruby could potentially adopt.

**Comment by isidorn** [comment]
@wingrunr21 I find it weird that issues just get auto closed with no response from maintainers at all.

**Comment by wingrunr21** [comment]
@isidorn the bot probably needs adjusted

as to the other: remember this isn’t my job. Are you doing this in your free time?

**Comment by isidorn** [comment]
If you do not have time to tackle this - maybe put a "help-wanted" label and somebody from the community might chime in. At least that is what we do on the VS Code side.
