### ISSUE TITLE
Autocomplete not working with Rails/Rbenv

### ISSUE THREAD

**Issue by guiloyins** [rubyide/vscode-ruby#78]
### Your environment

- `vscode-ruby` version: 0.9.0
- Ruby version: 2.3.1p112
- VS Code version: 1.6.0
- Operating System: OS X El Captain
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior
When I type ```[1, 2, 3].e``` inside a Rails model/controller is expected to trigger autocomplete.

### Actual behavior
Actually nothing happens in editor. In dev degub console show the following error:
```
shell.ts:441 /Users/guiloyins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:166:in `runtime_data_with_class': -:1:in `<main>': uninitialized constant ActiveRecord (NameError) (Rcodetools::ProcessParticularLine::NewCodeError)
	from /Users/guiloyins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:287:in `candidates_with_class'
	from /Users/guiloyins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:295:in `candidates'
	from /Users/guiloyins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:313:in `completion_code'
	from /Users/guiloyins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rcodetools-0.8.5.0/lib/rcodetools/completion.rb:206:in `run'
	from /Users/guiloyins/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rcodetools-0.8.5.0/bin/rct-complete:45:in `<top (required)>'
	from /Users/guiloyins/.rbenv/versions/2.3.1/bin/rct-complete:22:in `load'
	from /Users/guiloyins/.rbenv/versions/2.3.1/bin/rct-complete:22:in `<main>'
```

If the file edited is a regular ruby file the autocomplete works as expected.

### Steps to reproduce the problem
Setup a rails project with rbenv. Inside a controller, model and etc, and follow the steps on docs.
I don't know if I am doing something wrong and there is so little information about rcodetools and rails/rbenv on internet.

**Comment by HookyQR** [comment]
rctools pretty much doesn't work with rails. I'm working on various other ways of getting better code completion for ruby (and rails) without having to call outside of javascript. It's a long way from  complete yet though, so for now, we have what we have.
🙁 👎 🛠

**Comment by guiloyins** [comment]
Thank you @HookyQR. 
Since the creation of this issue I was playing around with rcodetools and, despite the fact that was promissing sometimes, I wasnt able to make it work on all situation. And it seems that every other autocomplete lib for ruby is abandoned as well, like Rsense. For now, only the RubyMine seems to work as expected.

Thank you anyway and I am eager to see your new way for this autocomplete issue. 
Maybe we can close this issue right now as it seems that nothing can be done.

**Comment by HookyQR** [comment]
Thanks for your feedback @guiloyins.
