### ISSUE TITLE
Environment Failing

### ISSUE THREAD

**Issue by Conor-Developer** [rubyide/vscode-ruby#787]
### Your environment

- `vscode-ruby` version: v0.28.0
- Ruby version: v0.28.1
- Ruby version manager (if any):
- VS Code version: 1.63.2
- Operating System: Unbuntu 20.04.3 LTS
- Using language server? (eg `useLanguageServer` is true in your configuration?) No

### Expected behavior

Rubocop gem (not extension!) to highlight errors in VS Code.

### Actual behavior

Rubocop gem (not extension!) is not highlighting my code in VS Code. It appears the environment is failing? This issue will be present if you open VS Code separately and then open a Ruby file via the terminal. 

There is a workaround which involves:

1) Locate your chosen ruby file via the  OS terminal (but do not open)
2) Opening VS Code software via the command "code ."
3) Select your file within VS Code. 
4) This will allow Rubocop to work correctly and show any formatting errors. 

Not working:
![image](https://user-images.githubusercontent.com/29331827/148051351-e0774729-bb3c-4ba0-aec2-e966e9b53ab2.png)

Working (via instructions given in 'Actual Behaviour' section:
![image](https://user-images.githubusercontent.com/29331827/148051427-60f27659-b312-4365-862d-056ab2a1ff1f.png)

**Comment by wingrunr21** [comment]
Did you look at the logs?
