### ISSUE TITLE
Bundler::Dsl::DSLError

### ISSUE THREAD

**Issue by resistorsoftware** [rubyide/vscode-ruby#789]
### Your environment

- `vscode-ruby` version: 0.28.1
- Ruby version: 3.1.0
- Ruby version manager (if any): RVM
- VS Code version: 1.63.2
- Operating System: MacOS 12
- Using language server? (eg `useLanguageServer` is true in your configuration?) true

### Expected behavior

in terminal outside VSCode, no issues with GemFile

### Actual behavior

inside VSCode, the OUTPUT tab has problems with the Gemfile, specifically, it is unable to parse it. 

    /Users/fiddle/Documents/Workspace/Apps/uexpress/Gemfile:4:in `read':  (Bundler::Dsl::DSLError)
    [!] There was an error parsing `Gemfile`: No such file or directory @ rb_sysopen - .ruby-version. Bundler cannot continue.

     #  from /Users/fiddle/Documents/Workspace/Apps/uexpress/Gemfile:4
     #  -------------------------------------------
     #  
     >  ruby File.read('.ruby-version').chomp
     #  
     #  -------------------------------------------
	from /Users/fiddle/Documents/Workspace/Apps/uexpress/Gemfile:4:in `eval_gemfile'
	from /Users/fiddle/.rvm/rubies/ruby-3.1.0/lib/ruby/3.1.0/bundler/dsl.rb:49:in `instance_eval'
	
The file does exist, and that code is fine... but not inside VSCode and the Ruby Language Server. What is wrong with my configuration of this plugin? I have no idea where to start looking other than to assume this all has to do with using RVM, 

*This and the next section should include screenshots, code samples, console output, etc. The more information we have to reproduce the better!*
*If this is a syntax highlighting report please include a code sample that can be quickly copied and pasted!*

**Comment by palexvs** [comment]
I have the same issue in the latest version `0.28.1`

**Comment by palexvs** [comment]
Rollbacked to 0.27.0 that seems like is working

**Comment by resistorsoftware** [comment]
I have given up, come back, given up, come back, and am ready to give up again, on VSCode. It just can't seem to get certain things right. I am sure it works aces on simple projects and certain use patterns. But with Ruby and the various extensions we get, it's just not able to keep up.
