### ISSUE TITLE
GoTo definition seems very crude

### ISSUE THREAD

**Issue by mleopold** [rubyide/vscode-ruby#79]
### Your environment
- `vscode-ruby` version: 0.9.0
- Ruby version: 2.3.1p112
- VS Code version: 1.6.1
- Operating System: Ubuntu 16.04
### Behavior

Using the files below I hit F12 to goto definition - I'm execting the cursor to jump 2 lines up, but instead I'm taken to a different file that has a function with a name clash
### Steps to reproduce the problem

I've created a project with two files: hest.rb/horse.rb. One is not included in the other and there is a variable name that has a name clash.

hest.rb

```
module Hest
  # something
  class MyClass
    def self.hest(filename, opts = {})
      content_hash = opts['content_hash']
      puts filename
      puts content_hash
    end
  end
end
```

horse.rb

```
def content_hash
   'asdf'
end
```

**Comment by HookyQR** [comment]
The go to definition only understands methods at this stage. So setting a variable with the same name won't get found by the parser. Had you set a method with the same name, it would have found both methods, which is still not the ideal behaviour, but it's better than the nothing we had before.

We know there is a lot of work to do, but we're working on it.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
