### ISSUE TITLE
No release in 15+ months - need help?

### ISSUE THREAD

**Issue by gareth** [rubyide/vscode-ruby#811]
The last release to this extension was [January 8th 2021](https://github.com/rubyide/vscode-ruby/releases/tag/v0.28.1). Since then a number of useful issues have been fixed (the one I'm personally interested in is #720)

Can you quickly summarise what's blocking another release? For example, are there concerns with the merged code that you don't want to release; are there other things that you need to do before you can make a new version; is the releasing process an annoying mess; do you just not have enough time to look at the extension right now?

If the community can help then it would be useful to know what help you need. This is a well-used extension and I think we all want it to be up-to-date and as good as it can be :)

**Comment by gareth** [comment]
I just spotted [this commit](https://github.com/rubyide/vscode-ruby/commit/dc81c809c82003d26af9c4dc7c89fa8f8a26cbf5) ("**LOOKING FOR MAINTAINERS**") which should help anyone else who finds/is watching this issue understand the state

**Comment by benzado** [comment]
I just spent a few hours debugging something that had already been fixed on `main` but not released (see [here](https://github.com/rubyide/vscode-ruby/issues/578#issuecomment-1104070993)).

@wingrunr21 - has anyone volunteered to be a maintainer yet? Have you reached out directly to any of the 86 contributors?

@rebornix - are you the owner of the rubyide org on GitHub, or just the only public member?

I have no prior experience with TypeScript or VSC extension development, but I volunteer to cut a release if no one else will.

**Comment by wingrunr21** [comment]
I have had no one email me yet, no. No, I'm not going to email the 86 contributors.

I am the owner of the rubyide org

**Comment by wingrunr21** [comment]
@benzado it isn't just cutting the release, it's providing support, debugging people's environments, etc after the release is cut. Cutting the release is straight forward.

**Comment by wingrunr21** [comment]
#815

**Comment by benzado** [comment]
@wingrunr21 Believe me, I know how much work is involved and how much it can take out of you. I don't blame you for wanting to step away. Not one bit.

**Comment by drewlustro** [comment]
In lieu of the maintainer willing to make a release, does anyone know how to install a VSCode extension using `organization/repo#commit` syntax?
