### ISSUE TITLE
LOOKING FOR MAINTAINERS

### ISSUE THREAD

**Issue by wingrunr21** [rubyide/vscode-ruby#815]
I don't have any time to maintain this extension. I'm not able to keep up with VSCode development + the Ruby community + provide support for this extension alone, in my limited free time. Thus, I'm looking for some folks to step in and assist with this extension.

If you are interested, please get in touch with me (info is available via my Github profile).

**Comment by benzado** [comment]
I'm willing to volunteer my time. I shouldn't take a lead role because I don't have much TypeScript or VSC extension knowledge. But I know enough to troubleshoot and I can review PRs. If others are stepping up, I can be a resource.

**Comment by asciito** [comment]
Hi, I'm new to Ruby but it would be a pleasure to help you.
Please Let me know if I can help with something.

**Comment by drewlustro** [comment]
Also down to help 👋

**Comment by obahareth** [comment]
I'm available to help on an occasional basis, I have OK Typescript knowledge and I've been using Ruby for quite a few years. I do lack knowledge in VS Code Extensions though.

**Comment by bv-ankit** [comment]
I am willing to assist to maintain this extension considering the impact that it is making.
I have no experience in VS Code extension development, but I should be able to quickly learn anything that is required.

**Comment by Ankk98** [comment]
I am willing to assist to maintain this extension considering the impact that it is making.
I have no experience in VS Code extension development, but I should be able to quickly learn anything that is required.

**Comment by bessey** [comment]
I'll put my name in the hat too, on an occasional basis anyway

**Comment by simonc** [comment]
Hi. Since [Ruby LSP](https://github.com/Shopify/vscode-ruby-lsp) was recently announced, does it mean this package is definitely dead? ❤️

**Comment by wingrunr21** [comment]
Yes, it does. I will be marking this deprecated on the VSCode marketplace as well as archiving this repo. The Ruby based LSPs are a significantly superior developer experience than using TypeScript + tree-sitter to perform the analysis (given Ruby's ability to self-introspect)

**Comment by bessey** [comment]
I'm excited to see so much new development in Ruby tooling thanks to Shopify and Github. Still, may I say sincerely, thank you for your years of contributions to the Ruby community @wingrunr21 and @rebornix. I can only imagine how much pressure it is to be the sole maintainer for the most popular Ruby extension in one of the most popular editors in the world!

Much love ❤️

**Comment by simonc** [comment]
I second @bessey in thanking you for all the hard work and time spent on the extension. Wishing you all the best ❤️

**Comment by drewlustro** [comment]
Cheers @wingrunr21 !

**Comment by Robaert-codes** [comment]
I can only add my gratitude to the predecessors here:

Thanks for putting out that great tooling to the community, @wingrunr21, @rebornix !

For me it made a big difference in my ruby experience - as more of an occasional user of ruby  for data mangling and test drivers against REST interfaces. Oh - and to remotely control Excel with a language so much more powerful and handy than VBA.

Let's see if we will have a much fun with the new tooling out there.

Thanks again, take care! :heart:

**Comment by jtbg** [comment]
Thanks for all your work @wingrunr21. Absolute hero

**Comment by gastonmorixe** [comment]
Thank you
