### ISSUE TITLE
unable to execute bundle exec rubocop and reek, but the same commands work in terminal

### ISSUE THREAD

**Issue by Juraci** [rubyide/vscode-ruby#816]
### Your environment

- `vscode-ruby` version: v0.28.0
- Ruby version: 2.7.5p203 (2021-11-24 revision f69aeb8314) [x86_64-linux]
- Ruby version manager (if any): rvm
- VS Code version: 1.66.2
- Operating System: Arch Linux
- Using language server? (eg `useLanguageServer` is true in your configuration?): yes

### Expected behavior

this should work from inside the editor
```
Lint: executing bundle exec rubocop -s '/home/juraci/personal/wy-cash-tdd/lib/money.rb' -f json...
Lint: executing bundle exec reek -f json --stdin-filename '/home/juraci/personal/wy-cash-tdd/lib/money.rb'
```

### Actual behavior

```
Lint: unable to execute bundle exec rubocop -s '/home/juraci/personal/wy-cash-tdd/lib/money.rb' -f json as the command could not be found
Lint: unable to execute bundle exec reek -f json --stdin-filename '/home/juraci/personal/wy-cash-tdd/lib/money.rb' as the command could not be found
```

Executing the same commands manually in the terminal against the same file does work:
rubocop
![screenshot_20220424_192233](https://user-images.githubusercontent.com/2266929/164999192-56c24229-40cb-4391-bde4-ef7c426f56ec.png)

reek
![screenshot_20220424_192316](https://user-images.githubusercontent.com/2266929/164999196-cc099676-1701-40e0-b8f7-8ecfd60b3ed3.png)

my settings file:
```
{
  "vim.easymotion": true,
  "vim.incsearch": true,
  "vim.useSystemClipboard": true,
  "vim.useCtrlKeys": true,
  "vim.hlsearch": true,
  "vim.insertModeKeyBindings": [
    {
      "before": ["k", "j"],
      "after": ["<Esc>"]
    }
  ],
  "vim.normalModeKeyBindingsNonRecursive": [
    {
      "before": ["<leader>", "d"],
      "after": ["d", "d" ]
    },
    {
      "before": [
        "<C-n>"
      ],
      "commands": [
        ":nohl"
      ]
    },
    {
      "before": [
        "K"
      ],
      "commands": [
        "lineBreakInsert"
      ],
      "silent": true
    }
  ],
  "vim.leader": "<space>",
  "vim.handleKeys": {
    "<C-a>": false,
    "<C-f>": false
  },
  "workbench.colorTheme": "One Dark Pro",
  "ruby.useBundler": true,
  "ruby.useLanguageServer": true,
  "ruby.lintDebounceTime": 3500,
  "ruby.lint": {
    "rubocop": {
      "useBundler": true
    },
    "reek": {
      "useBundler": true
    }
  },
  "ruby.format": "rubocop",
  "workbench.iconTheme": "material-icon-theme"
}
```

**Comment by noniq** [comment]
It could be related to the shell that is used to run subprocesses. I recently stumbled upon a similar issue in https://github.com/castwide/vscode-solargraph/issues/238 , where it uses the system default shell (`zsh`) to run subprocesses, but the setup for my Ruby environment is in the init files of `bash` (because that’s the shell I use personally).
