### ISSUE TITLE
Files: Default Language is interrupted 

### ISSUE THREAD

**Issue by ShalokShalom** [rubyide/vscode-ruby#830]
### Your environment

- `vscode-ruby` version: current
- Ruby version: 3.0
- Ruby version manager (if any): no
- VS Code version: current
- Operating System: Linux
- Using language server? (eg `useLanguageServer` is true in your configuration?)

### Expected behavior

There is a setting in VSCode, that is called Files: Default Language and when you put ruby into this field, it is expected that this opens every new file as .rb. 

### Actual behavior

With your extension, it opens as .arb.

You are responsible for [this](https://stackoverflow.com/questions/69471158/what-are-the-differences-between-rb-and-arb-files) and [this](https://github.com/microsoft/vscode/issues/158187).

**Comment by r7kamura** [comment]
This is the same issue as https://github.com/rubyide/vscode-ruby/issues/770, and will be fixed by https://github.com/rubyide/vscode-ruby/pull/814.
