### ISSUE TITLE
Add class name support to QuickOpen Symbol Search

### ISSUE THREAD

**Issue by thibaut-pro** [rubyide/vscode-ruby#832]
### Your environment

- `vscode-ruby` version: v0.28.1
- Ruby version: ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-darwin20]
- Ruby version manager (if any): asdf
- VS Code version: 1.69.2 (Universal)
- Operating System: MacOS (Intel Chip)
- Using language server? true

### Expected behavior

A search for a class name (e.g. `User::Searcher`) returns results that match.

### Actual behavior

Currently that does not work:
![image](https://user-images.githubusercontent.com/59576766/185839079-708d5fd8-8260-4697-9a3a-8d9afadf3c7e.png)
Even though
![image](https://user-images.githubusercontent.com/59576766/185839091-b30d07a5-3e35-4f47-b179-e1412417427c.png)

I initially opened an issue with VSCode: https://github.com/microsoft/vscode/issues/155099
@TylerLeonhardt recommended that this get fixed in the extension instead by registering symbols.

**Comment by GodAlmighty777** [comment]
> ![Screenshot_2022-09-13-16-46-36-041_com.vkontakte.android.jpg](https://user-images.githubusercontent.com/112938033/189959912-ef20025a-ac5f-4b92-9399- - - [ ] ## -3dbe9fc9cfbf.jpg)[]()@factormystic ~~````

````~~
