### ISSUE TITLE
ruby 3.x support

### ISSUE THREAD

**Issue by dedsecezio** [rubyide/vscode-ruby#836]
I am using `ruby 3.1.2` and I have configuration the same as the [docs/debugger.md](https://github.com/rubyide/vscode-ruby/blob/main/docs/debugger.md) examples (especially the simplest `launch.json` configuration example), but the debugger isn't working. I suppose the problem occurs because the new version of ruby isn't fully supported by this extension?

**Comment by ledsun** [comment]
I think what you want is https://github.com/ruby/vscode-rdbg .
