### ISSUE TITLE
Foreman start debugging

### ISSUE THREAD

**Issue by ricardo-yuxi** [rubyide/vscode-ruby#87]
### Your environment
- `vscode-ruby` version: 0.9.0
- Ruby version: 1.9.3-p374
- VS Code version: 1.6.1
- Operating System: Mac
### Expected behavior

Debug a rails app using foreman
### Actual behavior

I can't execute debug using `foreman start`

Cheers

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
