### ISSUE TITLE
No bracket matching in string interpolation syntax

### ISSUE THREAD

**Issue by atombender** [rubyide/vscode-ruby#88]
### Your environment

- `vscode-ruby` version: 0.10.1
- Ruby version: 2.3
- VS Code version: 1.7.1
- Operating System: macOS 10.12.1

### Expected behavior

Brackets (parantheses, etc.) should match inside strings. For example:

```
s = "hello, #{name}"
s = "hello, #{get_name(name)}"
s = "hello, #{[name].join}"
```

None of these do bracket matching — neither highlight nor `editor.action.jumpToBracket`.

### Actual behavior

I expected bracket matching to work. Both highlighting of matching brackets, and jumping via `editor.action.jumpToBracket`.

**Comment by atombender** [comment]
I just realized this might be in VSCode itself, which comes with its own Ruby syntax?

**Comment by HookyQR** [comment]
It is VSCode, but it's not the ruby syntax. This doesn't work in javascript or typescript interpreted strings either. I guess it's just not a thing. _(yet?)_

**Comment by alexanderadam** [comment]
Just to be sure: would automatically adding `{` and `}` when typing `#` in a string also be a VSCode issue or could this be added to `vscode-ruby`?

**Comment by amunoz951** [comment]
Was a VSCode issue opened for this? Link?

**Comment by Overload119** [comment]
This was the first result from Google - so I found https://marketplace.visualstudio.com/items?itemName=aliariff.auto-add-brackets which does what I want.
