### ISSUE TITLE
Debugging rails starts and exits immediately

### ISSUE THREAD

**Issue by RichardJECooke** [rubyide/vscode-ruby#91]
### Your environment

- `vscode-ruby` version: 0.10.3
- Ruby version:  2.3.0
- VS Code version: 1.7.2
- Operating System: Ubuntu 16.04 (in VirtualBox on Windows 10)
- Hardware (optional): Acer Aspire V15

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !
- This gem does not exist so I can't install it (nor is it in your docs, weird) : `ruby-debug-basex19`

### Expected behavior
Rails runs

### Actual behavior
Rails starts (perhaps) and stops.  See here:
![test](https://cloud.githubusercontent.com/assets/5468805/20559210/27287250-b17c-11e6-909a-49a742cb3f0d.gif)

### Steps to reproduce the problem
Use this launch.json setting, hit run:
```json
    {
      "name": "Rails server",
      "type": "Ruby",
      "request": "launch",
      "showDebuggerOutput": true,
      "useBundler": true,
      "cwd": "${workspaceRoot}",
      "program": "/home/rje/.rvm/gems/ruby-2.3.0/bin/bundle",
      "args": [ "exec", "rails", "s" ]
    }
```

**Comment by HookyQR** [comment]
Hi @RichardJECooke, your configuration section should look more like this:
```javascript
{
	"name": "Rails server",
	"type": "Ruby",
	"request": "launch",
	"cwd": "${workspaceRoot}",
	"useBundler": true,
	"pathToBundler": "/home/rje/.rvm/gems/ruby-2.3.0/bin/bundle",
	"program": "rails",
	"args": ["server"]
}
```

**Comment by RichardJECooke** [comment]
Thanks, but now it doesn't even start - it tries to find a program called "rails" in my project:

```
Fast Debugger (ruby-debug-ide 0.6.0, debase 0.2.1, file filtering is supported) listens on 127.0.0.1:1234
Uncaught exception: cannot load such file -- /home/rje/projects/rentalconnect/rails
	/home/rje/.rvm/gems/ruby-2.3.0/bin/rdebug-ide:23:in `load'
	/home/rje/.rvm/gems/ruby-2.3.0/bin/rdebug-ide:23:in `<main>'
	/home/rje/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	/home/rje/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
/home/rje/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_load': cannot load such file -- /home/rje/projects/rentalconnect/rails (LoadError)
	from /home/rje/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.0/lib/ruby-debug-ide.rb:88:in `debug_program'
	from /home/rje/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.0/bin/rdebug-ide:130:in `<top (required)>'
	from /home/rje/.rvm/gems/ruby-2.3.0/bin/rdebug-ide:23:in `load'
	from /home/rje/.rvm/gems/ruby-2.3.0/bin/rdebug-ide:23:in `<main>'
	from /home/rje/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/rje/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by rebornix** [comment]
@RichardJECooke it seems that Code has no clue about system env so it tries to find `rails` in current workspace, you may want to change `program` to `rails`'s absolute path.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
