### ISSUE TITLE
Variables can't be evaluated and watched in the Debug view WATCH section

### ISSUE THREAD

**Issue by noku** [rubyide/vscode-ruby#93]
### Your environment

- `vscode-ruby` version: 0.10.3
- Ruby version: `2.2.3`
- VS Code version: 1.7.1
- Operating System: MACOSX 10.11.4
- Hardware (optional): 

Make sure you have `ruby`, `ruby-debug-ide` and `ruby-debug-basex19` installed before submitting your issue -- thank you !

### Expected behavior

Variables and expressions can be evaluated and watched in the Debug view **WATCH** section.

### Actual behavior

Variables and expressions **can't** be evaluated and watched in the Debug view **WATCH** section.

<img width="845" alt="screenshot 2016-11-25 13 33 34" src="https://cloud.githubusercontent.com/assets/2285726/20624296/bf78f540-b314-11e6-96c4-766c4cf61cf6.png">

### Steps to reproduce the problem

- Add a variable or expression to **WATCH** section.
- Try to evaluate it.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
