### ISSUE TITLE
Debugger does not work with SketchUp + sketchup-ruby-debugger

### ISSUE THREAD

**Issue by seraku24** [rubyide/vscode-ruby#95]
### Your environment
- `vscode-ruby` version: 0.10.3
- Ruby version: (*) 2.2.5p319 (2016-04-26 revision 54774) [x64-mingw32]
- VS Code version: 1.7.2
- Operating System: Windows 10 Pro, Version 1511 (OS Build 10586.679)
- Hardware (optional): Intel® Core™2 Duo T9500 2.60 GHz, 6.00 GB RAM

(*) The Ruby version listed above is the stand-alone version installed on the machine, however SketchUp uses its own embedded Ruby environment, that is reportedly based on some 2.2.x version.

Installed gems:
```
bigdecimal (default: 1.2.6)
debase (0.2.1)
debase-ruby_core_source (0.9.4)
io-console (default: 0.4.3)
json (default: 1.8.1)
minitest (5.4.3)
power_assert (0.2.2)
psych (default: 2.0.8)
rake (default: 10.4.2)
rdoc (default: 4.2.0)
ruby-debug-ide (0.4.33)
rubygems-update (2.6.8)
test-unit (3.0.8)
```

- SketchUp: Make, Version 17.1.174 64-bit
- `sketchup-ruby-debugger` version: 1.0.2.0

### Expected behavior
Debugger attaches and supports basic debugging functionality, such as stopping at a breakpoint and resuming execution.

### Actual behavior
Debugger attaches and appears to react to the breakpoint that was set.  However, no line is highlighted and pressing "go" does not resume execution, leaving the SketchUp process frozen.

### Steps to reproduce the problem
1. Open the SketchUp plugins folder (e.g. `%APPDATA%\SketchUp\SketchUp 2017\SketchUp\Plugins`) within vscode.
2. Configure `.vscode\launch.json` as follows:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Attach",
            "type": "Ruby",
            "request": "attach",
            "cwd": "${workspaceRoot}",
            "remoteWorkspaceRoot": "${workspaceRoot}",
            "remoteHost": "127.0.0.1",
            "remotePort": "1234"
        }
    ]
}
```
3. Add `tut_hello_cube.rb` to the project:
```ruby
require 'sketchup.rb'
require 'extensions.rb'

module Examples
  module HelloCube

    unless file_loaded?(__FILE__)
      ex = SketchupExtension.new('Hello Cube', 'tut_hello_cube/main')
      ex.description = 'SketchUp Ruby API example creating a cube.'
      ex.version     = '1.0.0'
      ex.copyright   = 'Trimble Navigations © 2016'
      ex.creator     = 'SketchUp'
      Sketchup.register_extension(ex, true)
      file_loaded(__FILE__)
    end

  end # module HelloCube
end # module Examples
```
4. Add `tut_hello_cube\main.rb` to the project:
```ruby
require 'sketchup.rb'

module Examples
  module HelloCube

def self.create_cube
  model = Sketchup.active_model
  model.start_operation('Create Cube', true)
  group = model.active_entities.add_group
  entities = group.entities
  points = [
    Geom::Point3d.new(0,   0,   0),
    Geom::Point3d.new(1.m, 0,   0),
    Geom::Point3d.new(1.m, 1.m, 0),
    Geom::Point3d.new(0,   1.m, 0)
  ]
  face = entities.add_face(points)
  face.pushpull(-1.m)
  model.commit_operation
end

unless file_loaded?(__FILE__)
  menu = UI.menu('Plugins')
  menu.add_item('Create Cube Example') {
    self.create_cube
  }

  file_loaded(__FILE__)
end

  end # module HelloCube
end # module Examples
```
5. Ensure all breakpoints are cleared.
6. Launch SketchUp with the following command-line arguments: `SketchUp.exe -rdebug "ide port=1234"`
7. Dismiss the splash screen and wait for the SketchUp process to hang awaiting the debugger.
8. Start the debugger in vscode.
9. From SketchUp, use the tutorial extension (i.e. Extensions > Create Cube Example), noting that a cube appears.
10. Delete the cube that was created.
11. Add a breakpoint to `main.rb` within `self.create_cube` (e.g. line 17).
12. Repeat step 9, except note that now the SketchUp process will hang and the debugger controls in vscode reflect that execution is paused, however no line in the source is highlighted.
13. Try to resume execution from vscode, but note that the SketchUp process remains frozen.

For reference, the tutorial extension used above comes from http://developer.sketchup.com/en/content/tuthellocubemainrb.

This issue might be related to SketchUp/sketchup-ruby-debugger#7.

**Comment by thomthom** [comment]
This can be closed, as changes were made to the SketchUp Ruby Debugger server.

**Comment by wingrunr21** [comment]
Closing for issue cleanup. Apologies if this is still an issue. We are working to improve the core extension experience.
