### ISSUE TITLE
Minor issue - gulpfile.js specifies incorrect path for source maps.

### ISSUE THREAD

**Issue by seraku24** [rubyide/vscode-ruby#97]
*This is a minor issue, only affecting the ability to debug the debug adapter itself.*

`gulpfile.js` specifies a value of `../../src` for `sourcePath`.  However, the `out` directory is a sibling to the `src` directory, so the relative path should be just `../src`.

After I made this change in my fork, I was finally able to set breakpoints while debugging the extension.  Is there a good reason why the path is set the way it is?

**Comment by HookyQR** [comment]
Maybe it has moved around at some point. Doesn't seem logical though. Submit a PR to fix it.
